[package]
name = "disrobe-pass-lua"
description = "Lua + LuaJIT + Roblox Luau bytecode readers + decompilers + obfuscator reversers: Prometheus, MoonSec V1/V2/V3, Ironbrew2, AztupBrew, DarkSec, Boronide, PSU, WeAreDevs, luaobfuscator.com."
version.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
keywords = ["lua", "luajit", "luau", "roblox", "deobfuscation"]
categories.workspace = true

[lints]
workspace = true

[dependencies]
disrobe-bytes = { workspace = true }
disrobe-cfg = { workspace = true }
disrobe-core = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
flate2 = { workspace = true }
brotli-decompressor = "5.0.0"

[features]
default = []
chain = ["disrobe-core/chain"]

[dev-dependencies]
disrobe-binfmt = { workspace = true }
tempfile = "3"
