#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]
use std::path::PathBuf;

use disrobe_pass_lua::luraph;
use disrobe_pass_lua::obfuscator::{
    DeobfOptions, LuaObfuscatorKind, ObfuscatorDetection, PeelResult,
};

fn signature_fixture() -> Vec<u8> {
    let manifest_dir: &str = env!("CARGO_MANIFEST_DIR");
    let mut p: PathBuf = PathBuf::from(manifest_dir);
    p.push("..");
    p.push("..");
    p.push("corpus");
    p.push("lua");
    p.push("luraph");
    p.push("signature_header.lua");
    std::fs::read(&p).unwrap_or_else(|e| panic!("luraph fixture missing at {}: {e}", p.display()))
}

#[test]
fn detects_luraph_header_and_macros() {
    let bytes: Vec<u8> = signature_fixture();
    let det: ObfuscatorDetection =
        luraph::detect(&bytes).expect("must detect Luraph from header + macros");
    assert_eq!(det.kind, LuaObfuscatorKind::Luraph);
    assert!(det.confidence >= 90, "header hit must be high confidence");
    assert!(
        det.markers.iter().any(|m: &String| m.contains("Luraph")),
        "must report the Luraph header marker, got {:?}",
        det.markers
    );
    assert!(
        det.markers.iter().any(|m: &String| m.contains("LPH_")),
        "must report at least one LPH_ macro marker, got {:?}",
        det.markers
    );
}

#[test]
fn detects_on_macros_only() {
    let src: &[u8] = b"local x = LPH_ENCFUNC(function() end)\nlocal y = LPH_STRING\n";
    let det: ObfuscatorDetection = luraph::detect(src).expect("two LPH_ macros alone must detect");
    assert_eq!(det.kind, LuaObfuscatorKind::Luraph);
    assert!(det.confidence >= 80);
}

#[test]
fn does_not_fire_on_clean_lua() {
    let src: &[u8] = b"local function add(a, b) return a + b end\nprint(add(1, 2))\n";
    assert!(luraph::detect(src).is_none());
}

#[test]
fn peel_reports_the_failed_static_refutation() {
    let bytes: Vec<u8> = signature_fixture();
    let out: PeelResult =
        luraph::peel(&bytes, &DeobfOptions::default()).expect("peel returns a wall result");

    assert!(
        !out.fully_recovered,
        "this fixture must not fabricate Luraph recovery"
    );
    assert!(out.passes_run.is_empty(), "no recovery pass can run");
    assert_eq!(
        out.deobfuscated, bytes,
        "input must pass through unchanged at the wall"
    );
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("static refutation attempted")),
        "must record the refutation attempt, got {:?}",
        out.residual_markers
    );
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("LPH bytecode-shaped")),
        "must report the rejected LPH bytecode-shaped string, got {:?}",
        out.residual_markers
    );
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("runtime key material")),
        "must report the runtime key source, got {:?}",
        out.residual_markers
    );
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("WALL")),
        "must declare the wall explicitly, got {:?}",
        out.residual_markers
    );
}

#[test]
fn peel_reports_literal_key_and_static_tables_when_present() {
    let src: &[u8] = br"
-- This file was generated by Luraph (lura.ph)
local script_key = 0x20 + 2
local e = { 1,2,3,4,5,6,7,8 }
local u = { 8,7,6,5,4,3,2,1 }
local Y = { 10,11,12,13,14,15,16,17 }
local LPH_ENCFUNC = nil
local LPH_STRING = nil
return function() end
";
    let out: PeelResult =
        luraph::peel(src, &DeobfOptions::default()).expect("peel returns a wall result");

    assert!(!out.fully_recovered);
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("literal script key")),
        "must report literal script key, got {:?}",
        out.residual_markers
    );
    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("static bootstrap table candidates")),
        "must report static tables, got {:?}",
        out.residual_markers
    );
    assert!(
        !out.residual_markers
            .iter()
            .any(|m: &String| m.contains("no literal script key")),
        "must not repeat the absent-key wall when a literal key exists: {:?}",
        out.residual_markers
    );
}

#[test]
fn peel_reports_literal_string_key_length() {
    let src: &[u8] = br#"
-- obfuscated using Luraph
local LURAPH_SCRIPT_KEY = "\x41\066C"
local LPH_ENCFUNC = nil
local LPH_STRING = nil
"#;
    let out: PeelResult =
        luraph::peel(src, &DeobfOptions::default()).expect("peel returns a wall result");

    assert!(
        out.residual_markers
            .iter()
            .any(|m: &String| m.contains("3 byte string")),
        "must report decoded literal string-key length, got {:?}",
        out.residual_markers
    );
}
