#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use disrobe_pass_lua::obfuscator::{
    DeobfOptions, LuaObfuscatorKind, ObfuscatorDetection, PeelResult,
};
use disrobe_pass_lua::prometheus;

const SAMPLE: &[u8] = br#"-- prometheus
-- Generated by Prometheus
local _0xConst = { "hello" }
print(_0xConst[1])
"#;

#[test]
fn detect_prometheus_marker() {
    let det: ObfuscatorDetection = prometheus::detect(SAMPLE).expect("must detect");
    assert_eq!(det.kind, LuaObfuscatorKind::Prometheus);
    assert!(det.confidence >= 80);
    assert!(
        det.markers
            .iter()
            .any(|m: &String| m.contains("prometheus"))
    );
}

#[test]
fn peel_prometheus_reports_honest_status() {
    let opts: DeobfOptions = DeobfOptions::default();
    let out: PeelResult = prometheus::peel(SAMPLE, &opts).expect("peel");
    assert!(
        !out.fully_recovered,
        "prometheus static peel is not implemented; must not claim full recovery"
    );
    assert!(
        !out.residual_markers.is_empty(),
        "must document why it cannot peel"
    );
}

#[test]
fn prometheus_rejects_unsigned_source() {
    let opts: DeobfOptions = DeobfOptions::default();
    let err: disrobe_pass_lua::Error = prometheus::peel(b"print(1)", &opts).unwrap_err();
    assert!(matches!(
        err,
        disrobe_pass_lua::Error::NoObfuscatorSignature("Prometheus")
    ));
}
