pub mod appimage;
pub mod cramfs;
pub mod docker;
pub mod ext4;
pub mod flatpak;
pub mod innosetup;
pub mod installshield;
pub mod msi;
pub mod msix;
pub mod nsis;
pub mod oci;
pub mod ostree;
pub mod snap;
pub mod squashfs;

pub use appimage::{AppImageLayout, parse_appimage};
pub use cramfs::detect_cramfs;
pub use docker::{DockerManifest, parse_docker_manifest};
pub use ext4::detect_ext4;
pub use flatpak::flatpak_external_hint;
pub use innosetup::innosetup_external_hint;
pub use installshield::installshield_external_hint;
pub use msi::{MsiSummary, parse_msi_minimal};
pub use msix::{MsixManifest, parse_appx_manifest};
pub use nsis::{NsisHeader, detect_nsis};
pub use oci::{OciManifest, parse_oci_index, parse_oci_manifest};
pub use ostree::ostree_external_hint;
pub use snap::detect_snap;
pub use squashfs::{SquashfsSuperblock, parse_squashfs_superblock};
