"""Type stubs for the disrobe Python bindings."""

from typing import Any, Literal, TypedDict, Union

__version__: str
__doc__: str

Pack = Literal["pack-1", "pack-2", "pack-3", "pack-4"]
SourceLanguage = Literal["python", "py", "python3"]
ByteLanguage = Literal[
    "python-bytecode",
    "pyc",
    "jvm-class",
    "class",
    "dex",
    "beam",
    "hermes",
    "hermes-bundle",
    "hbc",
    "wasm",
]
ParseLanguage = Union[SourceLanguage, ByteLanguage]

class LlmBundle(TypedDict, total=False):
    """Top-level shape of `result["llm"]` when an LLM metadata pack was emitted.

    Mirrors the on-disk `disrobe.metadata.llm.v1` schema produced by the CLI
    `--llm` flag family. Keys present depend on which `pack` was requested.
    """

    schema: str
    schema_version: str
    generated_at: str
    tool: dict[str, Any]
    selection: dict[str, Any]
    input: dict[str, Any]
    pipeline: list[dict[str, Any]]
    categories: dict[str, Any]

class DisrobeError(Exception):
    """Raised by every disrobe binding when the underlying pass fails."""

class UnsupportedLanguage(DisrobeError):
    """Raised by `disasm`, `parse`, `compile` for languages with no backing
    implementation in the current build. The message includes a hint pointing
    at the equivalent CLI subcommand or upstream tool."""

def auto(
    input: bytes,
    *,
    max_depth: int = 8,
    path_hint: str | None = None,
) -> dict[str, Any]: ...
def py_decompile(
    pyc_bytes: bytes,
    *,
    roundtrip: bool = False,
    pack: Pack | None = None,
) -> dict[str, Any]: ...
def py_disasm(pyc_bytes: bytes, *, pack: Pack | None = None) -> dict[str, Any]: ...
def py_deob(
    source: str,
    *,
    cleanup: bool = True,
    pack: Pack | None = None,
) -> dict[str, Any]: ...
def py_deob_detect(source: str) -> dict[str, Any]: ...
def py_deob_list_passes() -> list[dict[str, str]]: ...
def py_deob_detect_pass(source: str, pass_id: str) -> dict[str, Any]: ...
def pyarmor_detect(source: str, *, pack: Pack | None = None) -> dict[str, Any]: ...
def pyarmor_unpack(
    wrapper_bytes: bytes,
    *,
    pack: Pack | None = None,
) -> dict[str, Any]: ...
def pyinstaller_extract(image_bytes: bytes) -> dict[str, Any]: ...
def pyinstaller_entry_bytes(image_bytes: bytes, entry_name: str) -> bytes: ...
def nuitka_detect(image_bytes: bytes) -> dict[str, Any]: ...
def nuitka_extract(image_bytes: bytes) -> dict[str, Any]: ...
def hermes_disasm(bundle_bytes: bytes) -> dict[str, Any]: ...
def hermes_lift(bundle_bytes: bytes) -> dict[str, Any]: ...
def hermes_info(bundle_bytes: bytes) -> dict[str, Any]: ...
def macho_dump(macho_bytes: bytes) -> dict[str, Any]: ...
def jvm_parse_class(class_bytes: bytes) -> dict[str, Any]: ...
def jvm_parse_dex(dex_bytes: bytes) -> dict[str, Any]: ...
def jvm_detect(class_bytes: bytes) -> list[dict[str, Any]]: ...
def jvm_backends() -> dict[str, Any]: ...
def dotnet_parse_pe(pe_bytes: bytes) -> dict[str, Any]: ...
def dotnet_parse_metadata(pe_bytes: bytes) -> dict[str, Any]: ...
def dotnet_detect(pe_bytes: bytes) -> dict[str, Any]: ...
def dotnet_analyze(pe_bytes: bytes) -> dict[str, Any]: ...
def dotnet_backends() -> list[dict[str, Any]]: ...
def wasm_analyze(wasm_bytes: bytes) -> dict[str, Any]: ...
def wasm_detect(wasm_bytes: bytes) -> dict[str, Any]: ...
def js_detect(js_source: str) -> dict[str, Any]: ...
def js_unminify(js_source: str) -> dict[str, Any]: ...
def js_unbundle(js_source: str, *, bundler: str | None = None) -> dict[str, Any]: ...
def native_format(binary_bytes: bytes) -> dict[str, Any]: ...
def native_detect(binary_bytes: bytes) -> list[dict[str, Any]]: ...
def native_probe_backends() -> list[dict[str, Any]]: ...
def envelope_create(
    payload: bytes,
    *,
    source_label: str = "inline",
    produced_by: str | None = None,
    detected_format: str | None = None,
) -> bytes: ...
def envelope_verify(envelope_bytes: bytes) -> dict[str, Any]: ...
def disasm(language: str, source: str | bytes) -> str: ...
def parse(language: str, source: str | bytes) -> dict[str, Any]: ...
def compile(language: str, source: str, *, version: str | None = None) -> bytes: ...
