"""Typed stubs for the disrobe Python bindings.

Every disrobe CLI capability is mirrored here as a typed library function.
Analysis functions return concrete report objects (not bare dicts); each report
exposes typed attribute accessors plus a ``raw`` dict escape hatch carrying the
full underlying record, a ``to_json()`` serializer, and ``from_json_str`` /
``from_obj`` constructors.
"""

from typing import Any, Literal, Protocol, Self, TypedDict, Union, runtime_checkable

__version__: str
__doc__: str

Pack = Literal["pack-1", "pack-2", "pack-3", "pack-4"]
SourceLanguage = Literal["python", "py", "python3"]
JsLanguage = Literal["javascript", "js", "typescript", "ts"]
ByteLanguage = Literal[
    "python-bytecode",
    "pyc",
    "jvm-class",
    "class",
    "dex",
    "beam",
    "hermes",
    "hermes-bundle",
    "hbc",
    "wasm",
]
ParseByteLanguage = Literal[
    "go",
    "swift",
    "objc",
    "objective-c",
    "kotlin",
    "ruby",
    "lua",
    "php",
]
DisasmByteLanguage = Literal[
    "ruby",
    "ruby-bytecode",
    "yarv",
    "mruby",
    "php",
    "php-bytecode",
]
DecompileLanguage = Literal[
    "python-bytecode",
    "pyc",
    "jvm-class",
    "class",
    "java",
    "kotlin",
    "lua",
    "ruby",
    "php",
    "php-bytecode",
    "javascript",
    "js",
    "typescript",
    "ts",
]
ParseLanguage = Union[SourceLanguage, ByteLanguage, JsLanguage, ParseByteLanguage]
SymbolKind = Literal["function", "data", "label", "export", "import"]
InstructionFlow = Literal[
    "sequential",
    "call",
    "indirect-call",
    "conditional-branch",
    "unconditional-branch",
    "indirect-branch",
    "return",
    "interrupt",
]

class LlmBundle(TypedDict, total=False):
    """Top-level shape of ``result["llm"]`` when an LLM metadata pack was emitted.

    Mirrors the on-disk ``disrobe.metadata.llm.v1`` schema produced by the CLI
    ``--llm`` flag family. Keys present depend on which ``pack`` was requested.
    """

    schema: str
    schema_version: str
    generated_at: str
    tool: dict[str, Any]
    selection: dict[str, Any]
    input: dict[str, Any]
    pipeline: list[dict[str, Any]]
    categories: dict[str, Any]

class DisrobeError(Exception):
    """Raised by every disrobe binding when the underlying pass fails."""

class UnsupportedLanguage(DisrobeError):
    """Raised by ``disasm``, ``parse``, ``compile``, ``decompile`` for languages
    with no backing implementation in the current build. The message includes a
    hint pointing at the equivalent CLI subcommand or upstream tool."""

class _Report:
    """Base shape shared by every typed analysis report.

    Concrete subclasses add field accessors; this base documents the common
    serialization surface every report carries.
    """

    @property
    def raw(self) -> dict[str, Any]:
        """The full underlying record as a nested dict (no detail dropped)."""
        ...

    def to_json(self) -> str:
        """Serialize the full record to a compact JSON string."""
        ...

    @classmethod
    def from_json_str(cls, text: str) -> Self:
        """Rebuild a report from a JSON string produced by ``to_json``."""
        ...

    @classmethod
    def from_obj(cls, obj: dict[str, Any]) -> Self:
        """Wrap an already-decoded dict as a typed report."""
        ...

class CanonicalSource(_Report):
    """Recovered source text for one language target."""

    @property
    def source(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...
    @property
    def produced_by(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...

class DisasmPayload(_Report):
    """Recovered disassembly: functions, instruction stream, and symbols."""

    @property
    def instruction_count(self) -> int: ...
    @property
    def symbol_count(self) -> int: ...
    @property
    def source_hash(self) -> str | None: ...

class FunctionList(_Report):
    """Query result over a module's recovered functions."""

    @property
    def kind(self) -> str | None: ...
    @property
    def count(self) -> int: ...

class QueryReport(_Report):
    """Result of a single IR query."""

    @property
    def kind(self) -> str | None: ...
    @property
    def match_count(self) -> int: ...

class CallGraph(_Report):
    """Whole-program call graph: nodes and call-instruction edges."""

    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...

class Capabilities(_Report):
    """Capability rule-set match report for a native binary."""

    @property
    def match_count(self) -> int: ...
    @property
    def format(self) -> str | None: ...

class ExtractionResult(_Report):
    """Container/firmware extraction result with carved member entries."""

    @property
    def kind(self) -> str | None: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def integrity_violation_count(self) -> int: ...

class OverlayReport(_Report):
    """Recursive carve report: per-chunk classification, entropy, nesting."""

    @property
    def max_depth(self) -> int | None: ...
    @property
    def nodes_visited(self) -> int | None: ...
    @property
    def chunks_total(self) -> int | None: ...
    @property
    def bytes_carved(self) -> int | None: ...

class EntropyReport(_Report):
    """Sliding-window Shannon entropy map of a binary."""

    @property
    def window_count(self) -> int: ...
    @property
    def mean(self) -> float | None: ...
    @property
    def min(self) -> float | None: ...
    @property
    def max(self) -> float | None: ...

class StringsReport(_Report):
    """Extracted ASCII/UTF-16 strings with optional deobfuscation."""

    @property
    def string_count(self) -> int: ...

class IocReport(_Report):
    """Indicators of compromise harvested from bytes and recovered strings."""

    @property
    def indicator_count(self) -> int: ...

class BehaviorReport(_Report):
    """Behavioral summary of a binary by category, with MITRE ATT&CK ids."""

    @property
    def category_count(self) -> int: ...

class IdentifyReport(_Report):
    """Compiler/linker/packer/protector/installer fingerprint of a binary."""

    @property
    def format(self) -> str | None: ...
    @property
    def finding_count(self) -> int: ...

class SecretScanReport(_Report):
    """Leaked-credential scan result over raw bytes."""

    @property
    def finding_count(self) -> int: ...

class SymbolsReport(_Report):
    """Symbols, sections, segments, imports, and debug info of a binary."""

    @property
    def symbol_count(self) -> int: ...
    @property
    def section_count(self) -> int: ...
    @property
    def import_count(self) -> int: ...

class SbomReport(_Report):
    """CycloneDX 1.5 SBOM from an embedded cargo-auditable section."""

    @property
    def component_count(self) -> int: ...
    @property
    def bom_format(self) -> str | None: ...
    @property
    def spec_version(self) -> str | None: ...

class FingerprintReport(_Report):
    """Aggregated crypto-constant + FLIRT + string-xref fingerprint sidecar."""

    @property
    def crypto_hit_count(self) -> int: ...

class SignatureReport(_Report):
    """Crypto-primitive signatures and optional FLIRT matches."""

    @property
    def signature_count(self) -> int: ...

class SigmakerReport(_Report):
    """Wildcarded byte signature for a function at a virtual address."""

    @property
    def ida_pattern(self) -> str | None: ...
    @property
    def byte_count(self) -> int: ...

class DiffReport(_Report):
    """Function-level diff of two binaries."""

    @property
    def added(self) -> int: ...
    @property
    def removed(self) -> int: ...
    @property
    def changed(self) -> int: ...

class PatchReport(_Report):
    """Result of rewriting native bytes and revalidating the image."""

    @property
    def at(self) -> int | None: ...
    @property
    def bytes_written(self) -> int | None: ...
    @property
    def revalidated(self) -> bool: ...

class YaraReport(_Report):
    """Parsed YARA ruleset AST, or a generated candidate rule."""

    @property
    def rule_count(self) -> int: ...

class ChainReport(_Report):
    """End-to-end chain/auto recovery document."""

    @property
    def spec(self) -> str | None: ...
    @property
    def pass_count(self) -> int: ...
    @property
    def terminated(self) -> bool: ...

class EnvelopeReport(_Report):
    """Verification report for a .dr envelope."""

    @property
    def verified(self) -> bool: ...
    @property
    def rung(self) -> str | None: ...
    @property
    def version(self) -> int | None: ...
    @property
    def hot_bytes(self) -> int | None: ...
    @property
    def cold_bytes(self) -> int | None: ...
    @property
    def root_hash(self) -> str | None: ...

class Provenance(_Report):
    """Tool/selection/input provenance metadata from an LLM sidecar bundle."""

    @property
    def schema(self) -> str | None: ...
    @property
    def schema_version(self) -> str | None: ...
    @property
    def generated_at(self) -> str | None: ...

RoundtripStatus = Literal[
    "perfect",
    "semantic",
    "code-diff",
    "no-interpreter",
    "recompile-failed",
    "skipped",
]
PyarmorUnpackStatus = Literal["functional", "bcc-partial", "detect-only", "skeleton"]
ContainerListing = Literal["enumerated", "requires-extraction", "unreadable"]

class _LlmReport(_Report):
    """A typed report from an LLM-wired or LLM-aware pass.

    Adds the ``llm`` accessor: a populated ``disrobe.metadata.llm.v1`` bundle on
    the LLM-wired passes (``py_decompile``, ``py_disasm``, ``py_deob``,
    ``pyarmor_detect``, ``pyarmor_unpack``), and ``None`` on every other pass
    that still threads the metadata slot through its record.
    """

    @property
    def llm(self) -> LlmBundle | None: ...

class PyDecompileReport(_LlmReport):
    """Decompiled .pyc: source, marshal/decompile versions, and round-trip outcome."""

    @property
    def source(self) -> str | None: ...
    @property
    def marshal_version(self) -> str | None: ...
    @property
    def decompile_version(self) -> str | None: ...
    @property
    def recovered_directly(self) -> bool: ...
    @property
    def fallback_reason(self) -> str | None: ...
    @property
    def roundtrip_status(self) -> RoundtripStatus | None: ...
    @property
    def roundtrip_detail(self) -> str | None: ...
    @property
    def interpreter_path(self) -> str | None: ...
    @property
    def interpreter_version(self) -> str | None: ...

class PyDisasmReport(_LlmReport):
    """Python bytecode disassembly: marshal version, instruction count, listing."""

    @property
    def marshal_version(self) -> str | None: ...
    @property
    def instruction_count(self) -> int: ...
    @property
    def text(self) -> str | None: ...

class PyDeobReport(_LlmReport):
    """Python deobfuscation: detection, peel trace, and constant-folded cleanup."""

    @property
    def peeled_source(self) -> str | None: ...
    @property
    def cleanup_source(self) -> str | None: ...
    @property
    def layer_count(self) -> int: ...

class PyDeobDetection(_LlmReport):
    """Family-detection verdict for an obfuscated Python source string."""

    @property
    def match_count(self) -> int: ...

class ObfuscatorPass(_Report):
    """One registered Python obfuscator pass, identified by its stable id."""

    @property
    def id(self) -> str | None: ...

class PyarmorDetection(_LlmReport):
    """PyArmor wrapper fingerprint: version, protection, serial, Python, geometry."""

    @property
    def version(self) -> str | None: ...
    @property
    def protection(self) -> str | None: ...
    @property
    def confidence(self) -> str | None: ...
    @property
    def serial(self) -> str | None: ...
    @property
    def python_major(self) -> int | None: ...
    @property
    def python_minor(self) -> int | None: ...
    @property
    def payload_offset(self) -> int | None: ...
    @property
    def payload_size(self) -> int | None: ...

class PyarmorUnpack(_LlmReport):
    """Static PyArmor unpack: status, plaintext geometry, recovery counts."""

    @property
    def status(self) -> PyarmorUnpackStatus | None: ...
    @property
    def pyarmor_version(self) -> str | None: ...
    @property
    def protection_kind(self) -> str | None: ...
    @property
    def plaintext_len(self) -> int | None: ...
    @property
    def plaintext_blake3_hex(self) -> str | None: ...
    @property
    def bcc_blob_count(self) -> int | None: ...
    @property
    def inner_cipher_recovered_co(self) -> int | None: ...

class PyarmorClassification(_Report):
    """PyArmor mode classification: script type, bootstrap import, feature flags."""

    @property
    def script_type(self) -> str | None: ...
    @property
    def bootstrap_import(self) -> str | None: ...
    @property
    def disposition(self) -> str | None: ...
    @property
    def rft_enabled(self) -> bool: ...
    @property
    def ecc_enabled(self) -> bool: ...

class PyInstallerArchive(_LlmReport):
    """PyInstaller image: cookie geometry plus per-entry member metadata."""

    @property
    def entry_count(self) -> int: ...
    @property
    def encrypted(self) -> bool: ...
    @property
    def encryption_key_present(self) -> bool: ...
    @property
    def python_major(self) -> int | None: ...
    @property
    def python_minor(self) -> int | None: ...

class NuitkaDetection(_LlmReport):
    """Nuitka fingerprint: flavor, version, wheel marker, onefile geometry."""

    @property
    def flavor(self) -> str | None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def wheel_marker(self) -> str | None: ...
    @property
    def onefile_payload_offset(self) -> int | None: ...
    @property
    def onefile_payload_compressed(self) -> bool: ...

class NuitkaExtraction(_LlmReport):
    """Nuitka variant extraction: onefile/standalone/module/signed-pe surface."""

    @property
    def variant(self) -> str | None: ...

class HermesDisassembly(_LlmReport):
    """Hermes disassembly: function/identifier/string counts and the listing."""

    @property
    def function_count(self) -> int: ...
    @property
    def identifier_count(self) -> int: ...
    @property
    def string_count(self) -> int: ...

class HermesLift(_LlmReport):
    """Hermes JS-surface lift: recovered tables and function surface."""

    @property
    def function_surface_count(self) -> int: ...
    @property
    def string_count(self) -> int: ...
    @property
    def identifier_count(self) -> int: ...

class HermesInfo(_LlmReport):
    """Hermes bundle header: format version, geometry counts, header size."""

    @property
    def version(self) -> int | None: ...
    @property
    def function_count(self) -> int | None: ...
    @property
    def string_count(self) -> int | None: ...
    @property
    def header_size(self) -> int | None: ...

class MachoReport(_LlmReport):
    """Mach-O dump: image kind, fat-arch entries, per-slice parses."""

    @property
    def kind(self) -> str | None: ...
    @property
    def fat_entry_count(self) -> int: ...
    @property
    def slice_count(self) -> int: ...

class SwiftReport(_LlmReport):
    """Swift/Objective-C reflective metadata: container, fat entries, slices."""

    @property
    def container(self) -> str | None: ...
    @property
    def fat_entry_count(self) -> int: ...
    @property
    def slice_count(self) -> int: ...

class JvmClass(_LlmReport):
    """Parsed JVM classfile: version, constant pool, fields, methods."""

    @property
    def major_version(self) -> int | None: ...
    @property
    def minor_version(self) -> int | None: ...
    @property
    def method_count(self) -> int: ...
    @property
    def field_count(self) -> int: ...
    @property
    def constant_pool_count(self) -> int: ...

class DexFileReport(_LlmReport):
    """Parsed DEX: header plus string, type, and class-descriptor pools."""

    @property
    def string_count(self) -> int: ...
    @property
    def type_count(self) -> int: ...
    @property
    def class_count(self) -> int: ...
    @property
    def method_count(self) -> int: ...

class JvmDecompiledClass(_Report):
    """Pseudo-Java decompilation of a classfile: source plus fidelity counts."""

    @property
    def source(self) -> str | None: ...
    @property
    def method_count(self) -> int: ...
    @property
    def field_count(self) -> int: ...
    @property
    def fully_lifted_methods(self) -> int: ...
    @property
    def fallback_methods(self) -> int: ...

class JvmDecompiledDex(_Report):
    """Pseudo-Java decompilation of a DEX file with per-class source and fidelity counts."""

    @property
    def source(self) -> str | None: ...
    @property
    def source_count(self) -> int: ...
    @property
    def class_count(self) -> int: ...
    @property
    def method_count(self) -> int: ...
    @property
    def fully_lifted_methods(self) -> int: ...
    @property
    def fallback_methods(self) -> int: ...

class DetectionList(_Report):
    """Ordered list of detection hits over an artifact."""

    @property
    def count(self) -> int: ...

class JvmBackends(_LlmReport):
    """Host probe for external JVM and Android decompiler backends."""

    @property
    def jvm_count(self) -> int: ...
    @property
    def android_count(self) -> int: ...

class BackendList(_Report):
    """Probe result per external backend: name, binary, and host availability."""

    @property
    def count(self) -> int: ...
    @property
    def available_count(self) -> int: ...

class ApkResources(_LlmReport):
    """Decoded APK resources: package, entries, manifest XML, certificates, JNI."""

    @property
    def package(self) -> str | None: ...
    @property
    def manifest_xml(self) -> str | None: ...
    @property
    def resource_entry_count(self) -> int: ...
    @property
    def certificate_count(self) -> int: ...
    @property
    def dex_count(self) -> int: ...

class DotnetPe(_LlmReport):
    """Parsed .NET PE: bitness, machine, sections, data directories."""

    @property
    def bitness(self) -> str | None: ...
    @property
    def machine(self) -> int | None: ...
    @property
    def section_count(self) -> int: ...
    @property
    def entry_point_rva(self) -> int | None: ...

class DotnetMetadata(_LlmReport):
    """CLR header plus metadata root: runtime version, version string, streams."""

    @property
    def version(self) -> str | None: ...
    @property
    def major_runtime_version(self) -> int | None: ...
    @property
    def stream_count(self) -> int: ...

class DotnetDetection(_LlmReport):
    """Protector detection for a .NET assembly: matches and primary verdict."""

    @property
    def primary(self) -> str | None: ...
    @property
    def match_count(self) -> int: ...

class DotnetAnalysis(_LlmReport):
    """.NET pass summary: bitness, runtime, native-AOT, protectors, coverage."""

    @property
    def pe_bitness(self) -> str | None: ...
    @property
    def clr_runtime_version(self) -> str | None: ...
    @property
    def native_aot(self) -> bool: ...
    @property
    def primary_protector(self) -> str | None: ...
    @property
    def opcode_spec_coverage_pct(self) -> int | None: ...

class DotnetDecompilation(_LlmReport):
    """Pseudo-C# decompilation: module name plus per-method recovery counts."""

    @property
    def module_name(self) -> str | None: ...
    @property
    def methods_decompiled(self) -> int | None: ...
    @property
    def methods_bodyless(self) -> int | None: ...
    @property
    def methods_failed(self) -> int | None: ...

class DotnetDecoders(_LlmReport):
    """Static string-decoder recovery: pure decoders and recovered constants."""

    @property
    def pure_decoders_found(self) -> int | None: ...
    @property
    def constants_recovered(self) -> int: ...

class WasmAnalysis(_LlmReport):
    """WebAssembly summary: import/export tables, section counts, DWARF."""

    @property
    def import_count(self) -> int: ...
    @property
    def export_count(self) -> int: ...
    @property
    def func_count(self) -> int | None: ...
    @property
    def code_size_bytes(self) -> int | None: ...
    @property
    def has_dwarf(self) -> bool: ...

class WasmDetection(_LlmReport):
    """WebAssembly obfuscator detection: family, confidence, module signals."""

    @property
    def obfuscator(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def has_name_section(self) -> bool: ...
    @property
    def function_count(self) -> int | None: ...

class JsDetection(_LlmReport):
    """JavaScript obfuscator detection: family, confidence, markers."""

    @property
    def family(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def marker_count(self) -> int: ...

class JsUnminify(_LlmReport):
    """JavaScript unminification: recovered source plus per-transform stats."""

    @property
    def source(self) -> str | None: ...

class JsUnbundle(_LlmReport):
    """JavaScript unbundle: per-module recovery from a detected/hinted bundler."""

    @property
    def module_count(self) -> int: ...
    @property
    def bundler(self) -> str | None: ...

class NativeFormat(_LlmReport):
    """Native container format: kind, bitness, subsystem, notes."""

    @property
    def kind(self) -> str | None: ...
    @property
    def bits(self) -> int | None: ...
    @property
    def subsystem(self) -> str | None: ...

class NativeDeobfuscation(_Report):
    """x86 OLLVM/Tigress deobfuscation: deflatten, bogus-branch, substitution."""

    @property
    def bits(self) -> int | None: ...
    @property
    def recovered_blocks(self) -> int | None: ...
    @property
    def original_blocks(self) -> int | None: ...
    @property
    def fully_recovered(self) -> bool: ...

class LuaDetection(_LlmReport):
    """Detected Lua bytecode flavor."""

    @property
    def format(self) -> str | None: ...

class LuaDecompilation(_LlmReport):
    """Lua bytecode decompilation: source, fidelity, warnings."""

    @property
    def source(self) -> str | None: ...
    @property
    def fidelity(self) -> str | None: ...
    @property
    def warning_count(self) -> int: ...

class LuaDeobfuscation(_LlmReport):
    """Lua source deobfuscation: obfuscator, peeled source, recovery state."""

    @property
    def obfuscator(self) -> str | None: ...
    @property
    def deobfuscated(self) -> str | None: ...
    @property
    def fully_recovered(self) -> bool: ...
    @property
    def passes_run_count(self) -> int: ...
    @property
    def recovered_string_count(self) -> int: ...

class GoAnalysis(_LlmReport):
    """Go binary analysis: image kind, pclntab version, build version, garble."""

    @property
    def image_kind(self) -> str | None: ...
    @property
    def pclntab_version(self) -> str | None: ...
    @property
    def buildversion(self) -> str | None: ...
    @property
    def ptr_size(self) -> int | None: ...

class GoSymbols(_LlmReport):
    """Go pclntab symbols: version label, functions, source files, packages."""

    @property
    def version_label(self) -> str | None: ...
    @property
    def function_count(self) -> int: ...
    @property
    def source_file_count(self) -> int: ...
    @property
    def package_count(self) -> int: ...

class GoPclntab(_LlmReport):
    """Go pclntab header: format version, pointer size, func count, image kind."""

    @property
    def version(self) -> str | None: ...
    @property
    def ptr_size(self) -> int | None: ...
    @property
    def func_count(self) -> int | None: ...
    @property
    def image_kind(self) -> str | None: ...

class GarbleReport(_LlmReport):
    """garble assessment: quality, score, seed recoverability, recovered strings."""

    @property
    def quality(self) -> str | None: ...
    @property
    def detection_score(self) -> int | None: ...
    @property
    def seed_recoverable(self) -> bool: ...
    @property
    def seed_hash(self) -> str | None: ...
    @property
    def recovered_string_count(self) -> int: ...

class RubyDetection(_LlmReport):
    """Detected Ruby artifact flavor."""

    @property
    def flavor(self) -> str | None: ...

class RubyAnalysis(_LlmReport):
    """Ruby analysis: flavor plus the backend-specific recovery surface."""

    @property
    def flavor(self) -> str | None: ...
    @property
    def source_path(self) -> str | None: ...
    @property
    def input_len(self) -> int | None: ...

class PhpDetection(_LlmReport):
    """PHP detection: kind, confidence, open-tag offset, __halt_compiler flag."""

    @property
    def kind(self) -> str | None: ...
    @property
    def confidence(self) -> str | None: ...
    @property
    def open_tag_offset(self) -> int | None: ...
    @property
    def has_halt_compiler(self) -> bool: ...

class PhpScan(_LlmReport):
    """PHP obfuscator signature scan: per-family hit counts."""

    @property
    def hit_count(self) -> int: ...
    @property
    def family_count(self) -> int: ...

class PhpDecode(_LlmReport):
    """PHP eval-chain decode: source, per-layer trace, residual-eval flag."""

    @property
    def source(self) -> str | None: ...
    @property
    def layer_count(self) -> int: ...
    @property
    def residual_eval(self) -> bool: ...

class BatchDeobReport(_LlmReport):
    """Batch deobfuscation: transforms, payloads, decrypted stages, IOCs, output."""

    @property
    def output(self) -> str | None: ...
    @property
    def embedded_payload_count(self) -> int: ...
    @property
    def decrypted_stage_count(self) -> int: ...
    @property
    def commands_emulated(self) -> int | None: ...

class PowershellDetection(_LlmReport):
    """PowerShell obfuscator detection: family, confidence, markers, ranking."""

    @property
    def obfuscator(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def marker_count(self) -> int: ...

class PowershellDeobfuscation(_LlmReport):
    """PowerShell deobfuscation: output plus token/string/AST transforms."""

    @property
    def output(self) -> str | None: ...
    @property
    def level(self) -> str | None: ...
    @property
    def transformation_count(self) -> int: ...

class ContainerDetection(_LlmReport):
    """Container detection: recognized flag, kind, zip-family membership."""

    @property
    def detected(self) -> bool: ...
    @property
    def kind(self) -> str | None: ...
    @property
    def is_zip_family(self) -> bool: ...

class ContainerMembers(_LlmReport):
    """Container member listing: format, size, listing mode, per-entry name/size."""

    @property
    def format(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def listing(self) -> ContainerListing | None: ...
    @property
    def entry_count(self) -> int: ...

class PickleDecompilation(_LlmReport):
    """Symbolic pickle decompilation: a Python-assignment source plus the graph."""

    @property
    def source(self) -> str | None: ...

class PickleSafety(_LlmReport):
    """Pickle safety verdict: severity, findings, imports, __reduce__ count."""

    @property
    def severity(self) -> str | None: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def import_count(self) -> int: ...
    @property
    def reduce_count(self) -> int | None: ...

class PickleTrace(_LlmReport):
    """Symbolic pickle VM trace: protocol, memo/stack counts, globals, reduces."""

    @property
    def protocol(self) -> int | None: ...
    @property
    def memo_count(self) -> int | None: ...
    @property
    def max_stack_depth(self) -> int | None: ...
    @property
    def global_ref_count(self) -> int: ...
    @property
    def reduce_count(self) -> int | None: ...

class PicklePolyglot(_LlmReport):
    """Pickle polyglot: pickle membership, co-resident kinds, polyglot verdict."""

    @property
    def is_pickle(self) -> bool: ...
    @property
    def is_polyglot(self) -> bool: ...
    @property
    def kind_count(self) -> int: ...

class PickleMlReport(_LlmReport):
    """ML-model pickle scan: model format, framing, embedded pickle streams."""

    @property
    def format(self) -> str | None: ...
    @property
    def framing(self) -> str | None: ...
    @property
    def embedded_count(self) -> int: ...

class Instruction:
    """A single recovered disassembly instruction with editable fields."""

    def __init__(
        self,
        offset: int,
        mnemonic: str,
        operands: list[str] | None = None,
        bytes: bytes | None = None,
    ) -> None: ...
    offset: int
    mnemonic: str
    operands: list[str]
    bytes: bytes
    branch_target: int | None
    @property
    def flow(self) -> InstructionFlow: ...
    def text(self) -> str: ...

class Symbol:
    """A single recovered symbol with editable address, name, and kind."""

    def __init__(self, address: int, name: str, kind: SymbolKind = "function") -> None: ...
    address: int
    name: str
    kind: SymbolKind

class CodeObject:
    """A mutable, re-serializable recovered code object backed by a .dr envelope.

    Load an existing Disasm- or Raw-rung .dr envelope, edit its instructions, symbols,
    provenance metadata, capabilities, or attached LLM sidecar, then call
    ``to_dr()`` to produce a fresh, integrity-hashed .dr envelope.
    """

    def __init__(self) -> None: ...
    @staticmethod
    def from_dr(dr_bytes: bytes) -> "CodeObject": ...
    @property
    def instructions(self) -> list[Instruction]: ...
    def set_instructions(self, instructions: list[Instruction]) -> None: ...
    def add_instruction(self, instruction: Instruction) -> None: ...
    @property
    def symbols(self) -> list[Symbol]: ...
    def set_symbols(self, symbols: list[Symbol]) -> None: ...
    def add_symbol(self, symbol: Symbol) -> None: ...
    @property
    def instruction_count(self) -> int: ...
    @property
    def symbol_count(self) -> int: ...
    source_hash: str
    produced_by: str
    @property
    def metadata(self) -> dict[str, str]: ...
    def set_metadata(self, key: str, value: str) -> None: ...
    def clear_metadata(self) -> None: ...
    @property
    def capabilities(self) -> list[str]: ...
    def add_capability(self, name: str, major: int) -> None: ...
    @property
    def llm(self) -> dict[str, Any] | None: ...
    def set_llm(self, sidecar: dict[str, Any] | None) -> None: ...
    def to_dr(self) -> bytes: ...

@runtime_checkable
class Pass(Protocol):
    """A custom pass registered via ``register_pass``: a callable mapping the
    incoming ``bytes`` (or a prior pass's return) to any output object."""

    def __call__(self, data: Any) -> Any: ...

@runtime_checkable
class OutputConsumer(Protocol):
    """A custom output consumer registered via ``register_consumer``: a callable
    invoked with a report object and optional keyword context."""

    def __call__(self, result: Any, **context: Any) -> Any: ...

def register_pass(name: str, callable: Pass) -> None: ...
def register_consumer(name: str, callable: OutputConsumer) -> None: ...
def registered_passes() -> list[str]: ...
def registered_consumers() -> list[str]: ...
def unregister(name: str) -> bool: ...
def run_pass(name: str, data: bytes) -> Any: ...
def run_chain(names: list[str], data: bytes) -> Any: ...
def emit(name: str, result: Any, **context: Any) -> Any: ...

def auto(input: bytes, *, max_depth: int = 8, path_hint: str | None = None) -> ChainReport: ...
def decompile(language: str, source: str | bytes) -> CanonicalSource:
    """Recover source for a single language target as a typed ``CanonicalSource``.

    Wired language families and the pass that backs each:
    ``python``/``pyc`` (py-decompile), ``jvm-class``/``class``/``java`` and
    ``kotlin`` (jvm lifter), ``lua`` (register lifter), ``ruby`` (YARV/mruby
    recovery), ``php``/``php-bytecode`` (eval-chain peel / op-array skeleton),
    and ``javascript``/``js``/``typescript``/``ts`` (unminify). Binary-only
    targets (``go``, ``swift``, ``wasm``) have no single recovered-source body;
    call their structural binding (``go_analyze``, ``swift_analyze``,
    ``wasm_analyze``) or ``parse`` instead.
    """
    ...

def disasm(language: str, source: str | bytes) -> str:
    """Render a bytecode/instruction listing as text.

    Wired: ``python``/``pyc``, ``jvm-class``/``class``, ``dex``, ``beam``,
    ``hermes``, ``wasm``, ``ruby``/``yarv``/``mruby`` (YARV disassembly or mruby
    irep summary), and ``php``/``php-bytecode`` (Zend op-array listing). Lua
    recovery is lifter-based; use ``decompile('lua', ...)`` or
    ``parse('lua', ...)`` instead of a raw listing.
    """
    ...

def parse(
    language: str, source: str | bytes
) -> (
    dict[str, Any]
    | GoAnalysis
    | SwiftReport
    | JvmClass
    | RubyAnalysis
    | LuaDecompilation
    | PhpDecode
    | JsUnminify
):
    """Parse a language artifact into a structured record.

    Returns a typed report for the structural-recovery languages: ``go`` ->
    :class:`GoAnalysis`, ``swift``/``objc`` -> :class:`SwiftReport`, ``kotlin``
    -> :class:`JvmClass`, ``ruby`` -> :class:`RubyAnalysis`, ``lua`` ->
    :class:`LuaDecompilation`, ``php`` -> :class:`PhpDecode`, and
    ``javascript``/``js``/``typescript``/``ts`` -> :class:`JsUnminify`. The
    container/bytecode formats (``pyc``, ``jvm-class``, ``dex``, ``wasm``,
    ``hermes``, ``beam``) return a nested ``dict`` because their full parse
    record has no single fixed typed shape.
    """
    ...

def compile(language: str, source: str, *, version: str | None = None) -> bytes: ...

def strings_extract(data: bytes, *, min_len: int = 4, decode: bool = True) -> StringsReport: ...
def ioc_extract(data: bytes) -> IocReport: ...
def behavior_analyze(data: bytes) -> BehaviorReport: ...
def identify(data: bytes) -> IdentifyReport: ...
def secret_scan(data: bytes, *, redact: bool = False) -> SecretScanReport: ...
def capabilities(binary_bytes: bytes) -> Capabilities: ...
def extract(data: bytes, out_dir: str) -> ExtractionResult: ...
def extract_recursive(
    data: bytes, *, source_label: str = "inline", max_depth: int = 8
) -> OverlayReport: ...
def yara_parse(ruleset_source: str) -> YaraReport: ...
def yara_generate(data: bytes, *, name: str | None = None) -> YaraReport: ...

def native_symbols(data: bytes) -> SymbolsReport: ...
def native_disasm(data: bytes) -> DisasmPayload: ...
def native_callgraph(data: bytes) -> CallGraph: ...
def native_imports_dot(data: bytes) -> str: ...
def native_entropy(data: bytes) -> EntropyReport: ...
def native_sbom(data: bytes) -> SbomReport: ...
def native_fingerprint(data: bytes, *, flirt: bytes | None = None) -> FingerprintReport: ...
def native_signatures(data: bytes, *, flirt: bytes | None = None) -> SignatureReport: ...
def native_sigmaker(data: bytes, at: int) -> SigmakerReport: ...
def native_diff(a: bytes, b: bytes) -> DiffReport: ...
def native_patch(
    data: bytes,
    *,
    at: int,
    replacement: bytes | None = None,
    nop_start: int | None = None,
    nop_end: int | None = None,
) -> tuple[bytes, PatchReport]: ...

def query_functions(dr_bytes: bytes) -> FunctionList: ...
def query_calls_to(dr_bytes: bytes, target: str) -> QueryReport: ...
def query_xrefs_to(dr_bytes: bytes, symbol: str) -> QueryReport: ...
def query_string_decoders(dr_bytes: bytes) -> QueryReport: ...
def query_complexity_over(dr_bytes: bytes, threshold: int) -> QueryReport: ...
def query_capability_sites(dr_bytes: bytes, capability: str) -> QueryReport: ...
def query_call_graph(dr_bytes: bytes) -> CallGraph: ...

def envelope_create(
    payload: bytes,
    *,
    source_label: str = "inline",
    produced_by: str | None = None,
    detected_format: str | None = None,
) -> bytes: ...
def envelope_verify(envelope_bytes: bytes) -> EnvelopeReport: ...

def agents_md(result: Any) -> str: ...
def skill_md(result: Any) -> str: ...
def provenance(result: Any) -> Provenance: ...

def py_decompile(
    pyc_bytes: bytes, *, roundtrip: bool = False, pack: Pack | None = None
) -> PyDecompileReport: ...
def py_disasm(pyc_bytes: bytes, *, pack: Pack | None = None) -> PyDisasmReport: ...
def py_deob(source: str, *, cleanup: bool = True, pack: Pack | None = None) -> PyDeobReport: ...
def py_deob_detect(source: str) -> PyDeobDetection: ...
def py_deob_list_passes() -> list[ObfuscatorPass]: ...
def py_deob_detect_pass(source: str, pass_id: str) -> PyDeobDetection: ...
def pyarmor_detect(source: str, *, pack: Pack | None = None) -> PyarmorDetection: ...
def pyarmor_unpack(wrapper_bytes: bytes, *, pack: Pack | None = None) -> PyarmorUnpack: ...
def pyarmor_classify(source: str, payload: bytes) -> PyarmorClassification: ...
def pyinstaller_extract(image_bytes: bytes) -> PyInstallerArchive: ...
def pyinstaller_entry_bytes(image_bytes: bytes, entry_name: str) -> bytes: ...
def nuitka_detect(image_bytes: bytes) -> NuitkaDetection: ...
def nuitka_extract(image_bytes: bytes) -> NuitkaExtraction: ...
def hermes_disasm(bundle_bytes: bytes) -> HermesDisassembly: ...
def hermes_lift(bundle_bytes: bytes) -> HermesLift: ...
def hermes_info(bundle_bytes: bytes) -> HermesInfo: ...
def macho_dump(macho_bytes: bytes) -> MachoReport: ...
def swift_analyze(macho_bytes: bytes) -> SwiftReport: ...
def jvm_parse_class(class_bytes: bytes) -> JvmClass: ...
def jvm_parse_dex(dex_bytes: bytes) -> DexFileReport: ...
def jvm_decompile_class(class_bytes: bytes) -> JvmDecompiledClass: ...
def jvm_decompile_dex(dex_bytes: bytes) -> JvmDecompiledDex: ...
def jvm_detect(class_bytes: bytes) -> DetectionList: ...
def jvm_backends() -> JvmBackends: ...
def apk_resources(apk_bytes: bytes) -> ApkResources: ...
def dotnet_parse_pe(pe_bytes: bytes) -> DotnetPe: ...
def dotnet_parse_metadata(pe_bytes: bytes) -> DotnetMetadata: ...
def dotnet_detect(pe_bytes: bytes) -> DotnetDetection: ...
def dotnet_analyze(pe_bytes: bytes) -> DotnetAnalysis: ...
def dotnet_decompile(pe_bytes: bytes) -> DotnetDecompilation: ...
def dotnet_recover_decoders(pe_bytes: bytes) -> DotnetDecoders: ...
def dotnet_backends() -> BackendList: ...
def wasm_analyze(wasm_bytes: bytes) -> WasmAnalysis: ...
def wasm_detect(wasm_bytes: bytes) -> WasmDetection: ...
def js_detect(js_source: str) -> JsDetection: ...
def js_unminify(js_source: str) -> JsUnminify: ...
def js_unbundle(js_source: str, *, bundler: str | None = None) -> JsUnbundle: ...
def native_format(binary_bytes: bytes) -> NativeFormat: ...
def native_detect(binary_bytes: bytes) -> DetectionList: ...
def native_probe_backends() -> BackendList: ...
def native_deobfuscate(
    code: bytes, *, bits: int = 64, base: int = 0, entry: int = 0
) -> NativeDeobfuscation: ...
def lua_detect(bytecode: bytes) -> LuaDetection: ...
def lua_decompile(bytecode: bytes) -> LuaDecompilation: ...
def lua_deobfuscate(
    source: str, *, authorize: bool = False, strict: bool = False
) -> LuaDeobfuscation: ...
def go_analyze(binary_bytes: bytes) -> GoAnalysis: ...
def go_symbols(binary_bytes: bytes) -> GoSymbols: ...
def go_pclntab(binary_bytes: bytes) -> GoPclntab: ...
def go_garble(binary_bytes: bytes) -> GarbleReport: ...
def ruby_detect(ruby_bytes: bytes, *, source_path: str | None = None) -> RubyDetection: ...
def ruby_decompile(ruby_bytes: bytes, *, source_path: str | None = None) -> RubyAnalysis: ...
def php_detect(php_bytes: bytes) -> PhpDetection: ...
def php_scan(php_bytes: bytes) -> PhpScan: ...
def php_decode(php_bytes: bytes, *, max_depth: int | None = None) -> PhpDecode: ...
def batch_deobfuscate(script: str, *, args: list[str] | None = None) -> BatchDeobReport: ...
def powershell_detect(script: str) -> PowershellDetection: ...
def powershell_deobfuscate(script: str) -> PowershellDeobfuscation: ...
def container_detect(container_bytes: bytes) -> ContainerDetection: ...
def container_members(container_bytes: bytes) -> ContainerMembers: ...
def pickle_disasm(pickle_bytes: bytes) -> str: ...
def pickle_decompile(pickle_bytes: bytes) -> PickleDecompilation: ...
def pickle_safety(pickle_bytes: bytes) -> PickleSafety: ...
def pickle_trace(pickle_bytes: bytes) -> PickleTrace: ...
def pickle_polyglot(file_bytes: bytes) -> PicklePolyglot: ...
def pickle_ml_detect(file_bytes: bytes) -> PickleMlReport: ...
