use crate::error::{Error, Result};
use crate::obfuscator::string_decode::eval_arith_expr;
use crate::obfuscator::vm_devirt::{devirt_to_peel, extract_embedded_payload};
use crate::obfuscator::{DeobfOptions, LuaObfuscatorKind, ObfuscatorDetection, PeelResult};

const HEADER_MARKERS: &[&[u8]] = &[
    b"This file was generated by Luraph",
    b"obfuscated using Luraph",
    b"lura.ph",
    b"Luraph",
];

const MACRO_MARKERS: &[&[u8]] = &[
    b"LPH_ENCFUNC",
    b"LPH_NO_VIRTUALIZE",
    b"LPH_JIT",
    b"LPH_STRING",
    b"LPH_ENCSTR",
    b"LPH_SKIP",
];
const LURAPH_SCAN_LIMIT: usize = 8 << 20;
const SCRIPT_KEY_NAMES: &[&str] = &[
    "script_key",
    "scriptKey",
    "SCRIPT_KEY",
    "LURAPH_KEY",
    "LURAPH_SCRIPT_KEY",
    "lph_key",
    "LPH_KEY",
];
const BOOTSTRAP_TABLE_NAMES: &[&str] = &["e", "u", "Y", "L", "H"];
const MIN_BOOTSTRAP_TABLE_VALUES: usize = 8;
const MAX_BOOTSTRAP_TABLE_VALUES: usize = 4096;
const MAX_LURAPH_EXPR_LEN: usize = 4096;

#[derive(Debug, Clone, PartialEq, Eq)]
struct LuraphBootstrapFacts {
    script_key: Option<ScriptKeyLiteral>,
    tables: Vec<LuraphStaticTable>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ScriptKeyLiteral {
    Number(u32),
    Bytes(usize),
}

impl ScriptKeyLiteral {
    fn label(&self) -> String {
        match self {
            Self::Number(value) => format!("numeric 0x{value:x}"),
            Self::Bytes(len) => format!("{len} byte string"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct LuraphStaticTable {
    name: &'static str,
    values: usize,
}

#[must_use]
pub fn detect(src: &[u8]) -> Option<ObfuscatorDetection> {
    let mut markers: Vec<String> = Vec::new();
    let mut header_hit: bool = false;
    for m in HEADER_MARKERS {
        if disrobe_core::byte_search::contains(src, m) {
            markers.push(String::from_utf8_lossy(m).into_owned());
            header_hit = true;
        }
    }
    let mut macro_hits: usize = 0;
    for m in MACRO_MARKERS {
        if disrobe_core::byte_search::contains(src, m) {
            markers.push(String::from_utf8_lossy(m).into_owned());
            macro_hits += 1;
        }
    }

    if markers.is_empty() {
        return None;
    }

    let confidence: u8 = if header_hit {
        96
    } else if macro_hits >= 2 {
        88
    } else {
        72
    };

    Some(ObfuscatorDetection {
        kind: LuaObfuscatorKind::Luraph,
        variant: Some("custom-encrypted-bytecode-vm".to_owned()),
        confidence,
        markers,
    })
}

pub fn peel(src: &[u8], _opts: &DeobfOptions) -> Result<PeelResult> {
    if detect(src).is_none() {
        return Err(Error::NoObfuscatorSignature("Luraph"));
    }
    let text: std::borrow::Cow<'_, str> = String::from_utf8_lossy(src);
    let embedded_payload: Option<Vec<u8>> = extract_embedded_payload(&text);
    if let Some(payload) = embedded_payload {
        return devirt_to_peel(src, &text, &payload, "luraph");
    }
    Ok(PeelResult::passthrough(
        src,
        static_refutation_markers(&text),
    ))
}

fn static_refutation_markers(text: &str) -> Vec<String> {
    let facts: LuraphBootstrapFacts = inspect_static_bootstrap(text);
    let mut markers: Vec<String> = vec![
        "luraph: static refutation attempted VMPAYLOAD hex, VMPAYLOAD_B64/VMPAYLOAD64, base64-tagged markers, and Lua quoted/long-string VM payload carriers".to_owned(),
    ];
    if has_lph_blob_marker(text) {
        markers.push(
            "luraph: refutation found an LPH bytecode-shaped Lua string, but it does not decode to the canonical VM payload format and remains encrypted or framed".to_owned(),
        );
    }
    if has_runtime_key_expression(text) {
        markers.push(
            "luraph: refutation found runtime key material (time/random/environment API), not a literal script key".to_owned(),
        );
    } else if let Some(script_key) = facts.script_key.as_ref() {
        markers.push(format!(
            "luraph: refutation found a literal script key ({})",
            script_key.label()
        ));
    } else {
        markers.push("luraph: refutation found no literal script key, so this routes to the runtime-key wall: the script key is derived at runtime (remote/Escrow) and is not present in this static input".to_owned());
    }
    if facts.tables.is_empty() {
        markers.push(
            "luraph: refutation found no static opcode permutation table beside the detected bootstrap".to_owned(),
        );
    } else {
        let table_summary: String = facts
            .tables
            .iter()
            .map(|table: &LuraphStaticTable| format!("{}={}", table.name, table.values))
            .collect::<Vec<String>>()
            .join(",");
        markers.push(format!(
            "luraph: refutation found static bootstrap table candidates ({table_summary})"
        ));
    }
    let wall: &str = if facts.script_key.is_some() || !facts.tables.is_empty() {
        "luraph: WALL - static bootstrap material is present, but no verified Luraph opcode permutation/decryptor mapping has been recovered yet"
    } else {
        "luraph: WALL - this artifact lacks the static bytecode key/permutation needed for recovery; runtime execution of the protected VM would be required"
    };
    markers.push(wall.to_owned());
    markers
}

fn inspect_static_bootstrap(text: &str) -> LuraphBootstrapFacts {
    let script_key: Option<ScriptKeyLiteral> = SCRIPT_KEY_NAMES
        .iter()
        .find_map(|name: &&str| find_lua_assignment_value(text, name))
        .and_then(|start: usize| parse_script_key_literal(text.as_bytes(), start));
    let mut tables: Vec<LuraphStaticTable> = Vec::new();
    for name in BOOTSTRAP_TABLE_NAMES {
        let Some(value_start): Option<usize> = find_lua_assignment_value(text, name) else {
            continue;
        };
        let Some(values): Option<usize> = parse_numeric_table_len(text.as_bytes(), value_start)
        else {
            continue;
        };
        if values >= MIN_BOOTSTRAP_TABLE_VALUES {
            tables.push(LuraphStaticTable { name, values });
        }
    }
    LuraphBootstrapFacts { script_key, tables }
}

#[must_use]
fn has_runtime_key_expression(text: &str) -> bool {
    [
        "os.time",
        "tick(",
        "time()",
        "math.random",
        "Random.new",
        "game:GetService",
        "HttpGet",
        "GetAsync",
        "os.clock",
    ]
    .iter()
    .any(|needle: &&str| text.contains(*needle))
}

#[must_use]
fn has_lph_blob_marker(text: &str) -> bool {
    text.contains("\\27\\76\\80\\72")
        || text.contains("\\x1bLPH")
        || text.contains("\u{1b}LPH")
        || text.contains("LPH!")
}

#[must_use]
fn find_lua_assignment_value(text: &str, name: &str) -> Option<usize> {
    let bytes: &[u8] = text.as_bytes();
    let limit: usize = bytes.len().min(LURAPH_SCAN_LIMIT);
    let mut search_start: usize = 0;
    while search_start < limit {
        let haystack: &str = text.get(search_start..limit)?;
        let found: usize = haystack.find(name)? + search_start;
        let before: bool = found
            .checked_sub(1)
            .and_then(|idx: usize| bytes.get(idx).copied())
            .is_some_and(is_lua_ident_byte);
        let after: bool = bytes
            .get(found + name.len())
            .copied()
            .is_some_and(is_lua_ident_byte);
        if !before && !after {
            let mut pos: usize = found + name.len();
            while pos < limit && bytes[pos].is_ascii_whitespace() {
                pos += 1;
            }
            if bytes.get(pos).copied() == Some(b'=') {
                pos += 1;
                while pos < limit && bytes[pos].is_ascii_whitespace() {
                    pos += 1;
                }
                return Some(pos);
            }
        }
        search_start = found + name.len();
    }
    None
}

#[inline]
#[must_use]
fn is_lua_ident_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

fn parse_script_key_literal(bytes: &[u8], start: usize) -> Option<ScriptKeyLiteral> {
    let pos: usize = skip_lua_ws(bytes, start);
    match bytes.get(pos).copied()? {
        b'\'' | b'"' => decode_lua_string_len(bytes, pos).map(ScriptKeyLiteral::Bytes),
        _ => {
            let expr: &str = expr_until_delimiter(bytes, pos)?;
            let value: i64 = eval_luraph_int_expr(expr)?;
            u32::try_from(value).ok().map(ScriptKeyLiteral::Number)
        }
    }
}

fn parse_numeric_table_len(bytes: &[u8], start: usize) -> Option<usize> {
    let mut pos: usize = skip_lua_ws(bytes, start);
    if bytes.get(pos).copied()? != b'{' {
        return None;
    }
    pos += 1;
    let mut count: usize = 0;
    loop {
        pos = skip_lua_table_sep(bytes, pos);
        match bytes.get(pos).copied()? {
            b'}' => return Some(count),
            _ => {
                let expr: &str = expr_until_delimiter(bytes, pos)?;
                let value: i64 = eval_luraph_int_expr(expr)?;
                if !(0..=255).contains(&value) {
                    return None;
                }
                count += 1;
                if count > MAX_BOOTSTRAP_TABLE_VALUES {
                    return None;
                }
                pos = pos.checked_add(expr.len())?;
            }
        }
    }
}

fn expr_until_delimiter(bytes: &[u8], start: usize) -> Option<&str> {
    let mut pos: usize = start;
    while pos < bytes.len() && !matches!(bytes[pos], b',' | b';' | b'}' | b'\n' | b'\r') {
        pos += 1;
    }
    if pos == start {
        return None;
    }
    std::str::from_utf8(&bytes[start..pos]).ok().map(str::trim)
}

fn eval_luraph_int_expr(expr: &str) -> Option<i64> {
    eval_arith_expr(expr).or_else(|| {
        let rewritten: String = rewrite_hex_literals(expr)?;
        eval_arith_expr(&rewritten)
    })
}

fn rewrite_hex_literals(expr: &str) -> Option<String> {
    if expr.len() > MAX_LURAPH_EXPR_LEN {
        return None;
    }
    let bytes: &[u8] = expr.as_bytes();
    let mut out: String = String::with_capacity(expr.len());
    let mut pos: usize = 0;
    while pos < bytes.len() {
        if bytes.get(pos).copied() == Some(b'0')
            && matches!(bytes.get(pos + 1).copied(), Some(b'x' | b'X'))
        {
            let digits_start: usize = pos + 2;
            let mut digits_end: usize = digits_start;
            while digits_end < bytes.len() && bytes[digits_end].is_ascii_hexdigit() {
                digits_end += 1;
            }
            if digits_end == digits_start {
                return None;
            }
            let hex: &str = std::str::from_utf8(&bytes[digits_start..digits_end]).ok()?;
            let value: u64 = u64::from_str_radix(hex, 16).ok()?;
            out.push_str(&value.to_string());
            pos = digits_end;
        } else {
            out.push(char::from(bytes[pos]));
            pos += 1;
        }
    }
    Some(out)
}

fn skip_lua_ws(bytes: &[u8], mut pos: usize) -> usize {
    while pos < bytes.len() && bytes[pos].is_ascii_whitespace() {
        pos += 1;
    }
    pos
}

fn skip_lua_table_sep(bytes: &[u8], mut pos: usize) -> usize {
    while pos < bytes.len()
        && (bytes[pos].is_ascii_whitespace() || bytes[pos] == b',' || bytes[pos] == b';')
    {
        pos += 1;
    }
    pos
}

fn decode_lua_string_len(bytes: &[u8], start: usize) -> Option<usize> {
    let quote: u8 = *bytes.get(start)?;
    if quote != b'\'' && quote != b'"' {
        return None;
    }
    let mut len: usize = 0;
    let mut pos: usize = start + 1;
    while pos < bytes.len() {
        let byte: u8 = bytes[pos];
        if byte == quote {
            return Some(len);
        }
        if byte == b'\\' {
            pos += 1;
            let escaped: u8 = *bytes.get(pos)?;
            if escaped.is_ascii_digit() {
                let mut value: u16 = 0;
                let mut digits: usize = 0;
                while digits < 3 && pos < bytes.len() && bytes[pos].is_ascii_digit() {
                    value = value
                        .checked_mul(10)?
                        .checked_add(u16::from(bytes[pos] - b'0'))?;
                    pos += 1;
                    digits += 1;
                }
                if value > u16::from(u8::MAX) {
                    return None;
                }
                len += 1;
                continue;
            }
            if escaped == b'x' {
                hex_nibble(*bytes.get(pos + 1)?)?;
                hex_nibble(*bytes.get(pos + 2)?)?;
                pos += 3;
                len += 1;
                continue;
            }
        }
        len += 1;
        pos += 1;
    }
    None
}

const fn hex_nibble(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}
