use std::collections::BTreeMap;

use disrobe_core::codec::{
    CustomBase64Alphabet, CustomBase64GroupPolicy, CustomBase64Input, decode_custom_base64,
};

use crate::error::{Error, Result};
use crate::obfuscator::string_decode::{
    apply_segment_reversals, decode_base85_variant, discover_base64_alphabets,
    discover_base85_alphabets, extract_named_table_body, first_wrapped_table_name,
    parse_constarray_rotation, parse_lua_string_literals_bounded,
};
use crate::obfuscator::{DeobfOptions, LuaObfuscatorKind, ObfuscatorDetection, PeelResult};

const COMMENT_MARKERS: &[&[u8]] = &[
    b"-- prometheus",
    b"Prometheus.Pipeline",
    b"-- Generated by Prometheus",
    b"PROMETHEUS_VERSION",
];

const STRUCT_WRAP_PREFIX: &[u8] = b"return(function(...)local ";
const STRUCT_IPAIRS_SUFFIX: &[u8] = b" in ipairs(";
const MAX_CONSTANT_ARRAY_ENTRIES: usize = 1 << 14;
const MAX_CONSTANT_ARRAY_DECODED_BYTES: usize = 4 << 20;
const _: () = assert!(
    MAX_CONSTANT_ARRAY_DECODED_BYTES < crate::obfuscator::prometheus_vm_ast::MAX_SOURCE_BYTES
);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ConstantArrayBudget {
    max_source_bytes: usize,
    max_entries: usize,
    max_decoded_bytes: usize,
}

const CONSTANT_ARRAY_BUDGET: ConstantArrayBudget = ConstantArrayBudget {
    max_source_bytes: crate::obfuscator::prometheus_vm_ast::MAX_SOURCE_BYTES,
    max_entries: MAX_CONSTANT_ARRAY_ENTRIES,
    max_decoded_bytes: MAX_CONSTANT_ARRAY_DECODED_BYTES,
};

pub fn detect(src: &[u8]) -> Option<ObfuscatorDetection> {
    let mut found: Vec<String> = Vec::new();
    let mut variant: Option<&'static str> = None;
    let mut confidence: u8 = 0;

    for m in COMMENT_MARKERS {
        if disrobe_core::byte_search::contains(src, m) {
            found.push(String::from_utf8_lossy(m).into_owned());
        }
    }
    if !found.is_empty() {
        variant = Some("CommentMarker");
        confidence = 95;
    }

    if matches_constarray_wrap(src) {
        found.push("ConstantArrayWrap".to_owned());
        variant = Some("ConstantArray+WrapInFunction");
        confidence = confidence.max(85);
    }

    if matches_minify_shape(src) {
        found.push("MangledShuffledMinify".to_owned());
        if variant.is_none() {
            variant = Some("Minify(MangledShuffled)");
        }
        confidence = confidence.max(60);
    }

    if matches_vmify_container_shape(src) {
        found.push("VmifyContainerDispatch".to_owned());
        if variant.is_none() {
            variant = Some("Vmify(bareContainer)");
        }
        confidence = confidence.max(80);
    }

    if found.is_empty() {
        return None;
    }
    Some(ObfuscatorDetection {
        kind: LuaObfuscatorKind::Prometheus,
        variant: variant.map(str::to_owned),
        confidence,
        markers: found,
    })
}

pub fn peel(src: &[u8], opts: &DeobfOptions) -> Result<PeelResult> {
    peel_with_budget(src, opts, CONSTANT_ARRAY_BUDGET)
}

fn peel_with_budget(
    src: &[u8],
    _opts: &DeobfOptions,
    budget: ConstantArrayBudget,
) -> Result<PeelResult> {
    if detect(src).is_none() {
        return Err(Error::NoObfuscatorSignature("Prometheus"));
    }
    if src.len() > budget.max_source_bytes {
        return Err(limit_exceeded(
            "Prometheus source bytes",
            src.len(),
            budget.max_source_bytes,
        ));
    }
    let text: std::borrow::Cow<'_, str> = String::from_utf8_lossy(src);
    let (mut result, string_pool_binding, resolved_pool_entries): (
        PeelResult,
        Option<String>,
        Vec<bool>,
    ) = match decode_string_pool(&text, budget)? {
        Some(decoded) => (
            decoded.result,
            Some(decoded.binding),
            decoded.resolved_entries,
        ),
        None => (
            PeelResult::passthrough(
                src,
                vec![
                    "prometheus: no static encoded constant-array present (minify-only shape leaves source strings in cleartext)".to_owned(),
                ],
            ),
            None,
            Vec::new(),
        ),
    };
    apply_vmlift(
        &text,
        &resolved_pool_entries,
        &mut result,
        string_pool_binding.as_deref(),
    );
    Ok(result)
}

const MAX_NESTED_VMIFY_PASSES: usize = 4;

fn apply_vmlift(
    text: &str,
    resolved_pool_entries: &[bool],
    result: &mut PeelResult,
    string_pool_binding: Option<&str>,
) {
    use crate::obfuscator::prometheus_vmlift::{
        analyze_dispatch, count_arithmetic_operators, fold_numeric_expressions,
    };

    let before_ops: usize = count_arithmetic_operators(text);
    let folded: String = fold_numeric_expressions(text);
    let after_ops: usize = count_arithmetic_operators(&folded);
    let folded_count: usize = before_ops.saturating_sub(after_ops);

    if folded_count > 0 {
        result
            .passes_run
            .push("prometheus-numbers-to-expressions-fold".to_owned());
        result.residual_markers.push(format!(
            "prometheus: folded {folded_count} NumbersToExpressions arithmetic wrappers back to numeric literals ({before_ops} -> {after_ops} arithmetic operators), runtime-equivalent under a real Lua interpreter"
        ));
    }

    let recovered_strings: Vec<String> = core::mem::take(&mut result.recovered_strings);
    let vmify_summary: Option<String> = apply_vmify_devirt(
        &folded,
        &recovered_strings,
        resolved_pool_entries,
        string_pool_binding,
        result,
    );
    result.recovered_strings = recovered_strings;
    if let Some(vmify_summary) = vmify_summary {
        result.residual_markers.push(vmify_summary);
        return;
    }

    let dispatch_note: Option<String> = analyze_dispatch(&folded).map(|report| {
        result
            .passes_run
            .push("prometheus-vmify-dispatch-cfg-recovery".to_owned());
        format!(
            "prometheus: Vmify dispatch recovered as a flattened state machine over '{}' with {} state comparisons, {} distinct leaf states, {} successor edges ({} conditional branches); control-flow graph is statically reconstructed but the per-block operations are not yet re-emitted as structured Lua",
            report.state_variable,
            report.comparison_count,
            report.block_count(),
            report.successor_edges,
            report.conditional_blocks,
        )
    });

    if folded_count > 0 {
        if string_pool_binding.is_some() {
            result.residual_markers.push(
                "prometheus: emitted artifact is the decoded constant-array string pool; the NumbersToExpressions fold above is a separately verified runtime-equivalent transform over the VM wrapper, not re-applied to the emitted pool".to_owned(),
            );
        } else {
            result.deobfuscated = folded.into_bytes();
        }
    }
    result.residual_markers.push(dispatch_note.unwrap_or_else(|| {
        "prometheus: the Vmify opcode/control-flow layer remains as an arithmetic-dispatch interpreter and is not lifted back to structured Lua by this pass".to_owned()
    }));
}

fn apply_vmify_devirt(
    folded: &str,
    recovered_strings: &[String],
    resolved_pool_entries: &[bool],
    string_pool_binding: Option<&str>,
    result: &mut PeelResult,
) -> Option<String> {
    use crate::obfuscator::prometheus_vm_cfg::{VmifyRecovery, recover_with_string_pool};

    let mut current: String = folded.to_owned();
    let mut passes: usize = 0;
    let mut last: Option<VmifyRecovery> = None;
    let mut refusal: Option<String> = None;
    while passes < MAX_NESTED_VMIFY_PASSES {
        match recover_with_string_pool(
            &current,
            recovered_strings,
            resolved_pool_entries,
            string_pool_binding,
        ) {
            Ok(Some(recovery)) => {
                current.clone_from(&recovery.source);
                passes += 1;
                last = Some(recovery);
            }
            Ok(None) => break,
            Err(err) => {
                refusal = Some(err.to_string());
                break;
            }
        }
    }
    let Some(recovery): Option<VmifyRecovery> = last else {
        if let Some(reason) = refusal {
            result.residual_markers.push(format!(
                "prometheus: a Vmify container was found but recovery was refused rather than emitted partly wrong: {reason}"
            ));
        }
        return None;
    };
    if let Some(reason) = &refusal {
        result.residual_markers.push(format!(
            "prometheus: recovered {passes} Vmify layer(s), then a further recovery pass was refused: {reason}"
        ));
    }
    result.deobfuscated = current.into_bytes();
    result
        .passes_run
        .push("prometheus-vmify-container-devirt".to_owned());
    if passes > 1 {
        result
            .passes_run
            .push(format!("prometheus-vmify-nested-devirt-{passes}-layers"));
    }
    result.fully_recovered = recovery.fully_recovered && refusal.is_none();
    let mut summary: String = format!(
        "prometheus: Vmify container devirtualized over {passes} layer(s), handlers {}/{} ({}%), functions {}/{}",
        recovery.handlers_recovered,
        recovery.handlers_total,
        ratio_pct(recovery.handlers_recovered, recovery.handlers_total),
        recovery.functions_recovered,
        recovery.functions_total,
    );
    if recovery.unreached_structural_leaves > 0 {
        summary.push_str(&format!(
            "; {} dispatch-tree leaf(ves) with real statements were never reached from a discovered function entry (excluded from the handler count above; likely dead or decoy code)",
            recovery.unreached_structural_leaves
        ));
    }
    Some(summary)
}

#[inline]
fn ratio_pct(num: usize, den: usize) -> u8 {
    if den == 0 {
        return 100;
    }
    let pct: usize = num.saturating_mul(100) / den;
    u8::try_from(pct.min(100)).unwrap_or(100)
}

struct DecodedStringPool {
    result: PeelResult,
    binding: String,
    resolved_entries: Vec<bool>,
}

fn decode_string_pool(
    text: &str,
    budget: ConstantArrayBudget,
) -> Result<Option<DecodedStringPool>> {
    let Some(pool_name): Option<char> = first_wrapped_table_name(text) else {
        return Ok(None);
    };
    let Some(pool_body): Option<&str> = extract_named_table_body(text, &pool_name.to_string())
    else {
        return Ok(None);
    };
    let encoded: Vec<String> = parse_lua_string_literals_bounded(pool_body, budget.max_entries)
        .map_err(|exceeded| {
            limit_exceeded(
                "Prometheus constant-array entries",
                exceeded.count,
                exceeded.limit,
            )
        })?;
    if encoded.is_empty() {
        return Ok(None);
    }
    let base64_maps: Vec<(char, BTreeMap<char, u8>)> = discover_base64_alphabets(text);
    let base64: Vec<(char, CustomBase64Alphabet<'_>)> = base64_maps
        .iter()
        .filter_map(|(name, map): &(char, BTreeMap<char, u8>)| {
            CustomBase64Alphabet::from_character_map(map)
                .map(|alphabet: CustomBase64Alphabet<'_>| (*name, alphabet))
        })
        .collect();
    let base85: Vec<(char, BTreeMap<char, u8>)> = discover_base85_alphabets(text);
    if base64.is_empty() && base85.is_empty() {
        return Ok(None);
    }

    let mut recovered: Vec<String> = Vec::with_capacity(encoded.len());
    let mut resolved_entries: Vec<bool> = Vec::with_capacity(encoded.len());
    let mut decoded_b64: usize = 0;
    let mut decoded_b85: usize = 0;
    let mut decoded_bytes: usize = 0;
    let mut residual_count: usize = 0;
    for enc in &encoded {
        match decode_pool_entry(enc, &base64, &base85) {
            Some((plain, Encoding::Base64)) => {
                decoded_bytes = add_decoded_bytes(decoded_bytes, plain.len(), budget)?;
                decoded_b64 += 1;
                recovered.push(plain);
                resolved_entries.push(true);
            }
            Some((plain, Encoding::Base85)) => {
                decoded_bytes = add_decoded_bytes(decoded_bytes, plain.len(), budget)?;
                decoded_b85 += 1;
                recovered.push(plain);
                resolved_entries.push(true);
            }
            None => {
                residual_count += 1;
                recovered.push(enc.clone());
                resolved_entries.push(false);
            }
        }
    }
    let decoded_count: usize = decoded_b64 + decoded_b85;
    if decoded_count == 0 {
        return Ok(None);
    }

    if let Some(pairs) = parse_constarray_rotation(text) {
        apply_segment_reversals(&mut recovered, &pairs);
        apply_segment_reversals(&mut resolved_entries, &pairs);
    }

    let mut out: String = String::new();
    out.push_str("local PROMETHEUS_STRINGS = {\n");
    for s in &recovered {
        out.push_str("  ");
        out.push_str(&quote(s));
        out.push_str(",\n");
    }
    out.push_str("}\n");

    let mut passes_run: Vec<String> =
        vec!["prometheus-constant-array-alphabet-discover".to_owned()];
    if decoded_b64 > 0 {
        passes_run.push("prometheus-base64-variant-string-decode".to_owned());
    }
    if decoded_b85 > 0 {
        passes_run.push("prometheus-base85-variant-string-decode".to_owned());
    }
    if parse_constarray_rotation(text).is_some() {
        passes_run.push("prometheus-constant-array-rotation-undo".to_owned());
    }

    let mut residual_markers: Vec<String> = vec![format!(
        "prometheus: {decoded_count}/{} constant-array entries decoded ({decoded_b64} base64, {decoded_b85} base85) from the static per-script alphabet table(s)",
        encoded.len()
    )];
    if residual_count > 0 {
        residual_markers.push(format!(
            "prometheus: {residual_count} constant-array entries are the original program's binary string data (non-printable bytes), kept in their raw encoded form"
        ));
    }
    Ok(Some(DecodedStringPool {
        result: PeelResult {
            deobfuscated: out.into_bytes(),
            passes_run,
            residual_markers,
            recovered_strings: recovered,
            fully_recovered: false,
        },
        binding: pool_name.to_string(),
        resolved_entries,
    }))
}

fn add_decoded_bytes(
    decoded_bytes: usize,
    entry_bytes: usize,
    budget: ConstantArrayBudget,
) -> Result<usize> {
    let next: usize = decoded_bytes.checked_add(entry_bytes).ok_or_else(|| {
        limit_exceeded(
            "Prometheus constant-array decoded bytes",
            usize::MAX,
            budget.max_decoded_bytes,
        )
    })?;
    if next > budget.max_decoded_bytes {
        return Err(limit_exceeded(
            "Prometheus constant-array decoded bytes",
            next,
            budget.max_decoded_bytes,
        ));
    }
    Ok(next)
}

fn limit_exceeded(section: &'static str, count: usize, limit: usize) -> Error {
    let count: u64 = count as u64;
    Error::LimitExceeded {
        section,
        count,
        limit,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Encoding {
    Base64,
    Base85,
}

fn decode_pool_entry(
    enc: &str,
    base64: &[(char, CustomBase64Alphabet<'_>)],
    base85: &[(char, BTreeMap<char, u8>)],
) -> Option<(String, Encoding)> {
    let mut chars: core::str::Chars<'_> = enc.chars();
    let _type_tag: char = chars.next()?;
    let body: &str = chars.as_str();
    if body.is_empty() {
        return None;
    }
    for (_name, alphabet) in base64 {
        let Some(bytes): Option<Vec<u8>> = decode_custom_base64(
            CustomBase64Input::Text(body),
            alphabet,
            CustomBase64GroupPolicy::DropPartial,
        ) else {
            continue;
        };
        if !bytes.is_empty() && is_plausible_plaintext(&bytes) {
            return Some((
                String::from_utf8_lossy(&bytes).into_owned(),
                Encoding::Base64,
            ));
        }
    }
    for (_name, alpha) in base85 {
        let Some(bytes): Option<Vec<u8>> = decode_base85_variant(body, alpha) else {
            continue;
        };
        if !bytes.is_empty() && is_plausible_plaintext(&bytes) {
            return Some((
                String::from_utf8_lossy(&bytes).into_owned(),
                Encoding::Base85,
            ));
        }
    }
    None
}

#[must_use]
fn is_plausible_plaintext(bytes: &[u8]) -> bool {
    let printable: usize = bytes
        .iter()
        .filter(|b: &&u8| (0x20..0x7F).contains(*b) || matches!(**b, b'\n' | b'\t' | b'\r'))
        .count();
    printable == bytes.len()
}

#[must_use]
fn quote(s: &str) -> String {
    let mut out: String = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\{}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn matches_constarray_wrap(src: &[u8]) -> bool {
    if !src.starts_with(STRUCT_WRAP_PREFIX) {
        return false;
    }
    let after_prefix: &[u8] = &src[STRUCT_WRAP_PREFIX.len()..];
    let Some(eq_pos): Option<usize> = after_prefix.iter().take(64).position(|b: &u8| *b == b'=')
    else {
        return false;
    };
    if after_prefix.get(eq_pos + 1) != Some(&b'{') || after_prefix.get(eq_pos + 2) != Some(&b'"') {
        return false;
    }
    disrobe_core::byte_search::contains(src, STRUCT_IPAIRS_SUFFIX)
}

fn matches_minify_shape(src: &[u8]) -> bool {
    if src.len() < 256 {
        return false;
    }
    let head_len: usize = src.len().min(4096);
    let head: &[u8] = &src[..head_len];
    let starts_local_table: bool = head.starts_with(b"local ")
        && head
            .get(6..8)
            .is_some_and(|w: &[u8]| w[0].is_ascii_alphabetic() && w[1] == b'=');
    if !starts_local_table {
        return false;
    }
    let newlines: usize = head.iter().filter(|b: &&u8| **b == b'\n').count();
    let density: usize = head_len / newlines.max(1);
    density >= 512
}

const VMIFY_DISPATCH_SCAN_LIMIT: usize = 1 << 24;

fn matches_vmify_container_shape(src: &[u8]) -> bool {
    if src.len() > VMIFY_DISPATCH_SCAN_LIMIT
        || !disrobe_core::byte_search::contains(src, b"function")
        || !disrobe_core::byte_search::contains(src, b"while ")
    {
        return false;
    }
    let text: std::borrow::Cow<'_, str> = String::from_utf8_lossy(src);
    !matches!(
        crate::obfuscator::prometheus_vm_cfg::recover(&text),
        Ok(None)
    )
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    const WEAK_EQUIVALENT: &[u8] =
        include_bytes!("../../../../corpus/lua/prometheus/weak/obfuscated.lua");

    #[test]
    fn refuses_source_before_constant_array_parsing() {
        let mut source: Vec<u8> = WEAK_EQUIVALENT.to_vec();
        source.resize(
            crate::obfuscator::prometheus_vm_ast::MAX_SOURCE_BYTES + 1,
            b' ',
        );
        let error: Error = peel(&source, &DeobfOptions::default())
            .expect_err("the source budget must be enforced before pool parsing");
        assert!(matches!(
            error,
            Error::LimitExceeded {
                section: "Prometheus source bytes",
                count,
                limit: crate::obfuscator::prometheus_vm_ast::MAX_SOURCE_BYTES,
            } if count == u64::try_from(source.len()).expect("test input length must fit u64")
        ));
    }

    #[test]
    fn refuses_constant_array_entry_count_over_budget() {
        let budget: ConstantArrayBudget = ConstantArrayBudget {
            max_source_bytes: usize::MAX,
            max_entries: 12,
            max_decoded_bytes: usize::MAX,
        };
        let error: Error = peel_with_budget(WEAK_EQUIVALENT, &DeobfOptions::default(), budget)
            .expect_err("the thirteenth constant-array entry must exceed the budget");
        assert!(matches!(
            error,
            Error::LimitExceeded {
                section: "Prometheus constant-array entries",
                count: 13,
                limit: 12,
            }
        ));
    }

    #[test]
    fn refuses_constant_array_decoded_bytes_over_budget() {
        let budget: ConstantArrayBudget = ConstantArrayBudget {
            max_source_bytes: usize::MAX,
            max_entries: usize::MAX,
            max_decoded_bytes: 0,
        };
        let error: Error = peel_with_budget(WEAK_EQUIVALENT, &DeobfOptions::default(), budget)
            .expect_err("the first decoded byte must exceed the budget");
        assert!(matches!(
            error,
            Error::LimitExceeded {
                section: "Prometheus constant-array decoded bytes",
                limit: 0,
                ..
            }
        ));
    }
}
