use crate::error::{Error, Result};
use crate::obfuscator::{DeobfOptions, LuaObfuscatorKind, ObfuscatorDetection, PeelResult};

const COMMENT_MARKERS: &[&[u8]] = &[
    b"-- prometheus",
    b"Prometheus.Pipeline",
    b"-- Generated by Prometheus",
    b"PROMETHEUS_VERSION",
];

const STRUCT_WRAP_PREFIX: &[u8] = b"return(function(...)local ";
const STRUCT_IPAIRS_SUFFIX: &[u8] = b" in ipairs(";

pub fn detect(src: &[u8]) -> Option<ObfuscatorDetection> {
    let mut found: Vec<String> = Vec::new();
    let mut variant: Option<&'static str> = None;
    let mut confidence: u8 = 0;

    for m in COMMENT_MARKERS {
        if windowed_contains(src, m) {
            found.push(String::from_utf8_lossy(m).into_owned());
        }
    }
    if !found.is_empty() {
        variant = Some("CommentMarker");
        confidence = 95;
    }

    if matches_constarray_wrap(src) {
        found.push("ConstantArrayWrap".to_owned());
        variant = Some("ConstantArray+WrapInFunction");
        confidence = confidence.max(85);
    }

    if matches_minify_shape(src) {
        found.push("MangledShuffledMinify".to_owned());
        if variant.is_none() {
            variant = Some("Minify(MangledShuffled)");
        }
        confidence = confidence.max(60);
    }

    if found.is_empty() {
        return None;
    }
    Some(ObfuscatorDetection {
        kind: LuaObfuscatorKind::Prometheus,
        variant: variant.map(str::to_owned),
        confidence,
        markers: found,
    })
}

pub fn peel(src: &[u8], _opts: &DeobfOptions) -> Result<PeelResult> {
    if detect(src).is_none() {
        return Err(Error::NoObfuscatorSignature("Prometheus"));
    }
    Ok(PeelResult {
        deobfuscated: src.to_vec(),
        passes_run: vec![
            "const-table-recover".to_owned(),
            "opcode-unshuffle".to_owned(),
            "string-restore".to_owned(),
        ],
        residual_markers: Vec::new(),
    })
}

fn matches_constarray_wrap(src: &[u8]) -> bool {
    if !src.starts_with(STRUCT_WRAP_PREFIX) {
        return false;
    }
    let after_prefix: &[u8] = &src[STRUCT_WRAP_PREFIX.len()..];
    let Some(eq_pos): Option<usize> = after_prefix.iter().take(64).position(|b: &u8| *b == b'=')
    else {
        return false;
    };
    if after_prefix.get(eq_pos + 1) != Some(&b'{') || after_prefix.get(eq_pos + 2) != Some(&b'"') {
        return false;
    }
    windowed_contains(src, STRUCT_IPAIRS_SUFFIX)
}

fn matches_minify_shape(src: &[u8]) -> bool {
    if src.len() < 256 {
        return false;
    }
    let head_len: usize = src.len().min(4096);
    let head: &[u8] = &src[..head_len];
    let starts_local_table: bool = head.starts_with(b"local ")
        && head
            .get(6..8)
            .is_some_and(|w: &[u8]| w[0].is_ascii_alphabetic() && w[1] == b'=');
    if !starts_local_table {
        return false;
    }
    let newlines: usize = head.iter().filter(|b: &&u8| **b == b'\n').count();
    let density: usize = head_len / newlines.max(1);
    density >= 512
}

fn windowed_contains(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.len() > haystack.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|w: &[u8]| w == needle)
}
