use super::super::CodeEntry;

pub(super) const CLI_A: &[CodeEntry] = &[
    CodeEntry {
        code: "DR-CLI-0000",
        title: "subcommand not yet implemented",
        description: "the requested CLI subcommand exists in the parser but has no implementation in this build.",
        common_causes: &["running a v0.x build that still ships scaffolding stubs"],
        common_fixes: &[
            "check `disrobe --version` & `disrobe passes` to confirm which features are wired",
            "track progress at https://github.com/1-3-7/disrobe/issues",
        ],
        crate_path: "crates/disrobe-cli/src/cli/util.rs",
    },
    CodeEntry {
        code: "DR-CLI-0001",
        title: "cannot read pyarmor wrapper file",
        description: "the path given to `pyarmor unpack` could not be read as a UTF-8 text file.",
        common_causes: &[
            "file does not exist",
            "permission denied",
            "path points at a binary instead of the wrapper .py",
        ],
        common_fixes: &[
            "verify the path with `ls`/`dir`",
            "check filesystem permissions",
            "pass the wrapper .py emitted by `pyarmor obfuscate`, not the runtime DLL/SO",
        ],
        crate_path: "crates/disrobe-cli/src/cli/pyarmor.rs",
    },
    CodeEntry {
        code: "DR-CLI-0002",
        title: "cannot create pyarmor output directory",
        description: "the `--out` path could not be created on disk.",
        common_causes: &[
            "permission denied on parent dir",
            "path crosses a read-only mount",
        ],
        common_fixes: &[
            "pick a writable `--out` location",
            "create the parent directory first",
        ],
        crate_path: "crates/disrobe-cli/src/cli/pyarmor.rs",
    },
    CodeEntry {
        code: "DR-CLI-0003",
        title: "cannot write pyarmor manifest",
        description: "could not write `manifest.json` into the output dir.",
        common_causes: &["disk full", "permission revoked mid-run"],
        common_fixes: &["free disk space", "retry with a different `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/pyarmor.rs",
    },
    CodeEntry {
        code: "DR-CLI-0004",
        title: "cannot write decrypted plaintext",
        description: "post-decryption plaintext could not be written to disk.",
        common_causes: &["disk full", "permission denied"],
        common_fixes: &["check free space", "retry"],
        crate_path: "crates/disrobe-cli/src/cli/pyarmor.rs",
    },
    CodeEntry {
        code: "DR-CLI-0005",
        title: "cannot write reconstructed pyc",
        description: "the rebuilt .pyc could not be persisted.",
        common_causes: &["disk full", "permission denied"],
        common_fixes: &["check free space", "retry"],
        crate_path: "crates/disrobe-cli/src/cli/pyarmor.rs",
    },
    CodeEntry {
        code: "DR-CLI-0011",
        title: "cannot read pyinstaller input",
        description: "`pyinstaller detect|extract` could not read the binary path.",
        common_causes: &["file does not exist", "permission denied"],
        common_fixes: &["verify path", "fix permissions"],
        crate_path: "crates/disrobe-cli/src/cli/pyinstaller.rs",
    },
    CodeEntry {
        code: "DR-CLI-0012",
        title: "cannot read pyinstaller archive for extract",
        description: "`pyinstaller extract` could not load the binary into memory.",
        common_causes: &["file does not exist", "permission denied"],
        common_fixes: &["verify path", "fix permissions"],
        crate_path: "crates/disrobe-cli/src/cli/pyinstaller.rs",
    },
    CodeEntry {
        code: "DR-CLI-0013",
        title: "cannot create pyinstaller out dir",
        description: "extraction directory could not be created.",
        common_causes: &["permission denied", "parent dir missing"],
        common_fixes: &["choose a writable location"],
        crate_path: "crates/disrobe-cli/src/cli/pyinstaller.rs",
    },
    CodeEntry {
        code: "DR-CLI-0014",
        title: "cannot write pyinstaller manifest",
        description: "`manifest.json` write failed inside the pyinstaller output dir.",
        common_causes: &["disk full", "permission denied"],
        common_fixes: &["free space", "retry"],
        crate_path: "crates/disrobe-cli/src/cli/pyinstaller.rs",
    },
    CodeEntry {
        code: "DR-CLI-0015",
        title: "cannot write pyinstaller entry",
        description: "a single TOC entry from the pyinstaller archive could not be written.",
        common_causes: &[
            "disk full",
            "filename contained reserved characters on this OS",
        ],
        common_fixes: &["retry to a different `--out` on a filesystem that allows the name"],
        crate_path: "crates/disrobe-cli/src/cli/pyinstaller.rs",
    },
    CodeEntry {
        code: "DR-CLI-0016",
        title: "cannot read nuitka input",
        description: "`nuitka extract` could not read the binary path.",
        common_causes: &["file does not exist", "permission denied"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0017",
        title: "input is not a nuitka --onefile build",
        description: "no KA[XY] onefile payload header was detected.",
        common_causes: &[
            "binary is a Nuitka --standalone build",
            "binary is not a Nuitka build at all",
        ],
        common_fixes: &[
            "use `nuitka symbols` for --standalone builds",
            "run `nuitka detect` first to confirm flavor",
        ],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0018",
        title: "cannot create nuitka out dir",
        description: "`--out` directory could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["pick a writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0019",
        title: "cannot write nuitka entry",
        description: "a payload entry write failed.",
        common_causes: &["disk full", "reserved filename characters"],
        common_fixes: &["change `--out`", "free space"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0020",
        title: "cannot read nuitka symbols input",
        description: "`nuitka symbols` could not read the binary.",
        common_causes: &["bad path", "permission denied"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0021",
        title: "cannot create nuitka symbols dir",
        description: "parent directory for symbols.json could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["choose writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0022",
        title: "cannot write nuitka symbols json",
        description: "symbol graph json write failed.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/nuitka.rs",
    },
    CodeEntry {
        code: "DR-CLI-0030",
        title: "cannot read py-deob input",
        description: "`py deob` could not read the source file.",
        common_causes: &["bad path", "permission denied"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0031",
        title: "cannot create py-deob out dir",
        description: "parent of `--out` could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0032",
        title: "cannot write deobfuscated python",
        description: "the rewritten source could not be written.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0033",
        title: "cannot write py-deob manifest",
        description: "the per-run manifest.json could not be written.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0034",
        title: "cannot read sourcedefender input",
        description: "`py sourcedefender` could not read the .pye file.",
        common_causes: &["bad path", "permission denied"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0035",
        title: "cannot create sourcedefender out dir",
        description: "parent of `--out` could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0036",
        title: "cannot write sourcedefender plaintext",
        description: "decrypted msgpack envelope could not be persisted.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0037",
        title: "cannot read js-deob input",
        description: "`js deob` could not read source.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/js.rs",
    },
    CodeEntry {
        code: "DR-CLI-0038",
        title: "cannot create js-deob out dir",
        description: "parent of `--out` could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/js.rs",
    },
    CodeEntry {
        code: "DR-CLI-0039",
        title: "cannot write js detection json",
        description: "the `*.detection.json` sidecar write failed.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/js.rs",
    },
    CodeEntry {
        code: "DR-CLI-0040",
        title: "cannot read wasm input",
        description: "`wasm` could not read the module.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/wasm.rs",
    },
    CodeEntry {
        code: "DR-CLI-0041",
        title: "cannot create wasm out dir",
        description: "parent of `--out` could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/wasm.rs",
    },
    CodeEntry {
        code: "DR-CLI-0042",
        title: "non utf-8 source / write failed",
        description: "either the JS source was not valid UTF-8, or the wasm summary.json write failed (two passes reuse this code).",
        common_causes: &[
            "binary file passed as JS source",
            "disk full on wasm output",
        ],
        common_fixes: &["check input charset", "free space"],
        crate_path: "crates/disrobe-cli/src/cli/{js,wasm}.rs",
    },
    CodeEntry {
        code: "DR-CLI-0043",
        title: "cannot write deobfuscated js",
        description: "the rewritten .js could not be persisted.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/js.rs",
    },
    CodeEntry {
        code: "DR-CLI-0044",
        title: "cannot write js recovery json",
        description: "the `*.recovery.json` sidecar write failed.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/js.rs",
    },
    CodeEntry {
        code: "DR-CLI-0050",
        title: "cannot read pyc input",
        description: "`py disasm` could not read the .pyc.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
];
