use super::super::CodeEntry;

pub(super) const CLI_B: &[CodeEntry] = &[
    CodeEntry {
        code: "DR-CLI-0051",
        title: "input is not a valid pyc",
        description: "the marshal header did not parse.",
        common_causes: &[
            "file is not a .pyc",
            "corrupt header",
            "unknown python magic",
        ],
        common_fixes: &[
            "confirm input via `file`",
            "regenerate with the matching python version",
        ],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0052",
        title: "pyc body is not a code object",
        description: "the marshalled root object was not a CodeObject.",
        common_causes: &["malformed .pyc", "wrong tool used to produce the file"],
        common_fixes: &["verify with `python -m dis` for sanity"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0053",
        title: "cannot create disasm dir",
        description: "parent of `--out` could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0054",
        title: "cannot write disasm text",
        description: "the rendered disassembly could not be written.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0055",
        title: "cannot write disasm json",
        description: "the structured disassembly json could not be written.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/py.rs",
    },
    CodeEntry {
        code: "DR-CLI-0060",
        title: "cannot create pyfreeze out dir",
        description: "extraction directory could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/pyfreeze.rs",
    },
    CodeEntry {
        code: "DR-CLI-0061",
        title: "cannot write pyfreeze manifest",
        description: "`manifest.json` write failed.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/pyfreeze.rs",
    },
    CodeEntry {
        code: "DR-CLI-0062",
        title: "pyfreeze manifest serialize failed",
        description: "the manifest could not be encoded to json.",
        common_causes: &["internal bug - please report"],
        common_fixes: &["open an issue at https://github.com/1-3-7/disrobe/issues"],
        crate_path: "crates/disrobe-cli/src/cli/pyfreeze.rs",
    },
    CodeEntry {
        code: "DR-CLI-0080",
        title: "cannot read envelope",
        description: "the .dr envelope could not be opened.",
        common_causes: &["bad path", "file is not a disrobe envelope"],
        common_fixes: &["produce one first with `envelope create`"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0081",
        title: "malformed envelope sidecar",
        description: "the postcard cold sidecar failed to decode.",
        common_causes: &[
            "envelope produced by a newer disrobe version",
            "file truncated",
        ],
        common_fixes: &["upgrade disrobe", "re-emit the envelope"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0082",
        title: "only --rung raw is implemented",
        description: "envelope create supports `--rung raw` only in v0.1.",
        common_causes: &["passed `--rung disasm` etc."],
        common_fixes: &["use `--rung raw` until other rungs land"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0083",
        title: "cannot read source for envelope create",
        description: "the input file could not be loaded.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0084",
        title: "rkyv encode failed",
        description: "encoding the raw payload to the .dr hot region failed.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0085",
        title: "postcard encode failed",
        description: "encoding the cold sidecar failed.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0086",
        title: "cannot write envelope",
        description: "the .dr envelope could not be written to disk.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0087",
        title: "envelope verification failed",
        description: "BLAKE3 root hash did not match the envelope payload.",
        common_causes: &["tampered envelope", "truncated file"],
        common_fixes: &["re-fetch the envelope", "regenerate"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0088",
        title: "cannot read envelope for diff/migrate-check",
        description: "one of the two .dr envelopes could not be read or its sidecar failed to decode.",
        common_causes: &[
            "bad path",
            "file is not a disrobe envelope",
            "truncated sidecar",
        ],
        common_fixes: &["verify both paths point at valid .dr envelopes"],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0089",
        title: "envelope migration is unsound",
        description: "no transcode path exists, or a Requires capability is unsatisfiable, or a Produces capability is dropped/downgraded.",
        common_causes: &[
            "incompatible rungs",
            "capability major-version bump",
            "dropped output capability",
        ],
        common_fixes: &[
            "register the missing transcode",
            "align capability majors between source and target",
        ],
        crate_path: "crates/disrobe-cli/src/cli/envelope.rs",
    },
    CodeEntry {
        code: "DR-CLI-0090",
        title: "auto sniff: cannot read input",
        description: "the input file given to `disrobe auto` could not be read.",
        common_causes: &["bad path", "permission denied"],
        common_fixes: &["verify path", "fix permissions"],
        crate_path: "crates/disrobe-cli/src/cli/auto.rs",
    },
    CodeEntry {
        code: "DR-CLI-0091",
        title: "machine-format serialize failed",
        description: "could not serialize the result to json / ndjson / sarif.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/output.rs",
    },
    CodeEntry {
        code: "DR-CLI-0092",
        title: "stdout write failed",
        description: "writing the machine-format result to stdout failed.",
        common_causes: &["downstream pipe closed", "redirected to read-only path"],
        common_fixes: &["redirect to a writable file"],
        crate_path: "crates/disrobe-cli/src/cli/output.rs",
    },
    CodeEntry {
        code: "DR-CLI-0093",
        title: "sarif inner serialize failed",
        description: "could not convert the inner payload to a sarif-compatible json value.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/output.rs",
    },
    CodeEntry {
        code: "DR-CLI-0094",
        title: "sarif envelope serialize failed",
        description: "could not encode the final SARIF v2.1.0 envelope.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/output.rs",
    },
    CodeEntry {
        code: "DR-CLI-0100",
        title: "auto: chain exceeded max depth",
        description: "the sniffer-chain hit its depth cap before reaching a terminal artifact.",
        common_causes: &["deeply nested wrappers", "cycle (same hash twice)"],
        common_fixes: &[
            "raise `--max-depth`",
            "inspect intermediate stages under out/",
        ],
        crate_path: "crates/disrobe-cli/src/cli/auto.rs",
    },
    CodeEntry {
        code: "DR-CLI-0101",
        title: "auto: cycle detected",
        description: "the sniffer-chain produced a stage whose BLAKE3 hash matched a prior stage.",
        common_causes: &[
            "pass that returns identity on its own output",
            "recursive self-wrapping",
        ],
        common_fixes: &["report the input - disrobe should grow a guard for this family"],
        crate_path: "crates/disrobe-cli/src/cli/auto.rs",
    },
    CodeEntry {
        code: "DR-CLI-0102",
        title: "explain: unknown DR code",
        description: "no documentation registered for the requested code.",
        common_causes: &["typo", "code emitted by a newer disrobe build"],
        common_fixes: &[
            "upgrade disrobe",
            "file an issue listing the code & the message you saw",
        ],
        crate_path: "crates/disrobe-cli/src/cli/explain.rs",
    },
    CodeEntry {
        code: "DR-CLI-0110",
        title: "init: target .disrobe already exists",
        description: "`disrobe init` refuses to overwrite an existing scaffold without `--force`.",
        common_causes: &["re-running init in an initialized project"],
        common_fixes: &["pass `--force` to overwrite, or remove `.disrobe/` first"],
        crate_path: "crates/disrobe-cli/src/cli/init.rs",
    },
    CodeEntry {
        code: "DR-CLI-0111",
        title: "init: cannot create .disrobe dir",
        description: "the `.disrobe/` directory could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["run with sufficient permissions"],
        crate_path: "crates/disrobe-cli/src/cli/init.rs",
    },
    CodeEntry {
        code: "DR-CLI-0112",
        title: "init: cannot write scaffold file",
        description: "writing one of the scaffold files failed mid-run.",
        common_causes: &["disk full", "permission revoked"],
        common_fixes: &["retry, then `disrobe init --force`"],
        crate_path: "crates/disrobe-cli/src/cli/init.rs",
    },
    CodeEntry {
        code: "DR-CLI-0120",
        title: "bug-report: cannot write report",
        description: "could not write the bug report to disk.",
        common_causes: &["disk full", "permission denied"],
        common_fixes: &["pick a writable `--out` or pipe to stdout via `--out -`"],
        crate_path: "crates/disrobe-cli/src/cli/bug_report.rs",
    },
    CodeEntry {
        code: "DR-CLI-0130",
        title: "man: cannot create output dir",
        description: "`disrobe man --out` directory could not be created.",
        common_causes: &["permission denied"],
        common_fixes: &["pick writable `--out`"],
        crate_path: "crates/disrobe-cli/src/cli/man.rs",
    },
    CodeEntry {
        code: "DR-CLI-0131",
        title: "man: render failed",
        description: "`clap_mangen` failed to render a subcommand page.",
        common_causes: &["internal bug - clap signature change"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-cli/src/cli/man.rs",
    },
    CodeEntry {
        code: "DR-CLI-0132",
        title: "man: cannot write page",
        description: "writing the .1 page failed.",
        common_causes: &["disk full"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-cli/src/cli/man.rs",
    },
    CodeEntry {
        code: "DR-CLI-0140",
        title: "completions install: cannot locate shell config",
        description: "could not figure out which rc file to update for the requested shell.",
        common_causes: &["uncommon shell layout", "missing HOME / PROFILE env"],
        common_fixes: &["pass `--rc-file` to point at your rc explicitly"],
        crate_path: "crates/disrobe-cli/src/cli/completions.rs",
    },
    CodeEntry {
        code: "DR-CLI-0141",
        title: "completions install: cannot write rc file",
        description: "appending the source line to the rc file failed.",
        common_causes: &["permission denied"],
        common_fixes: &["chown/chmod the rc file"],
        crate_path: "crates/disrobe-cli/src/cli/completions.rs",
    },
    CodeEntry {
        code: "DR-CLI-0150",
        title: "status: cannot read out/ tree",
        description: "could not walk the working directory's `out/` tree.",
        common_causes: &["permission denied"],
        common_fixes: &["fix permissions"],
        crate_path: "crates/disrobe-cli/src/cli/status.rs",
    },
    CodeEntry {
        code: "DR-CLI-0320",
        title: "guard denied write to ground-truth stage path",
        description: "the candidate path is a committed chain stage output (out/**/stages|final, a .disrobe-stage-lock-marked file, or under an explicit --root) and must not be edited.",
        common_causes: &[
            "editing a mirrored stage output.bin",
            "writing inside out/**/final",
            "path under a .disrobe-stage-lock",
        ],
        common_fixes: &[
            "edit the pass source, not the captured stage artifact",
            "re-run `disrobe chain` to regenerate stages",
            "remove the .disrobe-stage-lock if the lock is stale",
        ],
        crate_path: "crates/disrobe-cli/src/cli/guard.rs",
    },
    CodeEntry {
        code: "DR-CLI-0321",
        title: "guard: cannot resolve --root",
        description: "a `--root` protected subtree could not be canonicalized.",
        common_causes: &["nonexistent root dir", "permission denied"],
        common_fixes: &["pass an existing directory to --root"],
        crate_path: "crates/disrobe-cli/src/cli/guard.rs",
    },
];
