use super::super::CodeEntry;

pub(super) const MISC: &[CodeEntry] = &[
    CodeEntry {
        code: "DR-JSDEOB-0001",
        title: "no JS obfuscator family matched",
        description: "the source did not match any known JS obfuscator pattern.",
        common_causes: &["plain JS"],
        common_fixes: &["nothing to deobfuscate"],
        crate_path: "crates/disrobe-pass-js-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-JSDEOB-0002",
        title: "js-deob I/O error",
        description: "I/O failed.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-js-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-JSDEOB-0003",
        title: "js-deob oxc parse error",
        description: "the oxc parser rejected the source.",
        common_causes: &["malformed JS", "unsupported syntax"],
        common_fixes: &["check input with a JS validator"],
        crate_path: "crates/disrobe-pass-js-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-JSDEOB-0004",
        title: "js-deob invalid utf-8",
        description: "the JS source was not UTF-8.",
        common_causes: &["binary input"],
        common_fixes: &["pass valid UTF-8"],
        crate_path: "crates/disrobe-pass-js-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-WASMDEOB-0001",
        title: "not a valid WebAssembly module",
        description: "wasmparser rejected the binary.",
        common_causes: &["wrong file", "truncated module"],
        common_fixes: &["validate with `wasm-validate`"],
        crate_path: "crates/disrobe-pass-wasm-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-WASMDEOB-0002",
        title: "wasm-deob I/O error",
        description: "I/O failed.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-wasm-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0001",
        title: "marshal EOF",
        description: "input ran out before parsing completed.",
        common_causes: &["truncated marshal payload"],
        common_fixes: &["re-fetch source bytes"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0002",
        title: "marshal unknown tag",
        description: "an unrecognized marshal type byte was seen.",
        common_causes: &["wrong python version assumed"],
        common_fixes: &["pass correct pyver"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0003",
        title: "marshal invalid utf-8",
        description: "a marshal string was not valid UTF-8.",
        common_causes: &["wrong python version"],
        common_fixes: &["pass correct pyver"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0004",
        title: "marshal ref-table OOB",
        description: "back-reference index exceeded ref table size.",
        common_causes: &["corrupted marshal stream"],
        common_fixes: &["re-fetch source"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0005",
        title: "code object shape mismatch",
        description: "code object field count did not match the python era.",
        common_causes: &["wrong python version assumed"],
        common_fixes: &["pass correct pyver"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0006",
        title: "unsupported python version",
        description: "the python version reported by the header is not yet supported.",
        common_causes: &["very new or very old python"],
        common_fixes: &["file an issue listing the magic / pyver"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0007",
        title: "pyc header too short",
        description: "the pyc header was truncated.",
        common_causes: &["wrong file passed as pyc"],
        common_fixes: &["confirm with `file`"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0008",
        title: "unknown pyc magic",
        description: "the pyc magic number does not map to any known python version.",
        common_causes: &["very new / custom build"],
        common_fixes: &["file an issue"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0009",
        title: "marshal depth limit exceeded",
        description: "the marshal nesting depth exceeded the safety limit.",
        common_causes: &["pathological input"],
        common_fixes: &["refuse the sample"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0010",
        title: "long-int digit count too large",
        description: "long-int field would allocate beyond the sanity cap.",
        common_causes: &["pathological input"],
        common_fixes: &["refuse the sample"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0011",
        title: "container length too large",
        description: "tuple/list/dict length exceeded the sanity cap.",
        common_causes: &["pathological input"],
        common_fixes: &["refuse the sample"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
    CodeEntry {
        code: "DR-MARSHAL-0012",
        title: "marshal writer length overflow",
        description: "payload exceeded the marshal u32 size field max.",
        common_causes: &["asked to encode oversize payload"],
        common_fixes: &["split into smaller chunks"],
        crate_path: "crates/disrobe-py-marshal/src/error.rs",
    },
];
