use super::super::CodeEntry;

pub(super) const PYTHON_B: &[CodeEntry] = &[
    CodeEntry {
        code: "DR-NUITKA-0010",
        title: "nuitka reassembly needs >=1 entry",
        description: "the payload was empty.",
        common_causes: &["corrupted onefile"],
        common_fixes: &["re-fetch sample"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0001",
        title: "not a sourcedefender .pye",
        description: "BEGIN/END markers were not found.",
        common_causes: &["wrong file"],
        common_fixes: &["confirm extension; pass the original .pye"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0002",
        title: "sourcedefender I/O error",
        description: "I/O failure reading the .pye.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0003",
        title: "sourcedefender empty filename",
        description: "the filename is empty, so the filename-derived password cannot be computed.",
        common_causes: &["empty path"],
        common_fixes: &["pass a non-empty filename"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0004",
        title: "sourcedefender base85 decode failed",
        description: "the IV or ciphertext base85 block did not decode.",
        common_causes: &["wrong file", "tampered envelope"],
        common_fixes: &["regenerate sourcedefender output"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0005",
        title: "sourcedefender bad IV length",
        description: "IV was not 16 bytes.",
        common_causes: &["wrong file"],
        common_fixes: &["regenerate"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0006",
        title: "sourcedefender blake2 error",
        description: "internal blake2b error.",
        common_causes: &["internal bug"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0007",
        title: "sourcedefender not UTF-8",
        description: "the .pye envelope must be UTF-8.",
        common_causes: &["binary garbage"],
        common_fixes: &["verify input"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0008",
        title: "sourcedefender msgpack decode failed",
        description: "the inner msgpack envelope did not parse.",
        common_causes: &["corrupt payload"],
        common_fixes: &["regenerate"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0009",
        title: "sourcedefender inlined filename missing",
        description: "the inlined envelope did not carry a filename hint.",
        common_causes: &["non-standard inlined layout"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-SDEF-0010",
        title: "sourcedefender inlined no decrypt",
        description: "found blocks but none decrypted successfully.",
        common_causes: &["wrong filename hint", "tampered envelope"],
        common_fixes: &["pass the correct filename"],
        crate_path: "crates/disrobe-pass-sourcedefender/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0001",
        title: "no obfuscation family matched",
        description: "the source did not match any known python obfuscator pattern.",
        common_causes: &["plain code", "very rare obfuscator"],
        common_fixes: &["file an issue with a sample"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0002",
        title: "py-deob I/O error",
        description: "I/O failed.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0003",
        title: "py-deob depth limit reached",
        description: "encoder peel hit the depth cap without converging.",
        common_causes: &["very deeply nested encoder", "non-terminating obfuscator"],
        common_fixes: &["report sample for investigation"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0004",
        title: "py-deob base64 decode failed",
        description: "an intermediate base64 layer did not decode.",
        common_causes: &["custom alphabet", "corrupted source"],
        common_fixes: &["re-fetch the sample"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0005",
        title: "py-deob zlib decompression failed",
        description: "an intermediate zlib layer did not decompress.",
        common_causes: &["wrong layer detected"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0006",
        title: "py-deob lzma decompression failed",
        description: "an intermediate lzma layer did not decompress.",
        common_causes: &["wrong layer detected"],
        common_fixes: &["open an issue"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0007",
        title: "py-deob bytes literal not found",
        description: "the obfuscator's bytes literal was not located.",
        common_causes: &["unusual wrapper layout"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0008",
        title: "py-deob invalid utf-8 in output",
        description: "the deobfuscated bytes were not valid UTF-8 python source.",
        common_causes: &["wrong layer detected"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYDEOB-0009",
        title: "py-deob AST cleanup failed",
        description: "ruff-AST cleanup pass errored out.",
        common_causes: &["invalid python in intermediate stage"],
        common_fixes: &["disable `--cleanup` & inspect"],
        crate_path: "crates/disrobe-pass-py-deob/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0001",
        title: "not a recognized python freezer container",
        description: "input did not look like cx_Freeze / py2exe / shiv / pex / PyOxidizer / Briefcase.",
        common_causes: &["wrong tool", "unknown freezer"],
        common_fixes: &["try other passes"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0002",
        title: "pyfreeze I/O error",
        description: "I/O failed.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0003",
        title: "cx_Freeze missing sibling layout",
        description: "required sibling files were missing next to the binary.",
        common_causes: &["partial install"],
        common_fixes: &["copy the full bundle (lib/, python*.dll, etc.)"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0004",
        title: "py2exe PYTHONSCRIPT resource missing",
        description: "the PE resource was not present.",
        common_causes: &["repacked py2exe"],
        common_fixes: &["confirm with a resource viewer"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0005",
        title: "py2exe scriptinfo tag mismatch",
        description: "expected 0x78563412 tag absent.",
        common_causes: &["corrupted resource"],
        common_fixes: &["re-fetch sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0006",
        title: "py2exe scriptinfo truncated",
        description: "scriptinfo body shorter than required.",
        common_causes: &["truncated PE"],
        common_fixes: &["re-fetch"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0007",
        title: "shiv missing _bootstrap/",
        description: "shiv archive missing required bootstrap dir.",
        common_causes: &["repacked shiv"],
        common_fixes: &["use original shiv output"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0008",
        title: "shiv missing environment.json",
        description: "shiv manifest missing.",
        common_causes: &["repacked"],
        common_fixes: &["use original"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0009",
        title: "pex missing PEX-INFO",
        description: "pex manifest missing.",
        common_causes: &["repacked"],
        common_fixes: &["use original"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0010",
        title: "trailing zip EOCD missing",
        description: "end-of-central-directory record was not found in the trailing zip.",
        common_causes: &["truncated archive"],
        common_fixes: &["re-fetch"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0011",
        title: "zip parse failed",
        description: "the embedded zip did not parse.",
        common_causes: &["custom compression"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0012",
        title: "zip entry extraction failed",
        description: "a single zip entry could not be decompressed/written.",
        common_causes: &["disk full", "filename collision"],
        common_fixes: &["free space"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0013",
        title: "pyfreeze PE parse failed",
        description: "the PE header did not parse.",
        common_causes: &["truncated"],
        common_fixes: &["re-fetch"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0014",
        title: "shebang invalid",
        description: "shebang manifest line did not match shiv/pex grammar.",
        common_causes: &["modified bootstrap"],
        common_fixes: &["use original output"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0015",
        title: "unsafe archive entry path",
        description: "entry name attempted to escape the container root.",
        common_causes: &["malicious archive"],
        common_fixes: &["blocked; do not bypass"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0016",
        title: "payload decompression failed",
        description: "the inner payload could not be decompressed.",
        common_causes: &["custom compression"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0017",
        title: "json manifest parse failed",
        description: "the freezer's JSON manifest did not parse.",
        common_causes: &["custom freezer version"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0018",
        title: "pyfreeze quota exceeded",
        description: "extraction quota guard tripped on an entry.",
        common_causes: &["zip-bomb-style archive"],
        common_fixes: &["raise quota via env or refuse the sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0019",
        title: "PyOxidizer config block missing",
        description: "no embedded Python configuration was located in the PyOxidizer build.",
        common_causes: &["older PyOxidizer build"],
        common_fixes: &["report sample"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYFRZ-0020",
        title: "Briefcase missing sibling layout",
        description: "Briefcase support requires sibling files we could not find.",
        common_causes: &["partial bundle"],
        common_fixes: &["copy the full Briefcase output"],
        crate_path: "crates/disrobe-pass-pyfreeze/src/error.rs",
    },
];
