use super::super::CodeEntry;

pub(super) const PYTHON_A: &[CodeEntry] = &[
    CodeEntry {
        code: "DR-PYARM-0001",
        title: "input does not appear to be a PyArmor wrapper",
        description: "the file did not match any known PyArmor wrapper layout.",
        common_causes: &[
            "plain python source",
            "wrapper from an unknown PyArmor version",
        ],
        common_fixes: &[
            "confirm via `pyarmor inspect` upstream",
            "open an issue with a redacted sample",
        ],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0002",
        title: "unknown PyArmor wrapper format",
        description: "the wrapper shape did not match v6/v7/v8/v9 grammar.",
        common_causes: &["new PyArmor release", "custom build"],
        common_fixes: &["file an issue with the wrapper's first 200 lines"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0003",
        title: "payload bytes literal missing",
        description: "the embedded `b'...'` payload could not be located in the wrapper.",
        common_causes: &[
            "custom wrapper layout",
            "wrapper has been further obfuscated",
        ],
        common_fixes: &["run `py deob` first to peel the outer encoder"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0004",
        title: "PyArmor runtime extension not found",
        description: "no pyarmor runtime DLL/SO was located next to the wrapper.",
        common_causes: &[
            "sample shipped without runtime",
            "runtime is at a custom path",
        ],
        common_fixes: &["place the runtime DLL/SO in the same dir as the wrapper"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0005",
        title: "PyArmor v8/v9 header truncated",
        description: "the v8/v9 header was shorter than the expected fixed length.",
        common_causes: &["truncated download", "wrong file"],
        common_fixes: &["re-fetch the sample"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0006",
        title: "PyArmor v8/v9 magic mismatch",
        description: "expected `PY` + 6 digits magic was not present.",
        common_causes: &["sample is not v8/v9"],
        common_fixes: &["try the v6/v7 path"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0007",
        title: "PyArmor v6/v7 magic mismatch",
        description: "expected `PYARMOR\\0` magic was not present.",
        common_causes: &["sample is not v6/v7"],
        common_fixes: &["try the v8/v9 path", "verify with `pyarmor inspect`"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0008",
        title: "runtime DLL parse failed",
        description: "could not parse the PyArmor runtime extension.",
        common_causes: &["corrupt runtime", "unsupported runtime version"],
        common_fixes: &["ensure the runtime matches the wrapper version"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0009",
        title: "AES key extraction failed",
        description: "could not recover the AES key from the runtime.",
        common_causes: &[
            "runtime patched with non-default key derivation",
            "BCC mode in use",
        ],
        common_fixes: &["try `--allow-dynamic` to capture the runtime in a sandbox"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0010",
        title: "AES decryption failed",
        description: "the recovered key did not yield valid marshal output.",
        common_causes: &["wrong key extracted", "wrong IV"],
        common_fixes: &["try the dynamic hook fallback"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0011",
        title: "marshal decode error after decrypt",
        description: "the decrypted bytes did not parse as Python marshal.",
        common_causes: &["wrong decrypted payload", "outer layer not stripped"],
        common_fixes: &["re-run with `RUST_LOG=debug` & report the marshal offset"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0012",
        title: "pyarmor I/O error",
        description: "underlying I/O error reading input or runtime.",
        common_causes: &["bad paths", "permission denied"],
        common_fixes: &["fix paths/permissions"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0013",
        title: "PyArmor v3/v4/v5 capsule walled on the RSA-wrapped key",
        description: "v3-v5 capsule structure and metadata parse, but the bytecode AES key is RSA-wrapped with a private key the author never ships, so the plaintext is not in the artifact and cannot be recovered statically.",
        common_causes: &[
            "a v3-v5 capsule whose per-script AES key is sealed with the project private RSA key",
        ],
        common_fixes: &[
            "supply the cleartext capsule key if you hold it; structure, version, and metadata still parse without it",
        ],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0014",
        title: "BCC mode is partial-only",
        description: "BCC payloads require a native lifter; only the Python half is recoverable today.",
        common_causes: &["sample built with PyArmor BCC mode"],
        common_fixes: &[
            "accept partial recovery",
            "use `nuitka symbols`-style approach for the native side",
        ],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0015",
        title: "hex/escape decoding of wrapper bytes failed",
        description: "the Python bytes literal contained an escape sequence we cannot decode.",
        common_causes: &["wrapper post-processed by another obfuscator"],
        common_fixes: &["peel the outer obfuscator with `py deob` first"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0016",
        title: "dynamic hook required but not allowed",
        description: "static unpack failed & the dynamic-hook fallback was not enabled.",
        common_causes: &["v6/v7 sample with non-default key derivation"],
        common_fixes: &["re-run with `--allow-dynamic` inside a sandbox"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0017",
        title: "no usable Python found for dynamic hook",
        description: "no Python >= 3.9.7 was located on PATH.",
        common_causes: &["python not installed", "pyenv shim points elsewhere"],
        common_fixes: &[
            "install Python 3.9.7+",
            "set DISROBE_PYTHON to a usable interpreter",
        ],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0018",
        title: "dynamic hook timed out",
        description: "the watchdog killed the subprocess.",
        common_causes: &["sample exits slowly", "sample is interactive"],
        common_fixes: &["raise `--dynamic-timeout`"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0019",
        title: "dynamic hook subprocess error",
        description: "the dynamic-hook subprocess exited with a non-zero status.",
        common_causes: &["sample raised during import", "missing Python deps"],
        common_fixes: &["check the captured stderr in the output dir"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0020",
        title: "dynamic hook produced zero captures",
        description: "the subprocess ran but no marshal streams were captured.",
        common_causes: &[
            "sample exited before reaching protected code",
            "anti-debug check tripped",
        ],
        common_fixes: &["increase timeout, retry on a different host"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYARM-0021",
        title: "dynamic hook found python too old",
        description: "the located Python interpreter is older than the required 3.9.7.",
        common_causes: &["system python is 3.8 or older"],
        common_fixes: &["install a newer Python & set DISROBE_PYTHON"],
        crate_path: "crates/disrobe-pass-pyarmor/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0001",
        title: "PyInstaller MEI cookie not found",
        description: "the MEI cookie magic was not located in the binary.",
        common_causes: &[
            "binary is not a PyInstaller build",
            "binary was repacked / stripped",
        ],
        common_fixes: &[
            "confirm with strings | grep MEI",
            "try `nuitka detect` / `pyfreeze detect` instead",
        ],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0002",
        title: "PyInstaller cookie truncated",
        description: "the cookie header ran off the end of the file.",
        common_causes: &["truncated download"],
        common_fixes: &["re-fetch the sample"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0003",
        title: "PyInstaller I/O error",
        description: "underlying I/O error reading the binary.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0004",
        title: "PyInstaller TOC walk failed",
        description: "the table-of-contents walk produced an inconsistent entry.",
        common_causes: &["repacked archive", "custom packer"],
        common_fixes: &["re-fetch sample", "open an issue with the cookie offsets"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0005",
        title: "zlib inflate failed for entry",
        description: "a compressed TOC entry could not be decompressed.",
        common_causes: &["entry was AES-encrypted with no key provided"],
        common_fixes: &["if PyInstaller >= 6.0, decrypt with the bundled key first"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0006",
        title: "PyInstaller AES decrypt failed",
        description: "AES decryption produced invalid plaintext.",
        common_causes: &["wrong key", "PyInstaller >= 6.0 with custom key derivation"],
        common_fixes: &["supply key via PyInstaller hooks fork", "file an issue"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0007",
        title: "PyInstaller bad PYZ magic",
        description: "the inner PYZ archive did not start with `PYZ\\0`.",
        common_causes: &["corrupted archive"],
        common_fixes: &["re-fetch sample"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0008",
        title: "PyInstaller PYZ TOC marshal decode",
        description: "the PYZ table-of-contents marshal payload did not parse.",
        common_causes: &["wrong python version assumed", "corrupted PYZ"],
        common_fixes: &["use `pyinstaller detect` to confirm pyver"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0009",
        title: "PyInstaller path traversal",
        description: "a TOC entry name attempted to escape the output dir.",
        common_causes: &["malicious archive"],
        common_fixes: &["sample blocked; do not bypass"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-PYINST-0010",
        title: "PyInstaller bad pyver",
        description: "the pyver field did not decode to (major, minor).",
        common_causes: &["unknown PyInstaller bootloader fork"],
        common_fixes: &["open an issue with the cookie hex dump"],
        crate_path: "crates/disrobe-pass-pyinstaller/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0001",
        title: "not a Nuitka build",
        description: "no Nuitka signatures detected.",
        common_causes: &["binary is from a different packer"],
        common_fixes: &["try `pyinstaller detect` / `pyfreeze detect`"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0002",
        title: "nuitka I/O error",
        description: "I/O failed while reading the binary.",
        common_causes: &["bad path"],
        common_fixes: &["verify path"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0003",
        title: "PE/ELF/Mach-O parse error",
        description: "the executable header did not parse.",
        common_causes: &["truncated binary"],
        common_fixes: &["re-fetch"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0004",
        title: "nuitka onefile magic mismatch",
        description: "expected KA[XY] magic was not present.",
        common_causes: &["not a --onefile build"],
        common_fixes: &["use `nuitka symbols` instead"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0005",
        title: "nuitka zstd decompression failed",
        description: "the onefile payload could not be decompressed.",
        common_causes: &["corrupt sample"],
        common_fixes: &["re-fetch"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0006",
        title: "nuitka entry record truncated",
        description: "a per-entry record ran off the end of the payload.",
        common_causes: &["corrupt or truncated payload"],
        common_fixes: &["re-fetch sample"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0007",
        title: "nuitka source text not present",
        description: "Nuitka emits native code, so the original Python source text is not present in the artifact; constants and symbols are, and where the build .c is shipped, body recovery is partial.",
        common_causes: &["asking the wrong tool"],
        common_fixes: &[
            "use `nuitka symbols` for constants/symbols, then a native decompiler for the C++ side",
        ],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0008",
        title: "nuitka build-info missing",
        description: "the build-info section was not located in the image.",
        common_causes: &["stripped binary"],
        common_fixes: &["pass `-v` to expose more diagnostics"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
    CodeEntry {
        code: "DR-NUITKA-0009",
        title: "nuitka build-info malformed",
        description: "the build-info record did not parse.",
        common_causes: &["unsupported Nuitka version"],
        common_fixes: &["open an issue with version + first 64 bytes"],
        crate_path: "crates/disrobe-pass-nuitka/src/error.rs",
    },
];
