use serde::Serialize;

const HAXE_JS_BANNER: &[u8] = b"// Generated by Haxe";
const HAXE_HL_MAGIC: &[u8] = b"HLB";
const SWF_UNCOMPRESSED: &[u8] = b"FWS";
const SWF_ZLIB: &[u8] = b"CWS";
const SWF_LZMA: &[u8] = b"ZWS";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum HaxeTarget {
    JavaScript,
    SwfFlash,
    HashLink,
}

impl HaxeTarget {
    #[must_use]
    pub const fn route_pass_id(self) -> &'static str {
        match self {
            Self::JavaScript => "js.deob",
            Self::SwfFlash => "as3.classify",
            Self::HashLink => "scriptlang.classify",
        }
    }

    #[must_use]
    pub const fn target_label(self) -> &'static str {
        match self {
            Self::JavaScript => "haxe-js",
            Self::SwfFlash => "haxe-swf",
            Self::HashLink => "haxe-hl",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct HaxeFingerprint {
    pub target: HaxeTarget,
    pub route_pass_id: &'static str,
    pub compiler_version: Option<String>,
    pub haxe_confirmed: bool,
    pub hl_version: Option<u8>,
}

#[must_use]
pub fn detect(bytes: &[u8]) -> Option<HaxeFingerprint> {
    if let Some(fp) = detect_js(bytes) {
        return Some(fp);
    }
    if let Some(fp) = detect_hl(bytes) {
        return Some(fp);
    }
    detect_swf(bytes)
}

fn detect_js(bytes: &[u8]) -> Option<HaxeFingerprint> {
    let head: &[u8] = &bytes[..bytes.len().min(256)];
    if !starts_with(head, HAXE_JS_BANNER) {
        return None;
    }
    Some(HaxeFingerprint {
        target: HaxeTarget::JavaScript,
        route_pass_id: HaxeTarget::JavaScript.route_pass_id(),
        compiler_version: parse_js_version(head),
        haxe_confirmed: true,
        hl_version: None,
    })
}

fn detect_hl(bytes: &[u8]) -> Option<HaxeFingerprint> {
    if !starts_with(bytes, HAXE_HL_MAGIC) {
        return None;
    }
    let hl_version: Option<u8> = bytes.get(3).copied();
    Some(HaxeFingerprint {
        target: HaxeTarget::HashLink,
        route_pass_id: HaxeTarget::HashLink.route_pass_id(),
        compiler_version: None,
        haxe_confirmed: true,
        hl_version,
    })
}

fn detect_swf(bytes: &[u8]) -> Option<HaxeFingerprint> {
    let is_swf: bool = starts_with(bytes, SWF_UNCOMPRESSED)
        || starts_with(bytes, SWF_ZLIB)
        || starts_with(bytes, SWF_LZMA);
    if !is_swf {
        return None;
    }
    let haxe_confirmed: bool = window_contains(bytes, b"haxe") || window_contains(bytes, b"Haxe");
    Some(HaxeFingerprint {
        target: HaxeTarget::SwfFlash,
        route_pass_id: HaxeTarget::SwfFlash.route_pass_id(),
        compiler_version: None,
        haxe_confirmed,
        hl_version: None,
    })
}

fn parse_js_version(head: &[u8]) -> Option<String> {
    let text: &str = std::str::from_utf8(head).ok()?;
    let line: &str = text.lines().next()?;
    let after: &str = line.strip_prefix("// Generated by Haxe")?.trim();
    if after.is_empty() {
        None
    } else {
        Some(after.to_owned())
    }
}

#[inline]
fn starts_with(bytes: &[u8], prefix: &[u8]) -> bool {
    bytes.len() >= prefix.len() && &bytes[..prefix.len()] == prefix
}

#[inline]
fn window_contains(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || haystack.len() < needle.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|w: &[u8]| w == needle)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn detects_haxe_js_and_version() {
        let js: &[u8] = b"// Generated by Haxe 4.3.6\n(function ($global) { })({});\n";
        let fp: HaxeFingerprint = detect(js).expect("detect js");
        assert_eq!(fp.target, HaxeTarget::JavaScript);
        assert_eq!(fp.route_pass_id, "js.deob");
        assert_eq!(fp.compiler_version.as_deref(), Some("4.3.6"));
        assert!(fp.haxe_confirmed);
    }

    #[test]
    fn detects_hashlink() {
        let hl: &[u8] = b"HLB\x04\x01\x2d\x01";
        let fp: HaxeFingerprint = detect(hl).expect("detect hl");
        assert_eq!(fp.target, HaxeTarget::HashLink);
        assert_eq!(fp.hl_version, Some(4));
    }

    #[test]
    fn detects_swf_routes_to_as3() {
        let swf: &[u8] = b"CWS\n\xc3\x1b\x00\x00haxe-marker";
        let fp: HaxeFingerprint = detect(swf).expect("detect swf");
        assert_eq!(fp.target, HaxeTarget::SwfFlash);
        assert_eq!(fp.route_pass_id, "as3.classify");
        assert!(fp.haxe_confirmed);
    }

    #[test]
    fn rejects_non_haxe() {
        assert!(detect(b"plain text file with no haxe markers").is_none());
    }
}
