use serde::Serialize;

use crate::lang::hashlink::{self, HlCode, HlSummary};

const HAXE_JS_BANNER: &[u8] = b"// Generated by Haxe";
const HAXE_HL_MAGIC: &[u8] = b"HLB";
const NEKO_MAGIC: &[u8] = b"NEKO";
const SWF_UNCOMPRESSED: &[u8] = b"FWS";
const SWF_ZLIB: &[u8] = b"CWS";
const SWF_LZMA: &[u8] = b"ZWS";
const SWF_HEADER_BYTES: usize = 8usize;
const SWF_READ_CHUNK_BYTES: usize = 8192usize;
const MAX_SWF_BYTES: usize = 1usize << 26;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum HaxeTarget {
    JavaScript,
    SwfFlash,
    HashLink,
    Neko,
}

impl HaxeTarget {
    #[must_use]
    pub const fn route_pass_id(self) -> &'static str {
        match self {
            Self::JavaScript => "js.deob",
            Self::SwfFlash => "as3.classify",
            Self::HashLink | Self::Neko => "scriptlang.classify",
        }
    }

    #[must_use]
    pub const fn target_label(self) -> &'static str {
        match self {
            Self::JavaScript => "haxe-js",
            Self::SwfFlash => "haxe-swf",
            Self::HashLink => "haxe-hl",
            Self::Neko => "haxe-neko",
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct HaxeRecovered {
    pub classes: Vec<String>,
    pub methods: Vec<String>,
    pub source_files: Vec<String>,
    pub std_modules: Vec<String>,
    pub string_literals: Vec<String>,
}

impl HaxeRecovered {
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.classes.is_empty()
            && self.methods.is_empty()
            && self.source_files.is_empty()
            && self.std_modules.is_empty()
            && self.string_literals.is_empty()
    }

    #[must_use]
    pub fn symbol_count(&self) -> usize {
        self.classes.len() + self.methods.len()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct HaxeFingerprint {
    pub target: HaxeTarget,
    pub route_pass_id: &'static str,
    pub compiler_version: Option<String>,
    pub haxe_confirmed: bool,
    pub hl_version: Option<u8>,
    pub recovered: HaxeRecovered,
    pub hashlink: Option<Box<HlSummary>>,
}

#[must_use]
pub fn detect(bytes: &[u8]) -> Option<HaxeFingerprint> {
    if let Some(fp) = detect_js(bytes) {
        return Some(fp);
    }
    if let Some(fp) = detect_hl(bytes) {
        return Some(fp);
    }
    if let Some(fp) = detect_neko(bytes) {
        return Some(fp);
    }
    detect_swf(bytes)
}

fn detect_neko(bytes: &[u8]) -> Option<HaxeFingerprint> {
    if !starts_with(bytes, NEKO_MAGIC) {
        return None;
    }
    let recovered: HaxeRecovered = recover_vm_strings(bytes);
    let haxe_confirmed: bool = recovered
        .source_files
        .iter()
        .any(|s: &String| s.ends_with(".hx"))
        || window_contains(bytes, b"haxe")
        || window_contains(bytes, b"Haxe");
    if !haxe_confirmed {
        return None;
    }
    Some(HaxeFingerprint {
        target: HaxeTarget::Neko,
        route_pass_id: HaxeTarget::Neko.route_pass_id(),
        compiler_version: None,
        haxe_confirmed,
        hl_version: None,
        recovered,
        hashlink: None,
    })
}

fn detect_js(bytes: &[u8]) -> Option<HaxeFingerprint> {
    let head: &[u8] = &bytes[..bytes.len().min(256)];
    if !starts_with(head, HAXE_JS_BANNER) {
        return None;
    }
    Some(HaxeFingerprint {
        target: HaxeTarget::JavaScript,
        route_pass_id: HaxeTarget::JavaScript.route_pass_id(),
        compiler_version: parse_js_version(head),
        haxe_confirmed: true,
        hl_version: None,
        recovered: recover_js(bytes),
        hashlink: None,
    })
}

fn detect_hl(bytes: &[u8]) -> Option<HaxeFingerprint> {
    if !starts_with(bytes, HAXE_HL_MAGIC) {
        return None;
    }
    let hl_version: Option<u8> = bytes.get(3).copied();
    let mut recovered: HaxeRecovered = recover_vm_strings(bytes);
    let hashlink: Option<Box<HlSummary>> = match hashlink::read_code(bytes) {
        Ok(code) => {
            merge_hl_recovery(&mut recovered, &code);
            Some(Box::new(code.summary()))
        }
        Err(_) => None,
    };
    Some(HaxeFingerprint {
        target: HaxeTarget::HashLink,
        route_pass_id: HaxeTarget::HashLink.route_pass_id(),
        compiler_version: None,
        haxe_confirmed: true,
        hl_version,
        recovered,
        hashlink,
    })
}

fn merge_hl_recovery(recovered: &mut HaxeRecovered, code: &HlCode) {
    recovered.classes.extend(code.object_type_names());
    recovered.classes.extend(code.enum_type_names());
    recovered.methods.extend(code.method_names());
    for file in &code.debug_files {
        if !file.ends_with(".hx") {
            continue;
        }
        if file.contains("_std/") || file.contains("std/") || file.contains("/hl/") {
            recovered.std_modules.push(normalize_module_path(file));
        } else {
            recovered.source_files.push(leaf_name(file));
        }
    }
    dedup_sorted(&mut recovered.classes);
    dedup_sorted(&mut recovered.methods);
    dedup_sorted(&mut recovered.source_files);
    dedup_sorted(&mut recovered.std_modules);
}

fn detect_swf(bytes: &[u8]) -> Option<HaxeFingerprint> {
    let is_swf: bool = starts_with(bytes, SWF_UNCOMPRESSED)
        || starts_with(bytes, SWF_ZLIB)
        || starts_with(bytes, SWF_LZMA);
    if !is_swf {
        return None;
    }
    let inflated: Option<Vec<u8>> = if starts_with(bytes, SWF_ZLIB) {
        inflate_cws(bytes)
    } else {
        None
    };
    let recoverable: Option<&[u8]> = if starts_with(bytes, SWF_UNCOMPRESSED) {
        Some(bytes)
    } else {
        inflated.as_deref()
    };
    let recovered: HaxeRecovered =
        recoverable.map_or_else(HaxeRecovered::default, recover_vm_strings);
    let haxe_confirmed: bool = window_contains(bytes, b"haxe")
        || window_contains(bytes, b"Haxe")
        || recoverable.is_some_and(|decoded: &[u8]| {
            window_contains(decoded, b"haxe") || window_contains(decoded, b"Haxe")
        })
        || recovered
            .source_files
            .iter()
            .any(|source: &String| source.ends_with(".hx"));
    Some(HaxeFingerprint {
        target: HaxeTarget::SwfFlash,
        route_pass_id: HaxeTarget::SwfFlash.route_pass_id(),
        compiler_version: None,
        haxe_confirmed,
        hl_version: None,
        recovered,
        hashlink: None,
    })
}

fn inflate_cws(bytes: &[u8]) -> Option<Vec<u8>> {
    let header: &[u8] = bytes.get(..SWF_HEADER_BYTES)?;
    let declared_bytes: [u8; 4] = header.get(4usize..8usize)?.try_into().ok()?;
    let declared_len: usize = usize::try_from(u32::from_le_bytes(declared_bytes)).ok()?;
    if !(SWF_HEADER_BYTES..=MAX_SWF_BYTES).contains(&declared_len) {
        return None;
    }
    let declared_body_len: usize = declared_len.checked_sub(SWF_HEADER_BYTES)?;
    let output_limit: usize = declared_body_len.checked_add(1usize)?;
    let compressed: &[u8] = bytes.get(SWF_HEADER_BYTES..)?;
    let initial_capacity: usize = compressed
        .len()
        .min(declared_body_len)
        .min(SWF_READ_CHUNK_BYTES);
    let mut output: Vec<u8> = Vec::new();
    output.try_reserve(initial_capacity).ok()?;

    let mut decoder: flate2::Decompress = flate2::Decompress::new(true);
    let mut chunk: [u8; SWF_READ_CHUNK_BYTES] = [0u8; SWF_READ_CHUNK_BYTES];
    let mut input_offset: usize = 0usize;
    loop {
        let remaining_output: usize = output_limit.checked_sub(output.len())?;
        if remaining_output == 0usize {
            return None;
        }
        let output_len: usize = remaining_output.min(chunk.len());
        let input: &[u8] = compressed.get(input_offset..)?;
        let flush: flate2::FlushDecompress = if input.is_empty() {
            flate2::FlushDecompress::Finish
        } else {
            flate2::FlushDecompress::None
        };
        let before_in: u64 = decoder.total_in();
        let before_out: u64 = decoder.total_out();
        let status: flate2::Status = decoder
            .decompress(input, chunk.get_mut(..output_len)?, flush)
            .ok()?;
        let consumed: usize = usize::try_from(decoder.total_in().checked_sub(before_in)?).ok()?;
        let produced: usize = usize::try_from(decoder.total_out().checked_sub(before_out)?).ok()?;
        input_offset = input_offset.checked_add(consumed)?;
        let decoded: &[u8] = chunk.get(..produced)?;
        output.try_reserve(produced).ok()?;
        output.extend_from_slice(decoded);
        if status == flate2::Status::StreamEnd {
            break;
        }
        if consumed == 0usize && produced == 0usize {
            return None;
        }
    }
    if output.len() != declared_body_len || input_offset != compressed.len() {
        return None;
    }

    output.try_reserve(SWF_HEADER_BYTES).ok()?;
    output.resize(declared_len, 0u8);
    output.rotate_right(SWF_HEADER_BYTES);
    let reconstructed_header: &mut [u8] = output.get_mut(..SWF_HEADER_BYTES)?;
    reconstructed_header.copy_from_slice(header);
    let signature: &mut [u8] = output.get_mut(..SWF_UNCOMPRESSED.len())?;
    signature.copy_from_slice(SWF_UNCOMPRESSED);
    Some(output)
}

fn recover_js(bytes: &[u8]) -> HaxeRecovered {
    let Ok(text): Result<&str, _> = std::str::from_utf8(bytes) else {
        return HaxeRecovered::default();
    };
    let mut classes: Vec<String> = Vec::new();
    let mut methods: Vec<String> = Vec::new();
    let mut std_modules: Vec<String> = Vec::new();
    let mut source_files: Vec<String> = Vec::new();
    let mut string_literals: Vec<String> = Vec::new();

    for line in text.lines() {
        let trimmed: &str = line.trim_start();
        if let Some(name) = js_class_decl(trimmed) {
            if name.contains('_') {
                std_modules.push(name);
            } else {
                classes.push(name);
            }
        }
        if let Some(name) = js_static_method(trimmed) {
            methods.push(name);
        }
        if let Some(name) = js_proto_method(trimmed) {
            methods.push(name);
        }
        for src in js_source_markers(line) {
            source_files.push(src);
        }
        for lit in js_string_literals(line) {
            string_literals.push(lit);
        }
    }

    dedup_sorted(&mut classes);
    dedup_sorted(&mut methods);
    dedup_sorted(&mut std_modules);
    dedup_sorted(&mut source_files);
    dedup_sorted(&mut string_literals);
    HaxeRecovered {
        classes,
        methods,
        source_files,
        std_modules,
        string_literals,
    }
}

fn js_class_decl(line: &str) -> Option<String> {
    let rest: &str = line.strip_prefix("var ")?;
    let eq: usize = rest.find(" = ")?;
    let name: &str = &rest[..eq];
    let after: &str = rest[eq + 3..].trim_start();
    if (after.starts_with("function") || after.starts_with("$hx_exports"))
        && is_identifier(name)
        && name != "$global"
    {
        Some(name.to_owned())
    } else {
        None
    }
}

fn js_static_method(line: &str) -> Option<String> {
    let eq: usize = line.find(" = function")?;
    let lhs: &str = &line[..eq];
    let dot: usize = lhs.rfind('.')?;
    let owner: &str = &lhs[..dot];
    let method: &str = &lhs[dot + 1..];
    if is_identifier(owner.split('.').next().map_or(owner, |value: &str| value))
        && is_identifier(method)
        && method != "prototype"
    {
        Some(method.to_owned())
    } else {
        None
    }
}

fn js_proto_method(line: &str) -> Option<String> {
    let trimmed: &str = line.trim_start();
    let body: &str = trimmed
        .strip_prefix(',')
        .map_or(trimmed, |value: &str| value);
    let colon: usize = body.find(':')?;
    let after: &str = body[colon + 1..].trim_start();
    if !after.starts_with("function") {
        return None;
    }
    let name: &str = body[..colon].trim();
    if is_identifier(name) {
        Some(name.to_owned())
    } else {
        None
    }
}

fn js_source_markers(line: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut search: &str = line;
    while let Some(hx) = search.find(".hx:") {
        let before: &str = &search[..hx];
        let start: usize = before
            .rfind(|c: char| c == '"' || c == '\'' || c.is_whitespace())
            .map_or(0, |i: usize| i + 1);
        let file: &str = &search[start..hx + 3];
        let file: &str = file.trim_start_matches(['"', '\'']);
        if !file.is_empty() && file.ends_with(".hx") {
            out.push(file.to_owned());
        }
        search = &search[hx + 4..];
    }
    out
}

fn js_string_literals(line: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let bytes: &[u8] = line.as_bytes();
    let mut i: usize = 0usize;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let start: usize = i + 1;
            let mut j: usize = start;
            while j < bytes.len() && bytes[j] != b'"' {
                if bytes[j] == b'\\' {
                    j += 1;
                }
                j += 1;
            }
            if j <= bytes.len() {
                let lit: &str = line
                    .get(start..j.min(bytes.len()))
                    .map_or("", |value: &str| value);
                if lit.len() >= 3 && lit.len() <= 64 && !lit.contains(".hx:") && is_printable(lit) {
                    out.push(lit.to_owned());
                }
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
    out
}

fn recover_vm_strings(bytes: &[u8]) -> HaxeRecovered {
    let mut classes: Vec<String> = Vec::new();
    let mut methods: Vec<String> = Vec::new();
    let mut source_files: Vec<String> = Vec::new();
    let mut std_modules: Vec<String> = Vec::new();

    for run in printable_runs(bytes, 3) {
        let token: &str = run.trim_start_matches(['$', '@']);
        if token.ends_with(".hx") {
            if token.contains("_std") || token.contains("/hl/") || token.contains("std/") {
                std_modules.push(normalize_module_path(token));
            } else {
                source_files.push(leaf_name(token));
            }
        } else if is_dotted_type_path(token) {
            std_modules.push(token.to_owned());
        } else if is_identifier(token) && token.chars().next().is_some_and(char::is_uppercase) {
            classes.push(token.to_owned());
        } else if is_identifier(token) {
            methods.push(token.to_owned());
        }
    }

    dedup_sorted(&mut classes);
    dedup_sorted(&mut methods);
    dedup_sorted(&mut source_files);
    dedup_sorted(&mut std_modules);
    HaxeRecovered {
        classes,
        methods,
        source_files,
        std_modules,
        string_literals: Vec::new(),
    }
}

fn printable_runs(bytes: &[u8], min: usize) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut current: Vec<u8> = Vec::new();
    for &b in bytes {
        if (0x20..=0x7e).contains(&b) {
            current.push(b);
        } else {
            if current.len() >= min {
                out.push(String::from_utf8_lossy(&current).into_owned());
            }
            current.clear();
        }
    }
    if current.len() >= min {
        out.push(String::from_utf8_lossy(&current).into_owned());
    }
    out
}

fn normalize_module_path(path: &str) -> String {
    let core: &str = path.split("_std/").last().map_or(path, |value: &str| value);
    let core: &str = core.split("std/").last().map_or(core, |value: &str| value);
    core.trim_end_matches(".hx").replace('/', ".")
}

fn leaf_name(path: &str) -> String {
    path.rsplit(['/', '\\'])
        .next()
        .map_or(path, |value: &str| value)
        .to_owned()
}

fn is_dotted_type_path(s: &str) -> bool {
    s.contains('.')
        && !s.contains(' ')
        && !s.contains('/')
        && !s.contains('\\')
        && s.split('.').all(is_identifier)
        && s.split('.').count() >= 2
}

fn is_identifier(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .next()
            .is_some_and(|c: char| c.is_alphabetic() || c == '_')
        && s.chars().all(|c: char| c.is_alphanumeric() || c == '_')
}

fn is_printable(s: &str) -> bool {
    s.chars().all(|c: char| !c.is_control())
}

fn dedup_sorted(items: &mut Vec<String>) {
    items.sort_unstable();
    items.dedup();
}

fn parse_js_version(head: &[u8]) -> Option<String> {
    let text: &str = std::str::from_utf8(head).ok()?;
    let line: &str = text.lines().next()?;
    let after: &str = line.strip_prefix("// Generated by Haxe")?.trim();
    if after.is_empty() {
        None
    } else {
        Some(after.to_owned())
    }
}

#[inline]
fn starts_with(bytes: &[u8], prefix: &[u8]) -> bool {
    bytes.len() >= prefix.len() && &bytes[..prefix.len()] == prefix
}

#[inline]
fn window_contains(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || haystack.len() < needle.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|w: &[u8]| w == needle)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use std::io::Write;

    fn make_cws(body: &[u8]) -> Vec<u8> {
        let declared_len: u32 = u32::try_from(
            SWF_HEADER_BYTES
                .checked_add(body.len())
                .expect("test body length"),
        )
        .expect("test SWF length");
        let mut encoder: flate2::write::ZlibEncoder<Vec<u8>> =
            flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::fast());
        encoder.write_all(body).expect("compress test body");
        let compressed: Vec<u8> = encoder.finish().expect("finish test stream");
        let mut bytes: Vec<u8> =
            Vec::with_capacity(SWF_HEADER_BYTES.saturating_add(compressed.len()));
        bytes.extend_from_slice(SWF_ZLIB);
        bytes.push(10u8);
        bytes.extend_from_slice(&declared_len.to_le_bytes());
        bytes.extend_from_slice(&compressed);
        bytes
    }

    fn set_cws_declared_len(bytes: &mut [u8], declared_len: u32) {
        let field: &mut [u8] = bytes
            .get_mut(4usize..SWF_HEADER_BYTES)
            .expect("test SWF header");
        field.copy_from_slice(&declared_len.to_le_bytes());
    }

    #[test]
    fn detects_haxe_js_and_version() {
        let js: &[u8] = b"// Generated by Haxe 4.3.6\n(function ($global) { })({});\n";
        let fp: HaxeFingerprint = detect(js).expect("detect js");
        assert_eq!(fp.target, HaxeTarget::JavaScript);
        assert_eq!(fp.route_pass_id, "js.deob");
        assert_eq!(fp.compiler_version.as_deref(), Some("4.3.6"));
        assert!(fp.haxe_confirmed);
    }

    #[test]
    fn detects_hashlink() {
        let hl: &[u8] = b"HLB\x04\x01\x2d\x01";
        let fp: HaxeFingerprint = detect(hl).expect("detect hl");
        assert_eq!(fp.target, HaxeTarget::HashLink);
        assert_eq!(fp.hl_version, Some(4));
    }

    #[test]
    fn detects_swf_routes_to_as3() {
        let swf: &[u8] = b"CWS\n\xc3\x1b\x00\x00haxe-marker";
        let fp: HaxeFingerprint = detect(swf).expect("detect swf");
        assert_eq!(fp.target, HaxeTarget::SwfFlash);
        assert_eq!(fp.route_pass_id, "as3.classify");
        assert!(fp.haxe_confirmed);
    }

    #[test]
    fn cws_rejects_invalid_declared_lengths() {
        assert!(inflate_cws(b"CWS").is_none());
        let mut below_header: Vec<u8> = make_cws(b"haxe Main Main.hx");
        set_cws_declared_len(&mut below_header, 7u32);
        assert!(inflate_cws(&below_header).is_none());
        let mut above_limit: Vec<u8> = make_cws(b"haxe Main Main.hx");
        let oversized: u32 =
            u32::try_from(MAX_SWF_BYTES.saturating_add(1usize)).expect("limit fits u32");
        set_cws_declared_len(&mut above_limit, oversized);
        assert!(inflate_cws(&above_limit).is_none());
    }

    #[test]
    fn cws_rejects_declared_body_mismatch() {
        let body: &[u8] = b"haxe Main Main.hx";
        let declared_len: u32 = u32::try_from(
            SWF_HEADER_BYTES
                .checked_add(body.len())
                .expect("test body length"),
        )
        .expect("test SWF length");
        let mut short: Vec<u8> = make_cws(body);
        set_cws_declared_len(
            &mut short,
            declared_len.checked_sub(1u32).expect("shorter length"),
        );
        assert!(inflate_cws(&short).is_none());
        let mut long: Vec<u8> = make_cws(body);
        set_cws_declared_len(
            &mut long,
            declared_len.checked_add(1u32).expect("longer length"),
        );
        assert!(inflate_cws(&long).is_none());
    }

    #[test]
    fn cws_rejects_truncated_stream() {
        let mut bytes: Vec<u8> = make_cws(b"haxe Main Main.hx");
        let _: Option<u8> = bytes.pop();
        assert!(inflate_cws(&bytes).is_none());
    }

    #[test]
    fn cws_rejects_checksum_corruption() {
        let mut bytes: Vec<u8> = make_cws(b"haxe Main Main.hx");
        let last_index: usize = bytes.len().checked_sub(1usize).expect("test stream byte");
        let last: &mut u8 = bytes.get_mut(last_index).expect("test stream byte");
        *last ^= 0xffu8;
        assert!(inflate_cws(&bytes).is_none());
    }

    #[test]
    fn cws_rejects_trailing_bytes() {
        let mut bytes: Vec<u8> = make_cws(b"haxe Main Main.hx");
        bytes.push(0u8);
        assert!(inflate_cws(&bytes).is_none());
    }

    #[test]
    fn rejects_non_haxe() {
        assert!(detect(b"plain text file with no haxe markers").is_none());
    }
}
