pub mod haxe;
pub mod perl;
pub mod perl_bytecode;
pub mod r_rds;
pub mod rcpp;
pub mod tcl;

use std::io::Read;

use serde::Serialize;

use crate::error::{Error, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ScriptLang {
    Perl,
    R,
    Tcl,
    Haxe,
}

impl ScriptLang {
    #[must_use]
    pub const fn tag(self) -> &'static str {
        match self {
            Self::Perl => "perl-concise",
            Self::R => "r-rds",
            Self::Tcl => "tcl-starkit",
            Self::Haxe => "haxe-target",
        }
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "lang", rename_all = "kebab-case")]
pub enum ScriptArtifact {
    Perl(perl::PerlOpTree),
    R(r_rds::RdsObject),
    Tcl(tcl::StarkitContainer),
    Haxe(haxe::HaxeFingerprint),
}

impl ScriptArtifact {
    #[must_use]
    pub const fn lang(&self) -> ScriptLang {
        match self {
            Self::Perl(_) => ScriptLang::Perl,
            Self::R(_) => ScriptLang::R,
            Self::Tcl(_) => ScriptLang::Tcl,
            Self::Haxe(_) => ScriptLang::Haxe,
        }
    }
}

const GZIP_MAGIC: [u8; 2] = [0x1f, 0x8b];

#[must_use]
pub fn classify(bytes: &[u8]) -> Option<ScriptLang> {
    if haxe::detect(bytes).is_some() {
        return Some(ScriptLang::Haxe);
    }
    if tcl::is_starkit(bytes) {
        return Some(ScriptLang::Tcl);
    }
    if rds_detectable(bytes) {
        return Some(ScriptLang::R);
    }
    if perl_bytecode::is_bytecode(bytes) || perl::is_concise(bytes) {
        return Some(ScriptLang::Perl);
    }
    None
}

pub fn analyze(bytes: &[u8]) -> Result<ScriptArtifact> {
    if let Some(fp) = haxe::detect(bytes) {
        return Ok(ScriptArtifact::Haxe(fp));
    }
    if tcl::is_starkit(bytes) {
        return Ok(ScriptArtifact::Tcl(tcl::extract(bytes)?));
    }
    if let Some(rds_bytes) = maybe_gunzip_rds(bytes) {
        return Ok(ScriptArtifact::R(r_rds::read_rds(&rds_bytes)?));
    }
    if perl_bytecode::is_bytecode(bytes) {
        return Ok(ScriptArtifact::Perl(perl_bytecode::read_bytecode(bytes)?));
    }
    if perl::is_concise(bytes) {
        return Ok(ScriptArtifact::Perl(perl::read_concise(bytes)?));
    }
    Err(Error::Unrecognized)
}

pub fn analyze_rcpp(bytes: &[u8]) -> Result<rcpp::RcppFingerprint> {
    let rds_bytes: Vec<u8> = maybe_gunzip_rds(bytes).ok_or(Error::Unrecognized)?;
    let obj: r_rds::RdsObject = r_rds::read_rds(&rds_bytes)?;
    Ok(rcpp::fingerprint(&obj, &rds_bytes))
}

fn rds_detectable(bytes: &[u8]) -> bool {
    maybe_gunzip_rds(bytes).is_some_and(|b: Vec<u8>| r_rds::is_rds(&b))
}

fn maybe_gunzip_rds(bytes: &[u8]) -> Option<Vec<u8>> {
    if r_rds::is_rds(bytes) {
        return Some(bytes.to_vec());
    }
    if bytes.len() >= 2 && bytes[..2] == GZIP_MAGIC {
        let mut decoder: flate2::read::GzDecoder<&[u8]> = flate2::read::GzDecoder::new(bytes);
        let mut out: Vec<u8> = Vec::new();
        if decoder.read_to_end(&mut out).is_ok() && r_rds::is_rds(&out) {
            return Some(out);
        }
    }
    None
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn classify_haxe_js() {
        let js: &[u8] = b"// Generated by Haxe 4.3.6\n();\n";
        assert_eq!(classify(js), Some(ScriptLang::Haxe));
    }

    #[test]
    fn classify_rejects_random() {
        assert!(classify(b"random bytes with no recognizable script signature here").is_none());
    }

    #[test]
    fn analyze_haxe_returns_fingerprint() {
        let js: &[u8] = b"// Generated by Haxe 4.3.6\n();\n";
        let art: ScriptArtifact = analyze(js).expect("analyze");
        assert_eq!(art.lang(), ScriptLang::Haxe);
    }
}
