[package]
name = "disrobe-sleigh"
description = "Sleigh source front end and scalar AArch64 P-code lifter."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["sleigh", "aarch64", "pcode", "decoder", "lifter"]
categories.workspace = true

[lints]
workspace = true

[dev-dependencies]
disrobe-core.workspace = true
