use std::sync::LazyLock;

use regex::Regex;
use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum PsObfuscator {
    IseSteroids,
    InvokeObfuscationToken,
    InvokeObfuscationString,
    EncodedHex,
    EncodedOctal,
    EncodedBinary,
    EncodedAscii,
    EncodedBxor,
    EncodedSpecialChar,
    EncodedWhitespace,
    Base64Encoded,
    GzipCompressed,
    SecureString,
    IexIndirection,
    None,
}

#[derive(Debug, Clone, Serialize)]
pub struct ObfuscatorDetection {
    pub obfuscator: PsObfuscator,
    pub confidence: f32,
    pub markers: Vec<String>,
    pub ranked: Vec<(PsObfuscator, f32)>,
}

struct SignatureSpec {
    family: PsObfuscator,
    marker: &'static str,
    weight: f32,
    pattern: &'static str,
}

struct Signature {
    family: PsObfuscator,
    marker: &'static str,
    weight: f32,
    re: Regex,
}

const fn sig(
    family: PsObfuscator,
    marker: &'static str,
    weight: f32,
    pattern: &'static str,
) -> SignatureSpec {
    SignatureSpec {
        family,
        marker,
        weight,
        pattern,
    }
}

static SIGNATURES: LazyLock<Vec<Signature>> = LazyLock::new(|| {
    SIGNATURE_SPECS
        .iter()
        .map(|s: &SignatureSpec| Signature {
            family: s.family,
            marker: s.marker,
            weight: s.weight,
            re: crate::regex_util::safe_regex(s.pattern),
        })
        .collect()
});

static SIGNATURE_SPECS: &[SignatureSpec] = &[
    sig(
        PsObfuscator::IseSteroids,
        "isesteroids-sig-block",
        0.6,
        r"(?im)^#\s*SIG\s*#\s*Begin signature block",
    ),
    sig(
        PsObfuscator::IseSteroids,
        "isesteroids-banner",
        0.5,
        r"(?i)ISESteroids|generated by ISE",
    ),
    sig(
        PsObfuscator::IseSteroids,
        "homoglyph-cyrillic",
        0.35,
        r"[\x{0400}-\x{04FF}]",
    ),
    sig(
        PsObfuscator::EncodedHex,
        "hex-toint16",
        0.55,
        r"(?i)\[convert\]::toint(?:16|32|64)\s*\(\s*\$_\s*,\s*16\s*\)",
    ),
    sig(
        PsObfuscator::EncodedHex,
        "hex-0x-array",
        0.3,
        r"(?i)(?:0x[0-9a-f]{2}[^0-9a-f]+){4,}",
    ),
    sig(
        PsObfuscator::EncodedOctal,
        "octal-toint8",
        0.6,
        r"(?i)\[convert\]::toint(?:16|32|64)\s*\(\s*\$_\s*,\s*8\s*\)",
    ),
    sig(
        PsObfuscator::EncodedBinary,
        "binary-toint2",
        0.6,
        r"(?i)\[convert\]::toint(?:16|32|64)\s*\(\s*\$_\s*,\s*2\s*\)",
    ),
    sig(
        PsObfuscator::EncodedBxor,
        "bxor-operator",
        0.55,
        r"(?i)-b\s*xor\s+\d",
    ),
    sig(
        PsObfuscator::EncodedAscii,
        "char-array-join",
        0.4,
        r"(?i)\[char\[\]\]\s*\(?\s*\(?(?:\d{1,3}\s*,\s*){3,}",
    ),
    sig(
        PsObfuscator::EncodedSpecialChar,
        "special-char-only",
        0.55,
        r"\$\{[^A-Za-z0-9]{2,}\}",
    ),
    sig(
        PsObfuscator::EncodedWhitespace,
        "whitespace-encoded",
        0.5,
        r"(?i)\$\{[ \t]{4,}\}|\.length[^;]{0,40}\$\(\s*\)",
    ),
    sig(
        PsObfuscator::Base64Encoded,
        "frombase64",
        0.45,
        r"(?i)FromBase64String\s*\(",
    ),
    sig(
        PsObfuscator::Base64Encoded,
        "encodedcommand-flag",
        0.5,
        r"(?i)\s-e(?:nc(?:odedcommand)?)?\s+[A-Za-z0-9+/=]{16,}",
    ),
    sig(
        PsObfuscator::GzipCompressed,
        "gzip-deflate-stream",
        0.55,
        r"(?i)IO\.Compression\.(?:GZip|Deflate)Stream",
    ),
    sig(
        PsObfuscator::SecureString,
        "securestring",
        0.55,
        r"(?i)ConvertTo-SecureString|System\.Security\.SecureString",
    ),
    sig(
        PsObfuscator::InvokeObfuscationToken,
        "char-byte-token",
        0.45,
        r"(?i)\$\{?[A-Za-z0-9_]+\}?\s*=\s*\(\s*\[(?:char|byte)\]",
    ),
    sig(
        PsObfuscator::InvokeObfuscationToken,
        "backtick-density",
        0.3,
        r"(?:`[A-Za-z]){3,}",
    ),
    sig(
        PsObfuscator::InvokeObfuscationString,
        "format-operator",
        0.45,
        r#"(?i)['"][^'"]*\{0\}[^'"]*['"]\s*-f\s+"#,
    ),
    sig(
        PsObfuscator::InvokeObfuscationString,
        "string-reorder-join",
        0.35,
        r"(?i)\(\s*['\x22][^'\x22]+['\x22](?:\s*,\s*['\x22][^'\x22]+['\x22]){2,}\s*\)\s*-join",
    ),
    sig(
        PsObfuscator::IexIndirection,
        "iex-comspec",
        0.6,
        r"(?i)\$env:ComSpec\s*\[\s*\d+\s*,",
    ),
    sig(
        PsObfuscator::IexIndirection,
        "iex-mdr-variable",
        0.6,
        r"(?i)(?:Get-Variable|GV|Variable)\s+'?\*mdr\*'?",
    ),
    sig(
        PsObfuscator::IexIndirection,
        "iex-verbosepref",
        0.55,
        r"(?i)\$VerbosePreference\.ToString\s*\(\s*\)",
    ),
    sig(
        PsObfuscator::IexIndirection,
        "iex-getcommand-indirect",
        0.55,
        r"(?i)\$ExecutionContext\.InvokeCommand\.GetCommand",
    ),
];

#[must_use]
pub fn obfuscator_detect(input: &str) -> ObfuscatorDetection {
    let mut markers: Vec<String> = Vec::new();
    let mut scores: Vec<(PsObfuscator, f32)> = Vec::new();
    for sig in SIGNATURES.iter() {
        if sig.re.is_match(input) {
            markers.push(sig.marker.to_owned());
            match scores
                .iter_mut()
                .find(|(f, _): &&mut (PsObfuscator, f32)| *f == sig.family)
            {
                Some((_, acc)) => *acc += sig.weight,
                None => scores.push((sig.family, sig.weight)),
            }
        }
    }
    for entry in &mut scores {
        entry.1 = entry.1.min(1.0);
    }
    scores.sort_by(|a: &(PsObfuscator, f32), b: &(PsObfuscator, f32)| {
        b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal)
    });
    let (obfuscator, confidence): (PsObfuscator, f32) =
        scores.first().copied().unwrap_or((PsObfuscator::None, 0.0));
    ObfuscatorDetection {
        obfuscator,
        confidence,
        markers,
        ranked: scores,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_isesteroids_signature_block() {
        let src: &str =
            "Write-Host 'hi'\n# SIG # Begin signature block\nAAAA\n# SIG # End signature block\n";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::IseSteroids);
        assert!(d.confidence >= 0.6, "confidence={}", d.confidence);
    }

    #[test]
    fn detects_hex_encoder() {
        let src: &str = "$x | ForEach-Object {[Char]([Convert]::ToInt16($_,16))} | IEX";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::EncodedHex);
    }

    #[test]
    fn detects_bxor_encoder() {
        let src: &str = "(72,73,74 | %{[char]($_ -bxor 42)}) -join ''";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::EncodedBxor);
    }

    #[test]
    fn detects_iex_comspec_indirection() {
        let src: &str = "&( $env:ComSpec[4,15,25]-Join'')( $payload )";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::IexIndirection);
        assert!(d.markers.iter().any(|m: &String| m == "iex-comspec"));
    }

    #[test]
    fn detects_mdr_variable_indirection() {
        let src: &str = "((Variable '*mdr*').Name[3,11,2]-Join'')( $sc )";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::IexIndirection);
    }

    #[test]
    fn detects_base64_encoded_command() {
        let src: &str = "powershell -nop -enc QQBBAEEAQQBBAEEAQQBBAEEAQQBB";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::Base64Encoded);
    }

    #[test]
    fn plain_script_scores_none() {
        let src: &str = "Write-Host 'hello world'\nGet-Process | Sort-Object CPU\n";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert_eq!(d.obfuscator, PsObfuscator::None);
        assert!(d.confidence.abs() < f32::EPSILON);
    }

    #[test]
    fn ranked_breakdown_orders_by_confidence() {
        let src: &str =
            "# SIG # Begin signature block\n$x=([char]73);IEX (Variable '*mdr*').Value\n";
        let d: ObfuscatorDetection = obfuscator_detect(src);
        assert!(!d.ranked.is_empty());
        for win in d.ranked.windows(2) {
            assert!(win[0].1 >= win[1].1, "ranked not sorted: {:?}", d.ranked);
        }
    }
}
