pub(crate) mod annot;
#[cfg(feature = "jvm")]
pub(crate) mod apk;
#[cfg(feature = "as3")]
pub(crate) mod as3;
#[cfg(feature = "chain")]
pub(crate) mod auto;
#[cfg(feature = "chain")]
pub(crate) mod batch;
#[cfg(feature = "beam")]
pub(crate) mod beam;
pub(crate) mod behavior;
pub(crate) mod bug_report;
pub(crate) mod capabilities;
#[cfg(feature = "chain")]
pub(crate) mod catalog;
#[cfg(feature = "chain")]
pub(crate) mod catalog_registry;
#[cfg(feature = "chain")]
pub(crate) mod chain_compare;
#[cfg(feature = "chain")]
pub(crate) mod chain_v1;
pub(crate) mod completions;
pub(crate) mod config;
pub(crate) mod config_merge;
pub(crate) mod context;
pub(crate) mod cyclonedx;
#[cfg(feature = "chain")]
pub(crate) mod detect;
pub(crate) mod doctor;
#[cfg(feature = "dotnet")]
pub(crate) mod dotnet;
pub(crate) mod emit;
pub(crate) mod envelope;
pub(crate) mod explain;
pub(crate) mod extract;
#[cfg(feature = "flutter")]
pub(crate) mod flutter;
pub(crate) mod frisk;
#[cfg(feature = "chain")]
pub(crate) mod glob;
pub(crate) mod globals;
#[cfg(feature = "go")]
pub(crate) mod go;
#[cfg(feature = "server")]
pub(crate) mod grpc;
#[cfg(feature = "chain")]
pub(crate) mod guard;
#[cfg(feature = "mobile")]
pub(crate) mod hermes;
pub(crate) mod identify;
pub(crate) mod indicators;
pub(crate) mod init;
pub(crate) mod install;
pub(crate) mod install_deps;
pub(crate) mod ioc;
pub(crate) mod ir_metadata;
#[cfg(feature = "js")]
pub(crate) mod js;
#[cfg(feature = "jvm")]
pub(crate) mod jvm;
pub(crate) mod llm;
#[cfg(feature = "lua")]
pub(crate) mod lua;
#[cfg(feature = "swift")]
pub(crate) mod macho;
pub(crate) mod man;
#[cfg(test)]
mod metadata_coverage;
#[cfg(feature = "mobile")]
pub(crate) mod mobile;
pub(crate) mod native;
pub(crate) mod native_match;
pub(crate) mod nir_source;
pub(crate) mod nuitka;
pub(crate) mod openvex;
pub(crate) mod output;
pub(crate) mod pass_registry;
#[cfg(feature = "chain")]
pub(crate) mod path_ops;
#[cfg(feature = "php")]
pub(crate) mod php;
#[cfg(feature = "pickle")]
pub(crate) mod pickle;
#[cfg(feature = "plugin")]
pub(crate) mod plugin;
pub(crate) mod progress_ui;
pub(crate) mod prowl;
pub(crate) mod py;
pub(crate) mod pyarmor;
pub(crate) mod pyfreeze;
pub(crate) mod pyinstaller;
pub(crate) mod query;
pub(crate) mod rename;
#[cfg(feature = "chain")]
pub(crate) mod report;
#[cfg(feature = "chain")]
pub(crate) mod report_forensic;
#[cfg(feature = "chain")]
pub(crate) mod report_html;
#[cfg(feature = "ruby")]
pub(crate) mod ruby;
pub(crate) mod sarif;
pub(crate) mod scan;
pub(crate) mod self_update;
#[cfg(feature = "server")]
pub(crate) mod serve;
#[cfg(feature = "shell")]
pub(crate) mod shell;
pub(crate) mod spdx;
pub(crate) mod status;
pub(crate) mod strings;
pub(crate) mod structured_document;
#[cfg(feature = "swift")]
pub(crate) mod swift;
pub(crate) mod taint;
pub(crate) mod util;
pub(crate) mod vulnmatch;
#[cfg(feature = "wasm")]
pub(crate) mod wasm;
pub(crate) mod wasm_cmd;
pub(crate) mod webview;
pub(crate) mod yara;
