#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod common;

use std::path::Path;

use disrobe_pass_go::{GoAnalysis, GoTypeRef, analyze};

fn has_source_ext(path: &str) -> bool {
    Path::new(path).extension().is_some_and(|ext| {
        ["go", "s", "c", "h", "cpp"]
            .iter()
            .any(|want: &&str| ext.eq_ignore_ascii_case(want))
    })
}

#[test]
fn modulename_recovered_from_buildinfo_on_embed_fixture() {
    let bytes: Vec<u8> = common::fixture(common::HELLO_EMBED);
    let analysis: GoAnalysis = analyze(&bytes).expect("analyze embed");
    assert_eq!(
        analysis.moduledata.modulename.as_deref(),
        Some("embedfix"),
        "embed fixture's go.mod module is `embedfix`; the buildinfo blob must surface it"
    );
}

#[test]
fn modulename_absent_when_buildinfo_stripped() {
    let bytes: Vec<u8> = common::fixture(common::HELLO_GARBLE);
    let analysis: GoAnalysis = analyze(&bytes).expect("analyze garble");
    assert!(
        analysis.moduledata.modulename.is_none(),
        "garble strips the buildinfo module path to `unknown`; recovery must honestly report None, \
         got {:?}",
        analysis.moduledata.modulename
    );
}

#[test]
fn typemeta_recovers_names_on_real_386_binary() {
    let bytes: Vec<u8> = common::fixture(common::HELLO_386);
    let analysis: GoAnalysis = analyze(&bytes).expect("analyze 386");
    assert_eq!(analysis.ptr_size, 4, "expected a 32-bit (ptr_size=4) image");

    let total: usize = analysis.typemeta.types.len();
    let named: usize = analysis
        .typemeta
        .types
        .iter()
        .filter(|t: &&GoTypeRef| t.name.is_some())
        .count();
    assert!(
        total > 100,
        "32-bit go1.26.3 fixture should expose hundreds of types via typelinks (got {total})"
    );
    let ratio: f64 = (named as f64) / (total.max(1) as f64);
    assert!(
        ratio >= 0.85,
        "32-bit abi.Type str_off/kind_off must be wired: expected >= 85% type-name recovery \
         (got {named}/{total} = {ratio:.3}); a hardcoded 64-bit layout reads past the 28-byte \
         32-bit struct and yields garbage"
    );

    let names: Vec<&str> = analysis
        .typemeta
        .types
        .iter()
        .filter_map(|t: &GoTypeRef| t.name.as_deref())
        .collect();
    for pkg in ["runtime.", "abi."] {
        assert!(
            names.iter().any(|n: &&str| n.contains(pkg)),
            "expected a recovered 32-bit type name containing '{pkg}'"
        );
    }
    assert!(
        analysis
            .typemeta
            .types
            .iter()
            .any(|t: &GoTypeRef| t.kind_label.as_deref() == Some("ptr")),
        "32-bit kind_off must decode: expected at least one 'ptr' kind"
    );
}

#[test]
fn source_files_walked_via_cutab_not_brute_force() {
    let bytes: Vec<u8> = common::fixture(common::HELLO_NORMAL);
    let analysis: GoAnalysis = analyze(&bytes).expect("analyze normal");
    let files: &[String] = &analysis.symbols.source_files;
    assert!(
        files.len() > 50,
        "the filetab/cutab walk should recover the stdlib file set"
    );

    assert!(
        files.iter().any(|f: &String| f == "<autogenerated>"),
        "the cutab walk must surface the '<autogenerated>' compiler-unit entry that the old \
         .go/.s slash heuristic dropped"
    );
    assert!(
        files.iter().any(|f: &String| f.ends_with("main.go")),
        "expected the main package source file"
    );
    assert!(
        files.iter().any(|f: &String| f == "errors/errors.go"),
        "expected canonical stdlib source path errors/errors.go"
    );

    let garbage: Vec<&String> = files
        .iter()
        .filter(|f: &&String| f.as_str() != "<autogenerated>" && !has_source_ext(f))
        .collect();
    assert!(
        garbage.is_empty(),
        "the filetab/cutab walk must not admit non-source entries (the brute-force whole-body \
         scan did): {garbage:?}"
    );
}

#[test]
fn source_files_recovered_on_386_image() {
    let bytes: Vec<u8> = common::fixture(common::HELLO_386);
    let analysis: GoAnalysis = analyze(&bytes).expect("analyze 386");
    let files: &[String] = &analysis.symbols.source_files;
    assert!(
        files.iter().any(|f: &String| f == "<autogenerated>"),
        "32-bit filetab/cutab walk must also surface '<autogenerated>'"
    );
    assert!(
        files.iter().any(|f: &String| f == "runtime/proc.go"),
        "expected runtime/proc.go in the 32-bit source file set"
    );
}
