// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Calculator = function(label) {
	this.label = label;
};
Calculator.prototype = {
	add: function(a,b) {
		return a + b;
	}
	,describe: function() {
		return "Calculator: " + this.label;
	}
};
var Main = function() { };
Main.main = function() {
	var calc = new Calculator("disrobe-demo");
	var sum = calc.add(21,21);
	console.log("Main.hx:21:",calc.describe());
	console.log("Main.hx:22:","Sum is " + sum);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
