// Generated by Haxe 4.3.6
(function ($global) { "use strict";
var Main = function() { };
Main.greet = function(name) {
	return "Hello, " + name + "!";
};
Main.add = function(a,b) {
	return a + b;
};
Main.main = function() {
	console.log("Main.hx:9:",Main.greet("disrobe"));
	console.log("Main.hx:10:",Main.add(2,3));
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
