#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use disrobe_pass_js_deob::v8::{
    BytenodeCacheHeader, HeaderLayout, NodeVersion, V8_HEADER_SIZE_V11, V8_HEADER_SIZE_V12,
    V8_MAGIC_NODE_18, V8_MAGIC_NODE_20, V8_MAGIC_NODE_22, V8_MAGIC_NODE_24, parse_bytenode_header,
};

fn corpus_dir() -> PathBuf {
    let manifest: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .ancestors()
        .nth(2)
        .map(|p: &Path| p.to_path_buf())
        .unwrap_or(manifest)
        .join("corpus/v8")
}

fn fixture_path(label: &str) -> PathBuf {
    corpus_dir()
        .join(format!("node-{label}"))
        .join(format!("hello-{label}.jsc"))
}

fn assert_real_jsc_matches_exactly(
    label: &str,
    expected_node: NodeVersion,
    expected_magic: u32,
    expected_layout: HeaderLayout,
    expected_header_size: usize,
) {
    let path: PathBuf = fixture_path(label);
    let Ok(bytes): std::io::Result<Vec<u8>> = std::fs::read(&path) else {
        eprintln!(
            "FIXTURE PENDING: no real .jsc for node-{label} at {}; \
             only the locally-installed Node major can be regenerated (this host has Node 24). \
             Regenerate via `node -e \"require('fs').writeFileSync('hello-{label}.jsc', \
             new (require('vm').Script)(src,{{produceCachedData:true}}).cachedData)\"` on a real \
             Node {label} install and drop it into corpus/v8/node-{label}/.",
            path.display()
        );
        return;
    };
    let header: BytenodeCacheHeader = parse_bytenode_header(&bytes)
        .unwrap_or_else(|e| panic!("real .jsc {label} should parse but errored: {e}"));
    assert_eq!(
        header.magic_number, expected_magic,
        "real .jsc {label}: magic mismatch (got 0x{:08X}, expected 0x{:08X}); \
         tests must NOT accept Unknown as a pass condition on real fixtures",
        header.magic_number, expected_magic
    );
    assert_eq!(
        header.version_hash.node, expected_node,
        "real .jsc {label}: node version mismatch (got {:?}, expected {:?}); \
         was the .jsc generated by a different Node major than declared?",
        header.version_hash.node, expected_node
    );
    assert_eq!(
        header.layout, expected_layout,
        "real .jsc {label}: header layout mismatch (got {:?}, expected {:?})",
        header.layout, expected_layout
    );
    assert_eq!(header.header_size, expected_header_size);
    assert!(
        header.payload_length > 0u32,
        "real .jsc {label}: payload_length must be > 0",
    );
    let total: usize = header.header_size + header.payload_length as usize;
    assert_eq!(
        total,
        bytes.len(),
        "real .jsc {label}: header_size ({}) + payload_length ({}) must equal filesize ({})",
        header.header_size,
        header.payload_length,
        bytes.len()
    );
}

#[test]
fn node_18_real_fixture_parses_with_exact_real_magic_and_v11_layout() {
    assert_real_jsc_matches_exactly(
        "18",
        NodeVersion::Node18,
        V8_MAGIC_NODE_18,
        HeaderLayout::V11,
        V8_HEADER_SIZE_V11,
    );
}

#[test]
fn node_20_real_fixture_parses_with_exact_real_magic_and_v11_layout() {
    assert_real_jsc_matches_exactly(
        "20",
        NodeVersion::Node20,
        V8_MAGIC_NODE_20,
        HeaderLayout::V11,
        V8_HEADER_SIZE_V11,
    );
}

#[test]
fn node_22_real_fixture_parses_with_exact_real_magic_and_v12_layout() {
    assert_real_jsc_matches_exactly(
        "22",
        NodeVersion::Node22,
        V8_MAGIC_NODE_22,
        HeaderLayout::V12,
        V8_HEADER_SIZE_V12,
    );
}

#[test]
fn node_24_real_fixture_parses_with_exact_real_magic_and_v12_layout() {
    assert_real_jsc_matches_exactly(
        "24",
        NodeVersion::Node24,
        V8_MAGIC_NODE_24,
        HeaderLayout::V12,
        V8_HEADER_SIZE_V12,
    );
}

#[test]
fn at_least_one_real_jsc_fixture_is_present_and_validated() {
    let labels: [&str; 4] = ["18", "20", "22", "24"];
    let present: usize = labels
        .iter()
        .filter(|label: &&&str| fixture_path(label).is_file())
        .count();
    assert!(
        present > 0,
        "no real .jsc fixtures under corpus/v8/node-{{18,20,22,24}}; the V8 deserializer \
         track requires at least one genuine V8-produced fixture (this host can regenerate \
         the node-24 one via `node`)"
    );
}
