"""Generate the disrobe pickle fixture corpus across protocols 0-5.

Run: python corpus/pickle/generate.py
Writes .pkl binaries (gitignored) into category subdirs and rewrites
MANIFEST.toml (sha256-pinned), mirroring the sibling corpus manifests.
"""

from __future__ import annotations

import hashlib
import pickle
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

ROOT: Path = Path(__file__).resolve().parent
PROTOCOLS: tuple[int, ...] = (0, 1, 2, 3, 4, 5)


@dataclass(frozen=True)
class Sample:
    name: str
    source_tool: str
    size_bytes: int
    sha256: str
    notes: str


class ReduceShell:
    """A __reduce__-bearing object: unpickling calls os.system('echo pwned')."""

    def __reduce__(self) -> tuple[Callable[..., Any], tuple[str, ...]]:
        import os

        return (os.system, ("echo pwned",))


class StateObj:
    def __init__(self) -> None:
        self.a: int = 1
        self.b: str = "two"


def benign_values() -> dict[str, Any]:
    return {
        "int": 42,
        "neg_int": -7,
        "big_int": 2**128 + 1,
        "float": 3.14159,
        "str": "hello é world",
        "bytes": b"\x00\x01\x02\xff",
        "bool_true": True,
        "bool_false": False,
        "none": None,
        "list": [1, 2, [3, 4], "five"],
        "nested_dict": {"k": {"inner": [1, 2, 3]}, "n": 9},
        "tuple": (1, "a", (2, 3)),
        "set": {1, 2, 3},
        "frozenset": frozenset({4, 5, 6}),
        "instance": StateObj(),
    }


def malicious_values() -> dict[str, Any]:
    return {
        "reduce_os_system": ReduceShell(),
    }


def write_pickle(path: Path, obj: Any, proto: int) -> Sample:
    data: bytes = pickle.dumps(obj, protocol=proto)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return Sample(
        name=str(path.relative_to(ROOT)).replace("\\", "/"),
        source_tool=f"CPython pickle.dumps(protocol={proto})",
        size_bytes=len(data),
        sha256=hashlib.sha256(data).hexdigest(),
        notes=f"protocol {proto}",
    )


def build() -> list[Sample]:
    samples: list[Sample] = []
    for proto in PROTOCOLS:
        for key, value in benign_values().items():
            p: Path = ROOT / "benign" / f"p{proto}" / f"{key}.pkl"
            samples.append(write_pickle(p, value, proto))
        for key, value in malicious_values().items():
            p = ROOT / "malicious" / f"p{proto}" / f"{key}.pkl"
            samples.append(write_pickle(p, value, proto))
    return samples


def render_manifest(samples: list[Sample]) -> str:
    lines: list[str] = [
        'schema = "disrobe-corpus-v1"',
        'category = "pickle"',
        'target_crate = "disrobe-pass-pickle"',
        'fetched_utc = "2026-05-27T00:00:00Z"',
        'notes = """',
        "Clean-room pickle fixtures generated by generate.py with CPython 3.14.",
        "Coverage: every benign Python type (int/float/str/bytes/bool/None/list/",
        "dict/tuple/set/frozenset/class-instance) and a __reduce__-bearing",
        "malicious object (os.system) emitted at all six protocols (0-5).",
        "Binaries are gitignored; regenerate with `python corpus/pickle/generate.py`.",
        '"""',
        "",
    ]
    for s in samples:
        lines.extend(
            [
                "[[sample]]",
                f'name = "{s.name}"',
                f'source_tool = "{s.source_tool}"',
                f"size_bytes = {s.size_bytes}",
                f'sha256 = "{s.sha256}"',
                f'notes = "{s.notes}"',
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    samples: list[Sample] = build()
    (ROOT / "MANIFEST.toml").write_text(render_manifest(samples), encoding="utf-8")
    print(f"wrote {len(samples)} pickle fixtures + MANIFEST.toml")


if __name__ == "__main__":
    main()
