# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def comp(n: int) -> list:
    ...

def safe_div(a: int, b: int) -> int:
    ...

def with_default(a: int, b: int) -> int:
    ...

def varargs() -> int:
    ...

def closure(n: int) -> int:
    ...

def dict_comp(n: int) -> dict:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
