# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def add(a: int, b: int) -> int:
    ...

def sub(a: int, b: int) -> int:
    ...

def mul(a: int, b: int) -> int:
    ...

def addmul(a: int, b: int, c: int) -> int:
    ...

def neg(a: int) -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
