# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def is_pos(n: int) -> bool:
    ...

def is_eq(a: int, b: int) -> bool:
    ...

def in_range(n: int) -> bool:
    ...

def clamp_low(n: int) -> int:
    ...

def sign(n: int) -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
