# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def make_pair(a: int, b: int) -> list:
    ...

def make_dict(k: str, v: int) -> dict:
    ...

def first(items: list) -> int:
    ...

def pair_sum(items: list) -> int:
    ...

def boolop(a: int, b: int) -> bool:
    ...

def ternary(n: int) -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
