# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def greet(name: str) -> str:
    ...

def fib(n: int) -> int:
    ...

def main() -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
