# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def total(n: int) -> int:
    ...

def countdown(n: int) -> int:
    ...

def accumulate(n: int) -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
