# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

def stats(a: int, b: int) -> int:
    ...

def scale(x: int) -> int:
    ...

def swap_sum(a: int, b: int) -> int:
    ...

def absval(n: int) -> int:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
