-- This file was generated by Luraph (lura.ph)
-- The original source has been compiled to encrypted virtual-machine bytecode.
-- Macros referenced by the build: LPH_ENCFUNC LPH_NO_VIRTUALIZE LPH_JIT LPH_STRING
local LPH_ENCSTR = nil
return (function(...)
    local v = { 0x4c, 0x50, 0x48, 0x21 }
    local k = (function() return (os.time() % 256) end)()
    local bc = "\27\76\80\72" .. string.rep("\0", 32)
    return v, k, bc
end)(...)
