#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum KoiOp {
    Nop = 0,
    LindPtr = 1,
    LindObject = 2,
    LindByte = 3,
    LindWord = 4,
    LindDword = 5,
    LindQword = 6,
    SindPtr = 7,
    SindObject = 8,
    SindByte = 9,
    SindWord = 10,
    SindDword = 11,
    SindQword = 12,
    Pop = 13,
    PushrObject = 14,
    PushrByte = 15,
    PushrWord = 16,
    PushrDword = 17,
    PushrQword = 18,
    PushiDword = 19,
    PushiQword = 20,
    SxByte = 21,
    SxWord = 22,
    SxDword = 23,
    Call = 24,
    Ret = 25,
    NorDword = 26,
    NorQword = 27,
    Cmp = 28,
    CmpDword = 29,
    CmpQword = 30,
    CmpR32 = 31,
    CmpR64 = 32,
    Jz = 33,
    Jnz = 34,
    Jmp = 35,
    Swt = 36,
    AddDword = 37,
    AddQword = 38,
    AddR32 = 39,
    AddR64 = 40,
    SubR32 = 41,
    SubR64 = 42,
    MulDword = 43,
    MulQword = 44,
    MulR32 = 45,
    MulR64 = 46,
    DivDword = 47,
    DivQword = 48,
    DivR32 = 49,
    DivR64 = 50,
    RemDword = 51,
    RemQword = 52,
    RemR32 = 53,
    RemR64 = 54,
    ShrDword = 55,
    ShrQword = 56,
    ShlDword = 57,
    ShlQword = 58,
    FconvR32R64 = 59,
    FconvR64R32 = 60,
    FconvR32 = 61,
    FconvR64 = 62,
    IconvPtr = 63,
    IconvR64 = 64,
    Vcall = 65,
    Try = 66,
    Leave = 67,
}

pub const KOI_OP_MAX: u8 = 68;

impl KoiOp {
    #[must_use]
    pub const fn from_ordinal(value: u8) -> Option<Self> {
        let op: Self = match value {
            0 => Self::Nop,
            1 => Self::LindPtr,
            2 => Self::LindObject,
            3 => Self::LindByte,
            4 => Self::LindWord,
            5 => Self::LindDword,
            6 => Self::LindQword,
            7 => Self::SindPtr,
            8 => Self::SindObject,
            9 => Self::SindByte,
            10 => Self::SindWord,
            11 => Self::SindDword,
            12 => Self::SindQword,
            13 => Self::Pop,
            14 => Self::PushrObject,
            15 => Self::PushrByte,
            16 => Self::PushrWord,
            17 => Self::PushrDword,
            18 => Self::PushrQword,
            19 => Self::PushiDword,
            20 => Self::PushiQword,
            21 => Self::SxByte,
            22 => Self::SxWord,
            23 => Self::SxDword,
            24 => Self::Call,
            25 => Self::Ret,
            26 => Self::NorDword,
            27 => Self::NorQword,
            28 => Self::Cmp,
            29 => Self::CmpDword,
            30 => Self::CmpQword,
            31 => Self::CmpR32,
            32 => Self::CmpR64,
            33 => Self::Jz,
            34 => Self::Jnz,
            35 => Self::Jmp,
            36 => Self::Swt,
            37 => Self::AddDword,
            38 => Self::AddQword,
            39 => Self::AddR32,
            40 => Self::AddR64,
            41 => Self::SubR32,
            42 => Self::SubR64,
            43 => Self::MulDword,
            44 => Self::MulQword,
            45 => Self::MulR32,
            46 => Self::MulR64,
            47 => Self::DivDword,
            48 => Self::DivQword,
            49 => Self::DivR32,
            50 => Self::DivR64,
            51 => Self::RemDword,
            52 => Self::RemQword,
            53 => Self::RemR32,
            54 => Self::RemR64,
            55 => Self::ShrDword,
            56 => Self::ShrQword,
            57 => Self::ShlDword,
            58 => Self::ShlQword,
            59 => Self::FconvR32R64,
            60 => Self::FconvR64R32,
            61 => Self::FconvR32,
            62 => Self::FconvR64,
            63 => Self::IconvPtr,
            64 => Self::IconvR64,
            65 => Self::Vcall,
            66 => Self::Try,
            67 => Self::Leave,
            _ => return None,
        };
        Some(op)
    }

    #[must_use]
    pub const fn operand(self) -> KoiOperand {
        match self {
            Self::PushiDword => KoiOperand::ImmDword,
            Self::PushiQword => KoiOperand::ImmQword,
            Self::PushrObject
            | Self::PushrByte
            | Self::PushrWord
            | Self::PushrDword
            | Self::PushrQword
            | Self::Pop => KoiOperand::Register,
            _ => KoiOperand::None,
        }
    }

    #[must_use]
    pub const fn is_terminator(self) -> bool {
        matches!(
            self,
            Self::Ret | Self::Leave | Self::Jmp | Self::Jz | Self::Jnz | Self::Swt
        )
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Nop => "NOP",
            Self::LindPtr => "LIND_PTR",
            Self::LindObject => "LIND_OBJECT",
            Self::LindByte => "LIND_BYTE",
            Self::LindWord => "LIND_WORD",
            Self::LindDword => "LIND_DWORD",
            Self::LindQword => "LIND_QWORD",
            Self::SindPtr => "SIND_PTR",
            Self::SindObject => "SIND_OBJECT",
            Self::SindByte => "SIND_BYTE",
            Self::SindWord => "SIND_WORD",
            Self::SindDword => "SIND_DWORD",
            Self::SindQword => "SIND_QWORD",
            Self::Pop => "POP",
            Self::PushrObject => "PUSHR_OBJECT",
            Self::PushrByte => "PUSHR_BYTE",
            Self::PushrWord => "PUSHR_WORD",
            Self::PushrDword => "PUSHR_DWORD",
            Self::PushrQword => "PUSHR_QWORD",
            Self::PushiDword => "PUSHI_DWORD",
            Self::PushiQword => "PUSHI_QWORD",
            Self::SxByte => "SX_BYTE",
            Self::SxWord => "SX_WORD",
            Self::SxDword => "SX_DWORD",
            Self::Call => "CALL",
            Self::Ret => "RET",
            Self::NorDword => "NOR_DWORD",
            Self::NorQword => "NOR_QWORD",
            Self::Cmp => "CMP",
            Self::CmpDword => "CMP_DWORD",
            Self::CmpQword => "CMP_QWORD",
            Self::CmpR32 => "CMP_R32",
            Self::CmpR64 => "CMP_R64",
            Self::Jz => "JZ",
            Self::Jnz => "JNZ",
            Self::Jmp => "JMP",
            Self::Swt => "SWT",
            Self::AddDword => "ADD_DWORD",
            Self::AddQword => "ADD_QWORD",
            Self::AddR32 => "ADD_R32",
            Self::AddR64 => "ADD_R64",
            Self::SubR32 => "SUB_R32",
            Self::SubR64 => "SUB_R64",
            Self::MulDword => "MUL_DWORD",
            Self::MulQword => "MUL_QWORD",
            Self::MulR32 => "MUL_R32",
            Self::MulR64 => "MUL_R64",
            Self::DivDword => "DIV_DWORD",
            Self::DivQword => "DIV_QWORD",
            Self::DivR32 => "DIV_R32",
            Self::DivR64 => "DIV_R64",
            Self::RemDword => "REM_DWORD",
            Self::RemQword => "REM_QWORD",
            Self::RemR32 => "REM_R32",
            Self::RemR64 => "REM_R64",
            Self::ShrDword => "SHR_DWORD",
            Self::ShrQword => "SHR_QWORD",
            Self::ShlDword => "SHL_DWORD",
            Self::ShlQword => "SHL_QWORD",
            Self::FconvR32R64 => "FCONV_R32_R64",
            Self::FconvR64R32 => "FCONV_R64_R32",
            Self::FconvR32 => "FCONV_R32",
            Self::FconvR64 => "FCONV_R64",
            Self::IconvPtr => "ICONV_PTR",
            Self::IconvR64 => "ICONV_R64",
            Self::Vcall => "VCALL",
            Self::Try => "TRY",
            Self::Leave => "LEAVE",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KoiOperand {
    None,
    Register,
    ImmDword,
    ImmQword,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum KoiReg {
    R0 = 0,
    R1 = 1,
    R2 = 2,
    R3 = 3,
    R4 = 4,
    R5 = 5,
    R6 = 6,
    R7 = 7,
    Bp = 8,
    Sp = 9,
    Ip = 10,
    Fl = 11,
    K1 = 12,
    K2 = 13,
    M1 = 14,
    M2 = 15,
}

impl KoiReg {
    #[must_use]
    pub const fn from_ordinal(value: u8) -> Option<Self> {
        let reg: Self = match value {
            0 => Self::R0,
            1 => Self::R1,
            2 => Self::R2,
            3 => Self::R3,
            4 => Self::R4,
            5 => Self::R5,
            6 => Self::R6,
            7 => Self::R7,
            8 => Self::Bp,
            9 => Self::Sp,
            10 => Self::Ip,
            11 => Self::Fl,
            12 => Self::K1,
            13 => Self::K2,
            14 => Self::M1,
            15 => Self::M2,
            _ => return None,
        };
        Some(reg)
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::R0 => "R0",
            Self::R1 => "R1",
            Self::R2 => "R2",
            Self::R3 => "R3",
            Self::R4 => "R4",
            Self::R5 => "R5",
            Self::R6 => "R6",
            Self::R7 => "R7",
            Self::Bp => "BP",
            Self::Sp => "SP",
            Self::Ip => "IP",
            Self::Fl => "FL",
            Self::K1 => "K1",
            Self::K2 => "K2",
            Self::M1 => "M1",
            Self::M2 => "M2",
        }
    }
}
